[service]
listen = "0.0.0.0"
port   = 10103

[memcache]
ttl = 15

[log]
level = "error"
scoped_levels = ["tokio_core=error","tokio_reactor=error","zmq=error","hyper=error"]

[datastore]
user = "automate-builder-api"
database = "automate-builder-api"
connection_retry_ms = 300
connection_timeout_sec = 3600
db_workers = 4
host = "127.0.0.1"
port = 5432
