#!/usr/bin/env bash
#
# Copyright 2012-2019 Chef Software, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _CLUSTER_CTL_ROOT="$(abs_dirname "$libexec_path")"
export _CLUSTER_CTL_CMD="automate-cluster-ctl"
export _CLUSTER_CTL_COMMAND="$1"
export _CLUSTER_CTL_VERSION="${AUTOMATE_CLUSTER_VERSION:-DEV}"

# If not provided to use set it to our vendor/bundle
if [[ -z "${GEM_PATH}" ]]; then
  export GEM_PATH="$_CLUSTER_CTL_ROOT/vendor/bundle/ruby/3.0.0"
  export GEM_HOME="$_CLUSTER_CTL_ROOT/vendor/bundle/ruby/3.0.0"
fi

export PATH="${libexec_path}:$PATH"

case "$_CLUSTER_CTL_COMMAND" in
"" | "-h" | "--help" )
  exec cluster-help
  ;;
* )
  command_path="$(command -v "cluster-$_CLUSTER_CTL_COMMAND" || true)"
  if [ ! -x "$command_path" ]; then
    echo "automate-cluster-ctl: no such command \`$_CLUSTER_CTL_COMMAND'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
