#!{{pkgPathFor "core/bash"}}/bin/sh

exec 2>&1

set -e

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

{{#if cfg.required_recipe.enabled ~}}
# Copy the required_recipe into the service's data directory and
# ensure it has permissions that the service user can read.
touch {{pkg.svc_var_path}}/required_recipe
chown hab:hab {{pkg.svc_var_path}}/required_recipe
chmod 0400 {{pkg.svc_var_path}}/required_recipe

# Copy the required_recipe into the service's data directory
cp {{cfg.required_recipe.path}} {{pkg.svc_var_path}}/required_recipe
{{/if}}

# Nginx starts as root and drops priveleges to hab, so these files
# need to be readable by hab at runtime and not just on startup.
chown -R hab:hab "{{pkg.svc_config_path}}" "{{pkg.svc_data_path}}" "{{pkg.svc_var_path}}"

exec openresty -c {{pkg.svc_config_path}}/nginx.conf -p {{pkg.svc_var_path}}
