[mlsa]
accept = false

[service]
host = "localhost"
port = 10130

[logger]
format = "json"
level = "info"

[storage]
database = "chef_authz_service"
user = "authz"
max_idle_connections = 10
max_connections = 10
