#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
# {{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}
# guess : above line is the licence check 

#pg-helper ensure-service-database "chef_keyval_service"

exec keyval-service #serve --config {{pkg.svc_config_path}}/config.json
