#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

# Start es-sidecar-service
exec es-sidecar-service serve --config {{pkg.svc_config_path}}/config.toml
