source 'https://rubygems.org'

gem 'minitest', '~> 5.6'
gem 'pry', '~> 0.10'
gem 'rb-readline', '~> 0.5'
gem 'minitest-hooks', '~> 1.5.0'
gem 'grpc', '= 1.18.0'
gem 'grpc-tools', '= 1.18.0'
gem 'google-protobuf', '= 3.6.1'
