grpc = "127.0.0.1:{{cfg.service.port}}"
log-format = "{{cfg.log.format}}"
log-level = "{{cfg.log.level}}"
database = "{{cfg.storage.database}}"
migrations-path = "{{pkg.path}}/migrations"
authz-address = "127.0.0.1:{{cfg.authz.port}}"
secrets-address = "127.0.0.1:{{cfg.secrets.port}}"

[tls]
cert_path = "{{pkg.svc_config_path}}/service.crt"
key_path = "{{pkg.svc_config_path}}/service.key"
root_ca_path ="{{pkg.svc_config_path}}/root_ca.crt"
