run:
  deadline: 5m
  tests: false

issues:
  exclude-use-default: false
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: false
  godox:
    keywords:
      - NOCOMMIT
  govet:
    disable:
      - assign
      - atomic
      - copylocks

linters:
  enable-all: true
  disable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gocognit
    - goconst
    - godot
    - goerr113
    - goimports
    - gomnd
    - goprintffuncname
    - maligned
    - megacheck
    - nestif
    - nolintlint
    - interfacer
    - golint
    - gas
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - rowserrcheck # too many false positives as of Feb 2021
    - scopelint
    - stylecheck
    - unparam
    - lll
    - whitespace
    - wsl
    - gci
    - gofumpt
    - gofmt
    - gomoddirectives
    - revive
    - containedctx
    - cyclop
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - nlreturn
    - nosnakecase
    - tagliatelle
    - varnamelen
    - wrapcheck
    
