run:
  deadline: 5m
  tests: false

issues:
  exclude-use-default: false
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: false
  godox:
    keywords:
      - NOCOMMIT
  govet:
    disable:
      - copylocks

linters:
  enable-all: true
  disable:
    - dogsled
    - dupl
    - funlen
    - gocognit
    - goconst
    - godot
    - goerr113
    - goimports
    - gomnd
    - maligned
    - megacheck
    - nestif
    - nolintlint
    - interfacer
    - golint
    - gas
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - rowserrcheck # too many false positives as of Feb 2021
    - scopelint
    - stylecheck
    - unparam
    - lll
    - whitespace
    - wsl
