run:
  deadline: 5m
  tests: false

issues:
  exclude-use-default: false
  max-same-issues: 0

linters-settings:
  godox:
    keywords:
      - NOCOMMIT

linters:
  enable-all: true
  disable:
    - dogsled
    - dupl
    - funlen
    - gocognit
    - goconst
    - maligned
    - megacheck
    - interfacer
    - golint
    - gas
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - scopelint
    - stylecheck
    - unparam
    - lll
    - whitespace
    - wsl
