---
name: a2
directories:
  - ./
  - ./api/external
  - ./components/applications-service
  - ./components/authn-service
  - ./components/authz-service
  - ./components/automate-cli
  - ./components/automate-cs-bookshelf
  - ./components/automate-cs-nginx
  - ./components/automate-cs-oc-bifrost
  - ./components/automate-cs-oc-erchef
  - ./components/automate-debug
  - ./components/automate-deployment
  - ./components/automate-dex
  - ./components/automate-elasticsearch
  - ./components/automate-es-gateway
  - ./components/automate-gateway
  - ./components/automate-grpc
  - ./components/automate-load-balancer
  - ./components/automate-openjdk
  - ./components/automate-pg-gateway
  - ./components/automate-platform-tools
  - ./components/automate-postgresql
  - ./components/automate-prometheus
  - ./components/automate-ui
  - ./components/automate-ui-devproxy
  - ./components/automate-workflow-ctl
  - ./components/automate-workflow-web
  - ./components/automate-workflow-nginx
  - ./components/automate-workflow-server
  - ./components/backup-gateway
  - ./components/cereal-service
  - ./components/chef-ui-library
  - ./components/compliance-service
  - ./components/config-mgmt-service
  - ./components/es-sidecar-service
  - ./components/event-feed-service
  - ./components/event-gateway
  - ./components/event-service
  - ./components/ingest-service
  - ./components/license-control-service
  - ./components/local-user-service
  - ./components/nodemanager-service
  - ./components/notifications-client
  - ./components/notifications-service
  - ./components/notifications-service/server
  - ./components/pg-sidecar-service
  - ./components/release-mgmt-dashboard
  - ./components/secrets-service
  - ./components/session-service
  - ./components/teams-service
  - ./components/trial-license-service

habitat:
  channel_for_origin:
    - origin: chef
      channel: dev
allowed_licenses:
  - Apache-1.0
  - Apache-1.1
  - Apache-2.0
  - Artistic-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - BSD-3-Clause-Attribution
  - BSD-Source-Code
  - BSL-2.0
  - bzip2-1.0.6
  - CC0-1.0
  - CC-BY-2.0
  - CC-BY-3.0
  - CC-BY-4.0
  - curl
  - gnuplot
  - ICU
  - ISC
  - MIT
  - MPL-2.0
  - OpenSSL
  - PHP-3.0
  - PHP-3.01
  - PostgreSQL
  - Python-2.0
  - SAX-PD
  - Unlicense
  - WTFPL
  - Zlib

fallbacks:
  golang:
    - name: github.com/kevinburke/go-bindata
      license_id: CC0-1.0
      license_content: https://raw.githubusercontent.com/kevinburke/go-bindata/master/LICENSE
    - name: github.com/Masterminds/squirrel
      license_id: MIT
      license_content: https://github.com/Masterminds/squirrel/blob/master/LICENSE.txt
    - name: github.com/fatih/color
      license_id: MIT
      license_content: https://github.com/fatih/color/blob/master/LICENSE.md
    - name: gopkg.in/segmentio/analytics-go.v3
      license_id: MIT
      license_content: https://github.com/segmentio/analytics-go/blob/v3.1.0/License.md
    - name: github.com/ghodss/yaml
      license_id: MIT
      license_content: https://raw.githubusercontent.com/ghodss/yaml/master/LICENSE
    - name: github.com/golang/protobuf
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/protobuf/master/LICENSE
    - name: github.com/inconshreveable/mousetrap
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/inconshreveable/mousetrap/master/LICENSE
    - name: github.com/jmespath/go-jmespath
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/jmespath/go-jmespath/master/LICENSE
    - name: github.com/lib/pq
      license_id: MIT
      license_content: https://raw.githubusercontent.com/lib/pq/master/LICENSE.md
    - name: github.com/magiconair/properties
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/magiconair/properties/master/LICENSE
    - name: github.com/golang-migrate/migrate
      license_id: MIT
      license_content: https://raw.githubusercontent.com/golang-migrate/migrate/master/LICENSE
    - name: github.com/pmezard/go-difflib
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/pmezard/go-difflib/master/LICENSE
    - name: github.com/rcrowley/go-metrics
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/rcrowley/go-metrics/master/LICENSE
    - name: github.com/segmentio/backo-go
      license_id: MIT
      license_content: https://raw.githubusercontent.com/segmentio/backo-go/master/README.md
    - name: github.com/stretchr/objx
      license_id: MIT
      license_content: https://raw.githubusercontent.com/stretchr/objx/master/LICENSE
    - name: github.com/stretchr/testify
      license_id: MIT
      license_content: https://raw.githubusercontent.com/stretchr/testify/master/LICENSE
    - name: gopkg.in/asn1-ber.v1
      license_id: MIT
      license_content: https://raw.githubusercontent.com/go-asn1-ber/asn1-ber/v1.2/LICENSE
    - name: gopkg.in/ldap.v2
      license_id: MIT
      license_content: https://raw.githubusercontent.com/go-ldap/ldap/v2.5.1/LICENSE
    - name: github.com/beevik/etree
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/beevik/etree/master/LICENSE
    - name: github.com/gogo/protobuf
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gogo/protobuf/master/LICENSE
    - name: gopkg.in/yaml.v3
      license_id: MIT
      license_content: https://raw.githubusercontent.com/go-yaml/yaml/v3/LICENSE
    - name: github.com/bgentry/go-netrc
      license_id: MIT
      license_content: https://raw.githubusercontent.com/bgentry/go-netrc/master/LICENSE
    - name: bazil.org/fuse
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/bazil/fuse/master/LICENSE
    - name: github.com/BurntSushi/xgb
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/BurntSushi/xgb/master/LICENSE
    - name: github.com/bmizerany/assert
      license_id: MIT
      license_content: https://raw.githubusercontent.com/bmizerany/assert/master/README.md
    - name: github.com/gonum/blas
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gonum/license/master/LICENSE
    - name: github.com/gonum/floats
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gonum/license/master/LICENSE
    - name: github.com/gonum/internal
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gonum/license/master/LICENSE
    - name: github.com/gonum/lapack
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gonum/license/master/LICENSE
    - name: github.com/gonum/matrix
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/gonum/license/master/LICENSE
    - name: github.com/julienschmidt/httprouter
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/julienschmidt/httprouter/master/LICENSE
    - name: github.com/kr/logfmt
      license_id: MIT
      license_content: https://raw.githubusercontent.com/kr/logfmt/master/Readme
    - name: github.com/miekg/dns
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/miekg/dns/master/LICENSE
    - name: github.com/pascaldekloe/goe
      license_id: CC0-1.0
      license_content: https://raw.githubusercontent.com/pascaldekloe/goe/master/LICENSE
    - name: github.com/russross/blackfriday/v2
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/russross/blackfriday/master/LICENSE.txt
    - name: github.com/russross/blackfriday
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/russross/blackfriday/master/LICENSE.txt
    - name: github.com/sean-/seed
      license_id: MIT
      license_content: https://raw.githubusercontent.com/sean-/seed/master/LICENSE
    - name: github.com/smartystreets/assertions
      license_id: MIT
      license_content: https://raw.githubusercontent.com/smartystreets/assertions/master/LICENSE.md
    - name: github.com/smartystreets/goconvey
      license_id: MIT
      license_content: https://raw.githubusercontent.com/smartystreets/goconvey/master/LICENSE.md
    - name: github.com/ziutek/mymysql
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/ziutek/mymysql/master/LICENSE
    - name: gopkg.in/check.v1
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/go-check/check/v1/LICENSE
    - name: gopkg.in/tomb.v1
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/go-tomb/tomb/v1/LICENSE
    - name: github.com/josharian/intern
      license_id: MIT
      license_content: https://raw.githubusercontent.com/josharian/intern/master/license.md
    - name: github.com/chzyer/logex
      license_id: MIT
      license_content: https://raw.githubusercontent.com/chzyer/logex/master/LICENSE
    - name: cloud.google.com/go
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
    - name: github.com/envoyproxy/protoc-gen-validate
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/envoyproxy/protoc-gen-validate/master/LICENSE
    - name: github.com/google/go-cmp
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/google/go-cmp/master/LICENSE
    - name: github.com/prometheus/client_model
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/prometheus/client_model/master/LICENSE
    - name: golang.org/x/exp
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/exp/master/LICENSE
    - name: golang.org/x/lint
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/lint/master/LICENSE
    - name: golang.org/x/sync
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/sync/master/LICENSE
    - name: golang.org/x/tools
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/tools/master/LICENSE
    - name: golang.org/x/xerrors
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/golang/xerrors/master/LICENSE
    - name: google.golang.org/appengine
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/golang/appengine/master/LICENSE
    - name: gopkg.in/yaml.v2
      license_id: Apache-2.0
      license_content: https://raw.githubusercontent.com/go-yaml/yaml/v2.3.0/LICENSE
    - name: honnef.co/go/tools
      license_id: MIT
      license_content: https://raw.githubusercontent.com/dominikh/go-tools/master/LICENSE

  habitat:
    - name: chef/mlsa
      license_id: Chef-MLSA
      license_content: https://gist.githubusercontent.com/chef-ci/6cd978229702e9cb35dbd7d29a162a22/raw/c4377c5875af52228e459e68f137d3035793c9cd/chef-mlsa.txt
    - name: core/ruby
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/ruby/ruby/trunk/COPYING
    - name: core/ruby26
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/ruby/ruby/trunk/COPYING
    - name: core/cacerts
      license_id: MPL-2.0
      license_content: https://curl.haxx.se/docs/caextract.html
    - name: core/mpfr (3.1.4-*)
      license_id: LGPL-3.0-or-later
      license_content: http://www.mpfr.org
    - name: core/bundler
      license_id: MIT
      license_content: https://raw.githubusercontent.com/bundler/bundler/master/LICENSE.md
    - name: core/sqitch_pg
      license_id: MIT
      license_content: https://raw.githubusercontent.com/sqitchers/sqitch/master/LICENSE.md
  nodejs:
    - name: arraybuffer.slice
      license_id: MIT
      license_content: https://raw.githubusercontent.com/rase-/arraybuffer.slice/master/LICENCE
    - name: better-assert
      license_id: MIT
      license_content: https://raw.githubusercontent.com/tj/better-assert/master/LICENSE
    - name: bytes
      license_id: MIT
      license_content: https://raw.githubusercontent.com/visionmedia/bytes.js/master/LICENSE
    - name: component-bind
      license_id: MIT
      license_content: https://raw.githubusercontent.com/component/bind/master/LICENSE
    - name: options
      license_id: MIT
      license_content: https://raw.githubusercontent.com/einaros/options.js/master/README.md
    - name: uglify-js (2.3.6)
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/mishoo/UglifyJS2/v2.3.6/LICENSE
    - name: rrule
      license_id: BSD-3-Clause
      license_content: https://raw.githubusercontent.com/jakubroztocil/rrule/master/LICENCE
  ruby:
    - name: syslog-logger
      license_id: MIT
      license_content: https://raw.githubusercontent.com/ngmoco/syslog_logger/master/README.rdoc
    - name: net-telnet
      license_id: Ruby
      license_content: https://raw.githubusercontent.com/ruby/net-telnet/master/LICENSE.txt
    - name: unf
      license_id: BSD-2-Clause
      license_content: https://raw.githubusercontent.com/knu/ruby-unf/master/LICENSE

exceptions:
  habitat:
    - name: chef/mlsa
      reason: Chef MLSA licensed
    - name: core/attr
      reason: Exception made by Chef Legal
    - name: core/bash
      reason: Exception made by Chef Legal
    - name: core/busybox-static
      reason: Exception made by Chef Legal
    - name: core/coreutils-static
      reason: Exception made by Chef Legal
    - name: core/coreutils
      reason: Exception made by Chef Legal
    - name: core/findutils
      reason: Exception made by Chef Legal
    - name: core/gawk
      reason: Exception made by Chef Legal
    - name: core/gcc-libs
      reason: Exception made by Chef Legal
    - name: core/gdbm
      reason: Exception made by Chef Legal
    - name: core/glibc
      reason: Exception made by Chef Legal
    - name: core/gmp
      reason: Exception made by Chef Legal
    - name: core/grep
      reason: Exception made by Chef Legal
    - name: core/inetutils
      reason: Exception made by Chef Legal
    - name: core/less
      reason: Exception made by Chef Legal
    - name: core/libcap
      reason: Exception made by Chef Legal
    - name: core/libtool
      reason: Exception made by Chef Legal
    - name: core/linux-headers
      reason: Exception made by Chef Legal
    - name: core/mpfr
      reason: Exception made by Chef Legal
    - name: core/mysql-client
      reason: Exception made by Chef Legal
    - name: core/net-tools
      reason: Exception made by Chef Legal
    - name: core/netcat
      reason: Exception made by Chef Legal
    - name: core/readline
      reason: Exception made by Chef Legal
    - name: core/rsync
      reason: Exception made by Chef Legal
    - name: core/sed
      reason: Exception made by Chef Legal
    - name: core/tar
      reason: Exception made by Chef Legal
    - name: core/git
      reason: (sf) Shell out only (already ship git in A1)
    - name: core/gettext
      reason: (sf) dep of core/git shell out only
    - name: core/xz
      reason: (sf) dep of core/git shell out only
    - name: core/wget
      reason: (sf) dep of core/elasticsearch for health_check shell out only
    - name: core/libidn
      reason: (sf) dep of core/wget shell out only
    - name: core/util-linux
      reason: (sd) Shell out only
    - name: core/haproxy
      reason: (sd) Binary use only. Already shipped in chef-server. Exception made by Chef Legal
    - name: chef/automate-openjdk
      reason: Exception made by Chef Legal
    - name: core/nss-myhostname
      reason: Exception made by Chef Legal
    - name: core/binutils
      reason: (rc) dep of core/bundler. Exception made by Stephen Delano, 4/23/20
    - name: core/perl
      reason: (rc) dep of core/git, used by Workflow and sqitch. Exception made by Stephen Delano, 4/23/20
    - name: core/procps-ng
      reason: Exception made by Chef Legal

  ruby:
    - name: highline
      reason: Ruby license (previously shipped in Automate 1)
    - name: httpclient
      reason: Ruby license (previously shipped in Automate 1)
    - name: json
      reason: Ruby license (previously shipped in Automate 1)
    - name: net-telnet
      reason: Ruby license (previously shipped in Automate 1)
    - name: rubyzip
      reason: BSD-1-Clause license (previously shipped in Automate 1)
    - name: sfl
      reason: Ruby license (previously shipped in Automate 1)
    - name: systemu
      reason: Ruby license (previously shipped in Automate 1)

  nodejs:
    - name: jschardet
      reason: Exception made by Chef Legal
