data_collector_url = "http://a2-dev.test/api/v0/events/data-collector"
data_collector_token = "GI2W7sf8ufQReZ1dUhSomPUVrnE="
#converge_status_json_file = "./sample-data/example-converge-status.json"
#ohai_json_file = "sample-data/ohai-data.json"
#log_file = "/tmp/chef-load.log"
#compliance_sample_reports_dir = "sample-data/inspec-reports"
#compliance_status_json_file = "sample-data/example-compliance-status.json"
## We use the generate command from chef-load, we don't have to set these options
## inside the config file since we will pass them through the command line
# num_nodes = 100
# num_actions = 10
# interval = 30
data_collector_url = "https://ec2-18-223-124-210.us-east-2.compute.amazonaws.com/api/v0/events/data-collector"
data_collector_token = "_Jxk3Jba1CQHRfkoVkKfne0MGms="
node_name_prefix = "focus_d8"
random_data = true
converge_status_json_file = "./components/ingest-service/examples/converge-success-report.json"
ohai_json_file = "./components/ingest-service/chef-load-data/ohai-data.json"
log_file = "/tmp/chef-load.log"
compliance_sample_reports_dir = "./components/compliance-service/chef-load-data/samples"
compliance_status_json_file = "./components/compliance-service/chef-load-data/compliance-status.json"
