# This is a Chef Automate AWS HA mode configuration file. You can run
# 'chef-automate deploy' with this config file and it should
# successfully create a new Chef Automate HA instances with default settings.

[architecture.existing_infra]
## === INPUT NEEDED ===
# Eg.: ssh_user = "ubuntu"
ssh_user = "ubuntu"

# private ssh key file path to access instances
# Eg.: ssh_user = "~/.ssh/A2HA.pem"
ssh_key_file = "~/.ssh/id_rsa"

# custome ssh port no to connect instances, default will be 22
# Eg.: ssh_port = "22"
#ssh_port = "22"

# Provide Password if needed to run sudo commands.
sudo_password = ""
## === ===

secrets_key_file = "/hab/a2_deploy_workspace/secrets.key"
secrets_store_file = "/hab/a2_deploy_workspace/secrets.json"
architecture = "existing_nodes"
workspace_path = "/hab/a2_deploy_workspace"
# DON'T MODIFY THE BELOW LINE (backup_mount)
backup_mount = "/mnt/automate_backups"

# Eg.: backup_config = "object_storage" or "file_system"
backup_config = "object_storage"

# If backup_config = "object_storage" fill out [object_storage.config] as well 
## Object storage similar to AWS S3 Bucket
[object_storage.config]
bucket_name = "test-a2ha-bucket"
access_key = "AKIARUQHMSKVV6XDBQBN"
secret_key = "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"
# For S3 bucket, default endpoint value is "https://s3.amazonaws.com"
# Include protocol to the enpoint value. Eg: https://customdns1.com or http://customdns2.com
endpoint = "https://s3.amazonaws.com"

# [Optional] Mention object_storage region if applicable
# Eg: region = "us-west-1"
region = "eu-north-1"
## === ===

# ============== EC2 Nodes Config ======================
[automate.config]
## === INPUT NEEDED ===

# Password for Automate UI for 'admin' user.
# admin_password = ""


# Automate Load Balancer FQDN eg.: "chefautomate.example.com"
fqdn = "testing-cert-node.eng.chefdemo.net"

# No. of Automate Frontend Machine or VM eg.: instance_count = "2"
instance_count = "1"

## === ===


# teams_port = ""
config_file = "configs/automate.toml"

# Set enable_custom_certs = true to provide custom certificates during deployment
enable_custom_certs = false
# Add Automate load balancer root-ca and keys
# root_ca = ""
# private_key = ""
# public_key = ""
# [[automate.config.certs_by_ip]]
# ip = ""
# private_key = ""
# public_key = ""

[chef_server.config]
## === INPUT NEEDED ===

# No. of Chef Server Frontend Machine or VM eg.: instance_count = "2"
instance_count = "1"

# Set enable_custom_certs = true to provide custom certificates during deployment
enable_custom_certs = false
# Add Chef Server load balancer root-ca and keys
# private_key = ""
# public_key = ""
# [[chef_server.config.certs_by_ip]]
# ip = ""
# private_key = ""
# public_key = ""

## === ===

[opensearch.config]
## === INPUT NEEDED ===

# No. of OpenSearch DB Backend Machine or VM eg.: instance_count = "3"
instance_count = "3"

# Set enable_custom_certs = true to provide custom certificates during deployment
enable_custom_certs = true
# Add OpenSearch load balancer root-ca and keys
root_ca = "-----BEGIN CERTIFICATE-----\nMIIDQjCCAioCCQCeQNCZoCCMRzANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE\nCgwRQ2hlZiBTb2Z0d2FyZSBJbmMxETAPBgNVBAMMCHByb2dyZXNzMB4XDTIzMDMx\nMDA5MzYxNFoXDTI2MDMwOTA5MzYxNFowYzELMAkGA1UEBhMCVVMxEzARBgNVBAgM\nCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUxGjAYBgNVBAoMEUNoZWYgU29m\ndHdhcmUgSW5jMREwDwYDVQQDDAhwcm9ncmVzczCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAM6vXY67dxX/DgjEDNaFOAqUgJTmsGAsJE1mdiouRPWZvtUH\nrQAtu83HTex5N7K9v66eeO7zAQRH0TiRTHEq4bquN9jKrRM3VVk9ScmILHACKETU\nba1O1tgdwAZ1bOyl1ZwlI1n38YkMUVqcEJMzccdHgAkrQ9c1NmBXLDT30APD41Vk\nuN6RSwWM7Xs3zz/5j43wfVlEAVxhNTs3+fn4JUj5zRgSl23O8VaX17fuzBdGlUCf\n3T6KsnrqBgphmvJOW7kpwjt2d3DqaE5FV7VOo2iXX3ODCk1pecg/XFmVEKiiyQnn\nUbAOTYnzXDvjD5mXXAaeggkHGtpyrNd3rdmV4AsCAwEAATANBgkqhkiG9w0BAQsF\nAAOCAQEAxbD+xjEt844OTKHRpA0QnhMu/HeDzgY3NAHMdmNHnBRTH4qANNYCay92\neKSLSJUjtFgcOZIdVu082ztNjV5WO1548y9R/enB5UTCHAarXC25vHhVM1NVGeAY\nDjitfPcQnW7go3fdoXW5H9/InvFBuTwp7qs0bKcrMfCP8Cw/WzUqU9f0Po5h0ZX6\nNxHNlBYl0RYqV5jYpDoklsqMSoSQrFMzb/uqSKvNn0q2iX3bZ5ALk9PnI9ILJLI3\n9tUMg9PiwUwr6xgWY6504pzdrJdztS1ejNg/mz0F0I8lJF1sdcw4+KbW0GYy43wY\ndJUfyq57+ubipZVKuC/Xtqzj3RRudA==\n-----END CERTIFICATE-----"
admin_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3zL76vfhPKNRv\njKUouWYGy37BZ3Axt29U3S/GKhTkoVa6h8FggCUBPUjMIF6+NG5/SfaDknJaQJ4o\nU8XGWm3qk7oquZAR8E2CTN0ktG1S/wODqw/N2K2aCe/Y57cL+gdZ7y0fQ/ad17OT\nKfJJAq85NeeC2PPpK64VLxjssD37eX1OpNrYajKW9PeJTY3tOxn+Resopm4JvJmv\nWA5kuGzgNcMMZN7R75Wkhj3S30lpfW0dPBFpPDZosjjN/Awwwx8KGNTUfV/H4Izy\nL1BkV+eg/eDdDcufhGh4SqguW9D6ITRXF35egk5aL9PJ+oruVkiirEQr8l9TpxYT\nvBs+7TPTAgMBAAECggEAOL5sY6sMoxu+4iVww+7hEc33dyxBFghExdV3r11EkAVD\nalkJGYrWYdiSxfpkZaJ4TrH9+kbXKQf0DA047PD0KEytWA1r7i3bMBQc3f0aF1qF\nsju4qFtx1TGmK7f16iup41kU/CcWV0rFtPRpSaMbh7UdoWbrfpwupXmh30jWCfHE\n/No09bIOD4XqyAhJW5Z59r2eydxA9MlWHs9QmbKASH4W00vsJ9MfZARAY5lBgPCj\nvr6LklewKphyxLFTKWcbTsxbF4cCacM4pyAFAJLsYR8Fv117b19aimlvo0iq+yJr\nG52/ZYy8c3pTNA1i6eXvxhuIuG8sapv8m94xEd/qKQKBgQDgD2qEtg29m7Ykr3nz\n6yrXkS/oHgfmr8uuScCjpmCMLaZ0DlsLRljpGgBUPxoQuzlawgsmmq6aHP7JbfJg\nTW2G9hhTMBzJEwZ57Lx7pqHkEm4oU594t++uDxmRtayEuhuwhm6C91HwE/MwS6WG\nYTqe8SAFuuKQ0qUz+d6BcyBmTQKBgQDSAB1AIfGFMdqzJOTA6phUyEQPhgT95Jwf\nfFkVx/u3aYL7HQcc676qhw+RSg+UVWrk08q+VZqMNe5Am/9MU4869MrSpT/BhpX/\ngbBFOlCQ4sWinh1zcu07839hpOBcfGHMxP8IPeBkJHhMt5pavLJFWGGOZNC8P717\nAm9/p61SnwKBgQCWL58tr75MHwibVIgBSNvhvO8IvsB7D9EOVV9sEoTa0WqmlkzO\npOvJ6+TWk6mMF4MdY74HtV1d7huWtzzk8mF9Oo4ZjMFuwnLv3RCGLa6MaxIts8fM\nKjbdTD/OXKF0Ii+XRrTi0pa4vxaeg8ZC6f9aNLRLQvbFLn0P9uf/i0TnbQKBgBgs\nWzGetqaWbo5gmNR8LLzVsL/4tWpkfnRBZB/VvWwHgURWuxLhMDmBApG+7LwuePeO\nSbBPOlMZgit9yY2HsN0ggJhu3T/xtiKLUzck11FWSVnGya0YdaaJCQi8afc7eiaQ\nJqtUNBhS+mYaXHJFdl/1JIW3pS+GRtF6HkubiaARAoGABiqG2KQ36PEoAxT8Wbs2\n+Qker4loNSRZx4JBlJu3kIP6ca+ipNqjg0lwX4WEZDK6VtGyp5rHCREwxSVr2per\nIF/36BzraUk82cXUyMGU0c9Aqpz180GtdoipbzV7Fl6fWvO9uHdG5YcjiklW48tg\n6A/Dze90cZVJZHWXa+3XExE=\n-----END PRIVATE KEY-----"
admin_cert = "-----BEGIN CERTIFICATE-----\nMIIDazCCAlOgAwIBAgIJAIkhwPJ4FTPyMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow\nGAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzERMA8GA1UEAwwIcHJvZ3Jlc3MwHhcN\nMjMwMzEwMDkzNjE1WhcNMjYwMzA5MDkzNjE1WjBkMQswCQYDVQQGEwJVUzETMBEG\nA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hl\nZiBTb2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBALfMvvq9+E8o1G+MpSi5ZgbLfsFncDG3b1TdL8Yq\nFOShVrqHwWCAJQE9SMwgXr40bn9J9oOSclpAnihTxcZabeqTuiq5kBHwTYJM3SS0\nbVL/A4OrD83YrZoJ79jntwv6B1nvLR9D9p3Xs5Mp8kkCrzk154LY8+krrhUvGOyw\nPft5fU6k2thqMpb094lNje07Gf5F6yimbgm8ma9YDmS4bOA1wwxk3tHvlaSGPdLf\nSWl9bR08EWk8NmiyOM38DDDDHwoY1NR9X8fgjPIvUGRX56D94N0Ny5+EaHhKqC5b\n0PohNFcXfl6CTlov08n6iu5WSKKsRCvyX1OnFhO8Gz7tM9MCAwEAAaMhMB8wHQYD\nVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IBAQCj\ncXKrvVhfplZ7SIFVF3qCPXfzaICzXf5davU3rpM1YJ5KTnqHvSH8r6rGILFwN1bd\n/9b37GoyT1w1LLwWKaZDZ17d4M2/UL+FR+OAourGRWqJ4OZwpHeAB84r5gsZ+sIt\nwFfvGpAlDKLSXkgEQKN0IzpFOSSQPwQeoezoVCdFYWjb40paRljxuQ8C84sDZMMW\nnXyXTlny40WyUvWd09nhF+ArNBy4I3XF8JvHvt7evIag3jlR7Svi57rDUEKkUFql\nvSd+aX2sG+SdYXYOhYxxLp8rexGNVRiIN92o98iijC4+lrcpoaa8+G960WG1w1EF\nljxOUPSQb1BOOAnDZAjk\n-----END CERTIFICATE-----"
#private_key = ""
#public_key = ""
[[opensearch.config.certs_by_ip]]
ip = "172.31.12.199"
public_key = "-----BEGIN CERTIFICATE-----\nMIIDazCCAlOgAwIBAgIJAIkhwPJ4FTPzMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow\nGAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzERMA8GA1UEAwwIcHJvZ3Jlc3MwHhcN\nMjMwMzEwMDkzNjE1WhcNMjYwMzA5MDkzNjE1WjBkMQswCQYDVQQGEwJVUzETMBEG\nA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hl\nZiBTb2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZub2RlMTCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBALIg5194fVPkLl2tnXi8wyUMkeiLU/TfilWUkizl\nLIbpfUm2Fa7S7kDaEvMCwPj4SO7OB8NgHl/fN9WzK6SM5TG4S8j81KytU6oAbvq7\njTUooarqeYZiZ8QXYlCbuwByEtlgMJy8wX4G0o2RO+MG+M7smdzvCz4WVDJCdEh2\nFLsyZjOcs2aTOlCWxCxkkmo44pv7p6LHaQZTdWm0R46Wdwsbs0jwKzjZcK3HXJ8d\nZScp8hpXgOk9JM1REIfYLepuXg6af5ZTTgtFNXpbzQofGUaHZ6YxayehXfpdPLta\nC5lyvCgGLHk7lVb92dPYrIOUNap+31olsx/VFOB821DIJj8CAwEAAaMhMB8wHQYD\nVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IBAQDM\nYZfH69G1IjeQyp2kpoQwOuiXTrHwD3PJtQW2lFsSaFTEwvfjM/vt2KxGnrk10qil\nIOrjUc9KKDXK+KyIT2x4WLmO8y+pAhR415HOilf9dKyoHFsFQudnHTHzx6mamNui\nJ4w0oEv8S/ZmALG7mhWAknA3f6inIq/at8+Ab0L+6pZHRTQKLflEqyA4ZFYI5pZq\n8XXFElsAomkSMEhdX4UH358q6rP84gDId6BQlsj0x+zhCSPa7ZuQ0XK8bJlbPWgm\nqvxYioQBx6PpoWqJwuC5+GMCg30Wm24cqJ8TA/luRBrpgnmGFqpOCjNQh2D40tyf\nM8q7UUNL3q54l3RHhGR7\n-----END CERTIFICATE-----"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyIOdfeH1T5C5d\nrZ14vMMlDJHoi1P034pVlJIs5SyG6X1JthWu0u5A2hLzAsD4+EjuzgfDYB5f3zfV\nsyukjOUxuEvI/NSsrVOqAG76u401KKGq6nmGYmfEF2JQm7sAchLZYDCcvMF+BtKN\nkTvjBvjO7Jnc7ws+FlQyQnRIdhS7MmYznLNmkzpQlsQsZJJqOOKb+6eix2kGU3Vp\ntEeOlncLG7NI8Cs42XCtx1yfHWUnKfIaV4DpPSTNURCH2C3qbl4Omn+WU04LRTV6\nW80KHxlGh2emMWsnoV36XTy7WguZcrwoBix5O5VW/dnT2KyDlDWqft9aJbMf1RTg\nfNtQyCY/AgMBAAECggEASi9F7Q7jMzMO1FjgAk6q/x0TD0QnfQ40MJwlnKj9OFq5\noR9CPIMAUuX/ilGVSJsu1LXdqdK4E7mFKWzrOiartV9JwLT7Zcbx1xVDIw1FK+R2\nIBZy8jK9gH80pNmWsgLQMtPKqxw5gWEaA3d+93gJ2zPSiJ7Nkdf+zMe8Ygk7bRJI\nAYv3Uk2Zy6aEso+CJkzHhEhvRkwnju16Vo1iN+0A/5RlADJNeAYACW7A3JXW6Q8n\ng2ifW4Zix39lk3RxCcgaA/TwpS9jB8WF4Ba+Or/OdU+TPZ3fZP5atv1uAprTwPDX\njaiL+X1W9V5VFYE/+P8N9q9tAJ63c1H7VtOgPDPF0QKBgQDlvfZdx1Hp63yg7Ogi\nhRPmr+EpNToSPqO5u7tYfyy2dmsRoBULkHpPu2cAmSWntCLtZjW2hX7QGzSK8Uwn\nRi9XZxjNdtEpbWtP0T4HWny+abbIQFeI4RBS0ZRBUCpaOIBnrJNU4rCeTb+RV7hE\nGVE1pw8Mf6QB6krDhDW+6yFwSwKBgQDGfMc/cmAr0o5h0SBwENMkPleTixo32wRX\nfTPPZuk1f5LH6/sqqn8OMYLCmiLaLeHaHbk0IYvixnaEGSBKQ72hYCO6UcgJMwPh\n5Mz5ujuG9CtQ2A/5eNed1voe2oLnMxhBZmGzO70HGw1MyDo+VkYpSPZYYKcYrooM\ni8QIruwxXQKBgQCytkaDRJ1vvYNBG4in8aU9eetIxuLZdmid/m8JtEPv28YF++Tj\nDgxXIYxKZtdn0TSqPyvhQ48WC1OgEXwPwQTqlIQysA6cj0U+3aHGzpji9hD9TS/K\nhmjQQ79z3wxTCki4XQJusbh6LDissvPf5WHKvp1yN4g5BSwLUzkLvpRQaQKBgQCg\nQpFRzhSObYRewE6TjVIdemSVkYPKw4De7w1NEYeMlYO6/fMfAOhzWlB8tZ0cUl2A\nEe2+hLOAl8OLZwomTEmpKYnPX0bG/rTMyEMkA1Ua4ryymrFTOVnGbJQpIz78U8nq\nzDJoV/yI5zO24hf8ywX9QZb9xpREHnECLjtK04mLVQKBgFb3i9zF0eLiwab9oLu2\neAuFVDi/ZZWJapUds0Hk/bYZYKnu/8IE3tJgJqVoNxT0E+ESiCq70nLWFQ4fpMfI\nYR4B1waxHU7BiWT7G6iUKwlDIYuaaPQRg3fIRzaZpkUw/ZYzsCAq0+zxYhmO0iP4\nPYzqEzbQtGFTM1DpGRleagzJ\n-----END PRIVATE KEY-----"

[[opensearch.config.certs_by_ip]]
ip = "172.31.11.123"
public_key = "-----BEGIN CERTIFICATE-----\nMIIDazCCAlOgAwIBAgIJAIkhwPJ4FTP0MA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow\nGAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzERMA8GA1UEAwwIcHJvZ3Jlc3MwHhcN\nMjMwMzEwMDkzNjE1WhcNMjYwMzA5MDkzNjE1WjBkMQswCQYDVQQGEwJVUzETMBEG\nA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hl\nZiBTb2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZub2RlMjCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBALKorpQNgrkUz3JvV0mCWWOChpbPhTwqvVUr9B96\nPHcXUHihJg/xS5rnWxs18wc22CQ84hL2EL0RC6tmcddrm0LpfE1WWJFygnG7hMmi\nHSGLOYs3MWkYrvJPpg+ctZptAqGlI+PnEiHwTTctzvj5dG9hdHL4GdANPlS0UO8m\n893oFiBNqWTXlMqq4/IHEMC5j9KUsaTAQPP72LL1epOujzBLdVjLEEfcNJa8IGc+\nSsyjbjaqyCWnkxCO19hxfZTxJAVW5ar03HOHWR8rYsd39FcHdTaCn32QtRvaPWgF\n3wnQarNljyhwjHg90WYwY2C2lB0ej3dUqQjeIsFm6GlLFqECAwEAAaMhMB8wHQYD\nVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IBAQAN\nSMkqNlfw1kMdZcvHM9s6WpAQkbnLd3pGRGlOdDPQzfJh1lLOBdUIUSKZtC6YE0uT\n2Ti2WG+0M/8JZgOrP2gPuwrRK/QL4wqt+BELmACghVwaeqzu6TjxLM6mP1IC40hC\nHtyMID2XPcGgrJSbzp53sbPpeKY/LqaNwfJFq/WNFheDifKxHNEPVIFgC65zL8wt\nlxUxNjTBRUAIrhRoRqL78uPdMH3sjQYN63dHV8lZ0Tipv/PeAEpjJ597Bf907PKb\nWzikRFevOCIsp5+aJIJq4A9KgmE5hr4LkfHpw4BeXbBs9nfrOsztVWI+O5tHFwiR\nyzeNCKT7PFZMILGGnBCs\n-----END CERTIFICATE-----"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyqK6UDYK5FM9y\nb1dJglljgoaWz4U8Kr1VK/Qfejx3F1B4oSYP8Uua51sbNfMHNtgkPOIS9hC9EQur\nZnHXa5tC6XxNVliRcoJxu4TJoh0hizmLNzFpGK7yT6YPnLWabQKhpSPj5xIh8E03\nLc74+XRvYXRy+BnQDT5UtFDvJvPd6BYgTalk15TKquPyBxDAuY/SlLGkwEDz+9iy\n9XqTro8wS3VYyxBH3DSWvCBnPkrMo242qsglp5MQjtfYcX2U8SQFVuWq9Nxzh1kf\nK2LHd/RXB3U2gp99kLUb2j1oBd8J0GqzZY8ocIx4PdFmMGNgtpQdHo93VKkI3iLB\nZuhpSxahAgMBAAECggEBAKadd4ptey8eQETpn07XuIN8FAaLbCbrePz4a8f7WG58\nGLkXGIcfsjG5d5bN3mMo+7P376JdRsj8H5TuilarbPWfCCSb1Sd30j088x6UCHTj\nAXxascLgmS8zppvCuv5UkXKsrub49UkfcPN3ziEVi0fgbBhYVsJXx3x5WU1fV2jn\nW612iLsts6T8+76itxiz9Xs0Xx3StPQisdsi+3eHuRlXpegJdqEmh+81VkwUkqUx\nI8taLaqTikKtjOILFH2eiOx8wMVePX/RoF02MoHVoP8+2vo6UHiGkG/9QLif81Ji\n5wbXGEMA4zYIhziifjw1E/EdFTLbMpi6kHV6OdyjD0ECgYEA534GGo2x9IR+OC3N\n8PqXcxeh2okoUp4Tm/jEDZpmtUrVzK+5kfQBUBfiMl/0au+eFYS2PeONNd7T+uQT\nnV0WO61nKXZIPhyP7JLwyPL447OfzsLUuGwvfEL2VSeCRXwD1kjq0s9M0yCiW+nF\nXo/aLa+tQKyFoeQEqAW6Y8oyVPkCgYEAxZLAbiqvkGv4Jt+vf3OFsbmFWrpceKV3\nSe88z9NZLkUsWHjRoc1QX2a3Ob0sN2v7L2K2UJy60uqvPeEajRF/CsK+7/8mFTTS\nJ02nX+GfaOEHBx1pI/QNKHNvvkIT6H1qsh9JPCpj+KTkK8zjwRriRZamQycJ9o2r\n6D8rqg0JwOkCgYEAuU/SNQl/Dn3NyM0qEiGYgYLGh3nKtLBkhDRVRYp3c+NvWUbG\np8cMEgC8i5TyxXQCObmeZda2IQy65xoTdaKh/K3oanGMjWQx9rD+Xe7bPPR7Fnoy\n7Vt1e+Ti6vIQv+zx6WU/zfgyyMRUFH4ECJnhjzcV2zMAWsN80sCbH+0p84kCgYBQ\n2QaJjkodbTE0pyAnpVw2J9acE9q3O+6egJl/6dp6hq/o3DfcYCndgCjGJdUsMLGu\n6FP2lMwWdxaS2cSFqX01KA/+IYix8NV2Y95z693RixPXI3/cyIeB4Ar/7gY7gubg\nUNElH6udGcyM5+DjKl8hXs5WeGkpTTvlY8Q4Z/Fv0QKBgEWi+IwbmGoUP5ypYCIN\nmQDyoHqvkCoM6o1Yq/W16mElILc+WVkHcowqnB85A9gez1dDXQEQN9FMP4fh+HAn\nlmiD/1JlFbjJfG98Io6/lrbnDO1y7f/KjpQdxASH/YeyOAsLwWJtmlCy8DUNm//b\nBM29VWnuegZsXF+Y12QVnKYs\n-----END PRIVATE KEY-----"

[[opensearch.config.certs_by_ip]]
ip = "172.31.13.185"
public_key = "-----BEGIN CERTIFICATE-----\nMIIDazCCAlOgAwIBAgIJAIkhwPJ4FTP1MA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow\nGAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzERMA8GA1UEAwwIcHJvZ3Jlc3MwHhcN\nMjMwMzEwMDkzNjE1WhcNMjYwMzA5MDkzNjE1WjBkMQswCQYDVQQGEwJVUzETMBEG\nA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hl\nZiBTb2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZub2RlMzCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBANB9wUrQNHBgzCvyoI7DP0+S3QlEiV+Bp5xU2O8T\nz+qExtS5FUHGj4HkGN0ac601SQd8IPYKT+Wh/w2et3Sj9U03S2m2xTfuoPG8AU/Y\n9G/V6Q8ifjMfsQBncN9tA4ylsuQfIBciQZRCA6N8DJFZYd+g+waN7ZW/L9bxvTA7\ndEoxq+nkFs9WnrHPMCn3isDW17EvG6sAPzZm/rXu6hXAy2EtjciPPvrDPFwxvq/z\n0uJWKOdGWiGPnmmTr3uqBCrM2GMMQg2bvxoKzzYjn729QtiyNZhonXCyjkf9svmT\nnOUCZJ1CHtsHGcokJy6nh4/AgabJTdaErrsw32lKgYSIBJUCAwEAAaMhMB8wHQYD\nVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IBAQBb\nRyR9Q6ueOtDFQoCPTONVRBuefAB+gUWt4+7tSVFkPfA2+9Fil4SsMho3l5ul39cm\nq7M1DWv6moTMQQ8TVSk6WyDM40rnaM8ubCvSiS9u9GMkKhB5Ni75DWU08dYzGfBq\n4z76JQG+MqQBMMgwjeOW+uSA9oCgvipkfJGnwJaAlbNPxNf72CV6nVVYebGb27pH\nTc3w3MGLMowcJc/aeM1RbYeAY+cGsjKu4tLGGURvIg2nJ97mCi6XTiCvKnK66vW3\nNEN7RZ3LvPIH0h7w1cdXMBDwTr9nCLtg+QbVQW+2UknGAcjSpfE+K4dO1X037HkR\nLQwwuO28ZCPLzKGBcBaO\n-----END CERTIFICATE-----"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQfcFK0DRwYMwr\n8qCOwz9Pkt0JRIlfgaecVNjvE8/qhMbUuRVBxo+B5BjdGnOtNUkHfCD2Ck/lof8N\nnrd0o/VNN0tptsU37qDxvAFP2PRv1ekPIn4zH7EAZ3DfbQOMpbLkHyAXIkGUQgOj\nfAyRWWHfoPsGje2Vvy/W8b0wO3RKMavp5BbPVp6xzzAp94rA1texLxurAD82Zv61\n7uoVwMthLY3Ijz76wzxcMb6v89LiVijnRlohj55pk697qgQqzNhjDEINm78aCs82\nI5+9vULYsjWYaJ1wso5H/bL5k5zlAmSdQh7bBxnKJCcup4ePwIGmyU3WhK67MN9p\nSoGEiASVAgMBAAECggEAXT/htBRrX9frebyLE09AgdauBfchehYDYWiRnly+IaZB\nR+OAHmswxGfAtyOdmVq7zx01oNX75jkOWokihIjQrjiNAjs8+kdAtN3huFTQ/zQt\niRdkWnlSMVwSn9uiOsXhvSYutCoeKrFb70MMW/YeUGcv3z6bhN5+ByUX+PqeiI/f\nrLJmFfs4489tT1O+d04dOZsiTYAi8W3O6JF7iXKL3Ca80Qv4rznaWEBAXY3UUHKC\nmx8n8z9cbEL/4tHK18zAAwFXDyB3PHrL59HDJSwHCB1mqL1vJ4A0OY+bPRul3qSb\n4v/2CmgHCrjlCLnvqPZGUTqZDdWI5Qt3Urox63eOAQKBgQD3i/kNq2bInyACGeHc\nkZp9RrnVeoIUicAQyO/1iSd9kA4bwwZ9/AHXM4TBQEA6jMrLsfQYJ/2/P4EVPwqs\nP4rutz+GzHgBETJB0QIYWQtAejupRuWlwjgmdnbKImCovnf0FpGUMpcdERDc6UNo\nqjQlxwbdE5RlM8NazFKs3hmqbwKBgQDXnFzl2mxaRgkFjLjGH3momgknF5kh23Uu\nAoMcjv26ryTRHX4Mft9+tmrRk+jRpEwJPxZsS2R1s0zoKOebv3QCr7NZ2l3RWFbN\nX0hHwIKr1cK3Tde4MolBTiPLGuls7xzuyGcZqLvaLwPIBWZsSUT1hTOJ1zaERCz9\npFxmxECTOwKBgBUgO/P/sbjjY57qSI1DW9TfKVLfrqREEUEddOUWfGlJ1vpljXNJ\nA3szKVw4uIKGq3Pwzu0U1KHysHh4tdd3YMr4lpJRdthYeFqHlM8xIjWxeM/8ffLE\nfXhC2eZsQqWEA8av+mKUYrMXVsIToi4XgHXM43gQiLSOU1i3YULhfX0/AoGABfVB\nL+zYP6pdx3R7CqaGAx22kQj650+cLlhNbTWaV1VNrCWnfQrofCToUMBIl7p1i2/d\n28I9lW8N+gBfXhNtTkGysBHzs7xAMc6nPaxZMAxpJA2Xn3RuDIrvPEaTGrqEzyhk\niPX7suzHqvhTOzzPFgXHRdDXpdIIeD3Ze9GCg08CgYAsHp0y3t6a5fzXgK2NkhBp\nYRqOWxpQlYGbTYMOAi8e9j7KniiDMnxGLm3shK4Ea7+bPfafQ/xXOp0OpXeUiSDn\ntBvK0iToc6ZQC1Lpk7EJ7gO6Ev+CfkqtmX7t4nXwrt3QsgyDlkGcdxDcTgMvYBuW\nePBOn57PCV7f78kMKfG6fA==\n-----END PRIVATE KEY-----"

## === ===

[postgresql.config]
## === INPUT NEEDED ===

# No. of Postgresql DB Backend Machine or VM eg.: instance_count = "3"
instance_count = "3"

# Set enable_custom_certs = true to provide custom certificates during deployment
enable_custom_certs = false
# Add postgresql load balancer root-ca and keys
# root_ca = ""
# private_key = ""
# public_key = ""
# [[postgresql.config.certs_by_ip]]
# ip = ""
# private_key = ""
# public_key = ""

## === ===

[existing_infra.config]
## === INPUT NEEDED ===

# provide comma-seperated IP addresses of nodes, like ["192.0.0.1", "192.0.0.2", "192.0.0.2"]
# No. of IP address should be the same as the No. of instance_count count mentioned above in
# automate.config, chef_server.config, opensearch.config and postgresql.config
automate_private_ips = ["172.31.8.28", "172.31.8.30"]
chef_server_private_ips = ["172.31.14.88", "172.31.14.90"]
opensearch_private_ips = ["172.31.12.199","172.31.11.123","172.31.13.185"]
postgresql_private_ips = ["172.31.4.48","172.31.5.243","172.31.11.194"]
## === ===

# ============== External Datbase Services ======================

## === INPUT NEEDED ===
# In case you are trying to deploy with AWS Managed Services set type as "aws"
# If you are trying external managed database set type as "self-managed"

[external.database]

# eg type = "aws" or "self-managed"
type = ""

[external.database.postgre_sql]

# eg: instance_url = "managed-rds-db.c5gkx.ap-northeast-1.rds.amazonaws.com:5432"
instance_url = ""

# eg: username = "postgres"
superuser_username = ""

# eg: password = "Progress123"
superuser_password = ""

# eg: dbuser_username = "postgres"
dbuser_username = ""

# eg: dbuser_password = "Progress123"
dbuser_password = ""

# In case of AWS managed RDS leave it blank
postgresql_root_cert = "<cert_content>"

[external.database.open_search]

# eg: managed_opensearch_domain_name = "managed-services-os"
opensearch_domain_name = ""

# eg: opensearch_domain_url = "search-managed-services-os.us-east-1.es.amazonaws.com"
opensearch_domain_url = ""

# eg: opensearch_username = "admin"
opensearch_username = ""

# eg: opensearch_user_password = "Progress@123"
opensearch_user_password = ""

# In case of AWS managed opensearch leave it blank
opensearch_root_cert = "<cert_content>"

[external.database.open_search.aws]

# eg: aws_os_snapshot_role_arn = "arn:aws:iam::1127583934333:role/managed-services"
aws_os_snapshot_role_arn = ""

# eg: os_snapshot_user_access_key_id = "AKIA..........PQS7Q7A"
os_snapshot_user_access_key_id = ""

# eg: os_snapshot_user_access_key_secret = "skP4Mqihj....................anAXAX"
os_snapshot_user_access_key_secret = ""