required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/golang/mock/mockgen",
  "github.com/lyft/protoc-gen-validate"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    unused-packages = false
    non-go = false

  # proto files using protoc-gen-validate for validation will import
  # vendor/github.com/lyft/protoc-gen-validate/validate/validate.proto (non-go)
  [[prune.project]]
    name = "github.com/lyft/protoc-gen-validate"
    non-go = false

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

# "github.com/grpc-ecosystem/go-grpc-middleware" depends on logrus@^1.0.3
[[override]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[override]]
  name = "github.com/lyft/protoc-gen-validate"
  branch = "master"

# github.com/Azure/go-autorest pins v3.1.0
[[override]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

# github.com/grpc-ecosystem/grpc-gateway pins some refs for the following
[[override]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[override]]
  branch = "master"
  name = "google.golang.org/genproto"

# end of grpc-gateway-related overrides

# Note: currently, 0.3.4 is the only version that works with pb 1.1.0+
# see https://github.com/lyft/protoc-gen-star/issues/24.
[[constraint]]
  name = "github.com/lyft/protoc-gen-star"
  version = "=0.4.5"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.9.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "^6.2.16"

[[constraint]]
  name = "github.com/robfig/cron"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.0"

[[constraint]]
  name = "github.com/dexidp/dex"
  version = "2.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-oidc"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "go.uber.org/zap"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

# Converge Service
[[constraint]]
  name = "github.com/schollz/closestmatch"
  revision = "19d3b334fdfcb0151de79319f1fe1dfc41de758c"

# Gateway
[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  version = "1.2.0"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  branch = "master"
  name = "github.com/golang/mock"

# AuthN Service
[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/burntsushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/peterbourgon/mergemap"

[[constraint]]
  branch = "master"
  name = "github.com/briandowns/spinner"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.20"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/color"

[[constraint]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[constraint]]
  name = "github.com/mattes/migrate"
  branch = "master"

# Compliance Service
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.48"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  version = "2.1.0"

[[constraint]]
  name = "github.com/teambition/rrule-go"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "19.1.0"

# authz-service
# Note 2018/12/11 (sr): We're explicitly pinning this version. Bumping OPA
# should be an explicit endeavour, and be accompanied by re-running the
# benchmarks to assess the impact. (Version pins without "=" can be updated
# more easily.)
[[constraint]]
  name = "github.com/open-policy-agent/opa"
  version = "=0.10.7"

[[constraint]]
  name = "github.com/chef/toml"
  branch = "master"

# automate-grpc
[[constraint]]
  name = "github.com/jhump/protoreflect"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-opentracing"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.2"

[[constraint]]
  name = "github.com/buger/goterm"
  branch = "master"

[[constraint]]
  name = "github.com/buger/jsonparser"
  branch = "master"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  name = "go.uber.org/multierr"
  branch = "master"

# event-service
[[constraint]]
  name = "github.com/nats-io/nats-streaming-server"
  branch = "master"

[[override]]
  name = "github.com/nats-io/gnatsd"
  # patch to make nats gateway feature work with our mTLS setup, specifically
  # where we set CN=service-name
  # https://github.com/nats-io/gnatsd/pull/922
  # when that is merged we should go back to mainline
  # branch = "master"
  source = "https://github.com/danielsdeleo/gnatsd.git"
  branch = "dan/allow-explicit-server-name-in-gateway"

# applications-service
[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  branch = "master"

# for testing
[[constraint]]
  name = "github.com/leanovate/gopter"
  version = "0.2.4"
