// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interservice/infra_proxy/response/environments.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Environments struct {
	// Environments list.
	Environments         []*EnvironmentListItem `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty" toml:"environments,omitempty" mapstructure:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                 `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                  `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Environments) Reset()         { *m = Environments{} }
func (m *Environments) String() string { return proto.CompactTextString(m) }
func (*Environments) ProtoMessage()    {}
func (*Environments) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa686a0ac5a989, []int{0}
}

func (m *Environments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environments.Unmarshal(m, b)
}
func (m *Environments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environments.Marshal(b, m, deterministic)
}
func (m *Environments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environments.Merge(m, src)
}
func (m *Environments) XXX_Size() int {
	return xxx_messageInfo_Environments.Size(m)
}
func (m *Environments) XXX_DiscardUnknown() {
	xxx_messageInfo_Environments.DiscardUnknown(m)
}

var xxx_messageInfo_Environments proto.InternalMessageInfo

func (m *Environments) GetEnvironments() []*EnvironmentListItem {
	if m != nil {
		return m.Environments
	}
	return nil
}

type EnvironmentListItem struct {
	// Environment name.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *EnvironmentListItem) Reset()         { *m = EnvironmentListItem{} }
func (m *EnvironmentListItem) String() string { return proto.CompactTextString(m) }
func (*EnvironmentListItem) ProtoMessage()    {}
func (*EnvironmentListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa686a0ac5a989, []int{1}
}

func (m *EnvironmentListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentListItem.Unmarshal(m, b)
}
func (m *EnvironmentListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentListItem.Marshal(b, m, deterministic)
}
func (m *EnvironmentListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentListItem.Merge(m, src)
}
func (m *EnvironmentListItem) XXX_Size() int {
	return xxx_messageInfo_EnvironmentListItem.Size(m)
}
func (m *EnvironmentListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentListItem.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentListItem proto.InternalMessageInfo

func (m *EnvironmentListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Environment struct {
	// Environment name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	// Chef object type.
	ChefType string `protobuf:"bytes,2,opt,name=chef_type,json=chefType,proto3" json:"chef_type,omitempty" toml:"chef_type,omitempty" mapstructure:"chef_type,omitempty"`
	// Environment description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty" mapstructure:"description,omitempty"`
	// Environment JSON class.
	JsonClass string `protobuf:"bytes,4,opt,name=json_class,json=jsonClass,proto3" json:"json_class,omitempty" toml:"json_class,omitempty" mapstructure:"json_class,omitempty"`
	// Environment versined cookbooks constraints.
	CookbookVersions map[string]string `protobuf:"bytes,5,rep,name=cookbook_versions,json=cookbookVersions,proto3" json:"cookbook_versions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" toml:"cookbook_versions,omitempty" mapstructure:"cookbook_versions,omitempty"`
	// Stringified json of the default attributes.
	DefaultAttributes string `protobuf:"bytes,6,opt,name=default_attributes,json=defaultAttributes,proto3" json:"default_attributes,omitempty" toml:"default_attributes,omitempty" mapstructure:"default_attributes,omitempty"`
	// Stringified json of the override attributes.
	OverrideAttributes   string   `protobuf:"bytes,7,opt,name=override_attributes,json=overrideAttributes,proto3" json:"override_attributes,omitempty" toml:"override_attributes,omitempty" mapstructure:"override_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa686a0ac5a989, []int{2}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetChefType() string {
	if m != nil {
		return m.ChefType
	}
	return ""
}

func (m *Environment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Environment) GetJsonClass() string {
	if m != nil {
		return m.JsonClass
	}
	return ""
}

func (m *Environment) GetCookbookVersions() map[string]string {
	if m != nil {
		return m.CookbookVersions
	}
	return nil
}

func (m *Environment) GetDefaultAttributes() string {
	if m != nil {
		return m.DefaultAttributes
	}
	return ""
}

func (m *Environment) GetOverrideAttributes() string {
	if m != nil {
		return m.OverrideAttributes
	}
	return ""
}

func init() {
	proto.RegisterType((*Environments)(nil), "chef.automate.domain.infra_proxy.response.Environments")
	proto.RegisterType((*EnvironmentListItem)(nil), "chef.automate.domain.infra_proxy.response.EnvironmentListItem")
	proto.RegisterType((*Environment)(nil), "chef.automate.domain.infra_proxy.response.Environment")
	proto.RegisterMapType((map[string]string)(nil), "chef.automate.domain.infra_proxy.response.Environment.CookbookVersionsEntry")
}

func init() {
	proto.RegisterFile("interservice/infra_proxy/response/environments.proto", fileDescriptor_40fa686a0ac5a989)
}

var fileDescriptor_40fa686a0ac5a989 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0xeb, 0xd3, 0x40,
	0x10, 0xc5, 0xc9, 0x3f, 0x6d, 0xb5, 0xd3, 0x1e, 0xda, 0xad, 0x42, 0x50, 0x84, 0xd2, 0x53, 0x7b,
	0x70, 0x17, 0xd4, 0x83, 0x78, 0x28, 0x6a, 0xe9, 0x41, 0xe8, 0xa9, 0x88, 0x07, 0x2f, 0x61, 0x93,
	0x4c, 0xed, 0xda, 0x66, 0x27, 0xec, 0x6e, 0x82, 0xf9, 0x34, 0x7e, 0x55, 0xc9, 0x9a, 0x68, 0x94,
	0x82, 0xf2, 0xbf, 0xed, 0xbe, 0xf7, 0xe6, 0xc7, 0xf0, 0x18, 0x78, 0xa5, 0xb4, 0x43, 0x63, 0xd1,
	0x54, 0x2a, 0x45, 0xa1, 0xf4, 0xc9, 0xc8, 0xb8, 0x30, 0xf4, 0xad, 0x16, 0x06, 0x6d, 0x41, 0xda,
	0xa2, 0x40, 0x5d, 0x29, 0x43, 0x3a, 0x47, 0xed, 0x2c, 0x2f, 0x0c, 0x39, 0x62, 0x9b, 0xf4, 0x8c,
	0x27, 0x2e, 0x4b, 0x47, 0xb9, 0x74, 0xc8, 0x33, 0xca, 0xa5, 0xd2, 0xbc, 0x37, 0xcd, 0xbb, 0xe9,
	0x95, 0x81, 0xe9, 0xbe, 0x07, 0x60, 0x09, 0x4c, 0xfb, 0xc0, 0x28, 0x58, 0x86, 0xeb, 0xc9, 0x8b,
	0x2d, 0xff, 0x6f, 0x22, 0xef, 0xe1, 0x0e, 0xca, 0xba, 0x0f, 0x0e, 0xf3, 0xe3, 0x1f, 0xcc, 0xd5,
	0x06, 0x16, 0x37, 0x42, 0x8c, 0xc1, 0x40, 0xcb, 0x1c, 0xa3, 0x60, 0x19, 0xac, 0xc7, 0x47, 0xff,
	0x5e, 0x7d, 0x0f, 0x61, 0xd2, 0xcb, 0xde, 0xca, 0xb0, 0xa7, 0x30, 0x6e, 0xb6, 0x8b, 0x5d, 0x5d,
	0x60, 0x74, 0xe7, 0x8d, 0x87, 0x8d, 0xf0, 0xb1, 0x2e, 0x90, 0x2d, 0x61, 0x92, 0xa1, 0x4d, 0x8d,
	0x2a, 0x9c, 0x22, 0x1d, 0x85, 0xde, 0xee, 0x4b, 0xec, 0x19, 0xc0, 0x57, 0x4b, 0x3a, 0x4e, 0xaf,
	0xd2, 0xda, 0x68, 0xe0, 0x03, 0xe3, 0x46, 0xd9, 0x35, 0x02, 0xab, 0x61, 0x9e, 0x12, 0x5d, 0x12,
	0xa2, 0x4b, 0x5c, 0xa1, 0xb1, 0x8a, 0xb4, 0x8d, 0x86, 0xbe, 0x95, 0xc3, 0xfd, 0x5a, 0xe1, 0xbb,
	0x96, 0xf7, 0xa9, 0xc5, 0xed, 0xb5, 0x33, 0xf5, 0x71, 0x96, 0xfe, 0x25, 0xb3, 0xe7, 0xc0, 0x32,
	0x3c, 0xc9, 0xf2, 0xea, 0x62, 0xe9, 0x9c, 0x51, 0x49, 0xe9, 0xd0, 0x46, 0x23, 0xbf, 0xe1, 0xbc,
	0x75, 0xde, 0xfd, 0x32, 0x98, 0x80, 0x05, 0x55, 0x68, 0x8c, 0xca, 0xb0, 0x9f, 0x7f, 0xe0, 0xf3,
	0xac, 0xb3, 0x7e, 0x0f, 0x3c, 0xd9, 0xc1, 0xe3, 0x9b, 0xab, 0xb0, 0x19, 0x84, 0x17, 0xac, 0xdb,
	0x92, 0x9b, 0x27, 0x7b, 0x04, 0xc3, 0x4a, 0x5e, 0xcb, 0xae, 0xdf, 0x9f, 0x9f, 0x37, 0x77, 0xaf,
	0x83, 0xf7, 0x6f, 0x3f, 0x6f, 0xbf, 0x28, 0x77, 0x2e, 0x13, 0x9e, 0x52, 0x2e, 0x9a, 0x42, 0x44,
	0x57, 0x88, 0x90, 0x85, 0x12, 0xff, 0x3c, 0xe0, 0x64, 0xe4, 0x8f, 0xf6, 0xe5, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x01, 0xa2, 0xe2, 0x7f, 0xec, 0x02, 0x00, 0x00,
}
