// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/interservice/infra_proxy/response/orgs.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrg struct {
	Org                  *Org     `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty" toml:"org,omitempty" mapstructure:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *CreateOrg) Reset()         { *m = CreateOrg{} }
func (m *CreateOrg) String() string { return proto.CompactTextString(m) }
func (*CreateOrg) ProtoMessage()    {}
func (*CreateOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{0}
}

func (m *CreateOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrg.Unmarshal(m, b)
}
func (m *CreateOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrg.Marshal(b, m, deterministic)
}
func (m *CreateOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrg.Merge(m, src)
}
func (m *CreateOrg) XXX_Size() int {
	return xxx_messageInfo_CreateOrg.Size(m)
}
func (m *CreateOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrg.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrg proto.InternalMessageInfo

func (m *CreateOrg) GetOrg() *Org {
	if m != nil {
		return m.Org
	}
	return nil
}

type DeleteOrg struct {
	Org                  *Org     `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty" toml:"org,omitempty" mapstructure:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *DeleteOrg) Reset()         { *m = DeleteOrg{} }
func (m *DeleteOrg) String() string { return proto.CompactTextString(m) }
func (*DeleteOrg) ProtoMessage()    {}
func (*DeleteOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{1}
}

func (m *DeleteOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrg.Unmarshal(m, b)
}
func (m *DeleteOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrg.Marshal(b, m, deterministic)
}
func (m *DeleteOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrg.Merge(m, src)
}
func (m *DeleteOrg) XXX_Size() int {
	return xxx_messageInfo_DeleteOrg.Size(m)
}
func (m *DeleteOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrg.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrg proto.InternalMessageInfo

func (m *DeleteOrg) GetOrg() *Org {
	if m != nil {
		return m.Org
	}
	return nil
}

type UpdateOrg struct {
	Org                  *Org     `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty" toml:"org,omitempty" mapstructure:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpdateOrg) Reset()         { *m = UpdateOrg{} }
func (m *UpdateOrg) String() string { return proto.CompactTextString(m) }
func (*UpdateOrg) ProtoMessage()    {}
func (*UpdateOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{2}
}

func (m *UpdateOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrg.Unmarshal(m, b)
}
func (m *UpdateOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrg.Marshal(b, m, deterministic)
}
func (m *UpdateOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrg.Merge(m, src)
}
func (m *UpdateOrg) XXX_Size() int {
	return xxx_messageInfo_UpdateOrg.Size(m)
}
func (m *UpdateOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrg proto.InternalMessageInfo

func (m *UpdateOrg) GetOrg() *Org {
	if m != nil {
		return m.Org
	}
	return nil
}

type GetOrgs struct {
	Orgs                 []*Org   `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty" toml:"orgs,omitempty" mapstructure:"orgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetOrgs) Reset()         { *m = GetOrgs{} }
func (m *GetOrgs) String() string { return proto.CompactTextString(m) }
func (*GetOrgs) ProtoMessage()    {}
func (*GetOrgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{3}
}

func (m *GetOrgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrgs.Unmarshal(m, b)
}
func (m *GetOrgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrgs.Marshal(b, m, deterministic)
}
func (m *GetOrgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgs.Merge(m, src)
}
func (m *GetOrgs) XXX_Size() int {
	return xxx_messageInfo_GetOrgs.Size(m)
}
func (m *GetOrgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgs proto.InternalMessageInfo

func (m *GetOrgs) GetOrgs() []*Org {
	if m != nil {
		return m.Orgs
	}
	return nil
}

type GetOrg struct {
	Org                  *Org     `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty" toml:"org,omitempty" mapstructure:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetOrg) Reset()         { *m = GetOrg{} }
func (m *GetOrg) String() string { return proto.CompactTextString(m) }
func (*GetOrg) ProtoMessage()    {}
func (*GetOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{4}
}

func (m *GetOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrg.Unmarshal(m, b)
}
func (m *GetOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrg.Marshal(b, m, deterministic)
}
func (m *GetOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrg.Merge(m, src)
}
func (m *GetOrg) XXX_Size() int {
	return xxx_messageInfo_GetOrg.Size(m)
}
func (m *GetOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrg.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrg proto.InternalMessageInfo

func (m *GetOrg) GetOrg() *Org {
	if m != nil {
		return m.Org
	}
	return nil
}

type Org struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	AdminUser            string   `protobuf:"bytes,3,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty" toml:"admin_user,omitempty" mapstructure:"admin_user,omitempty"`
	AdminKey             string   `protobuf:"bytes,4,opt,name=admin_key,json=adminKey,proto3" json:"admin_key,omitempty" toml:"admin_key,omitempty" mapstructure:"admin_key,omitempty"`
	ServerId             string   `protobuf:"bytes,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty" toml:"server_id,omitempty" mapstructure:"server_id,omitempty"`
	Projects             []string `protobuf:"bytes,6,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Org) Reset()         { *m = Org{} }
func (m *Org) String() string { return proto.CompactTextString(m) }
func (*Org) ProtoMessage()    {}
func (*Org) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dc8f1d5db2fd376, []int{5}
}

func (m *Org) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Org.Unmarshal(m, b)
}
func (m *Org) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Org.Marshal(b, m, deterministic)
}
func (m *Org) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Org.Merge(m, src)
}
func (m *Org) XXX_Size() int {
	return xxx_messageInfo_Org.Size(m)
}
func (m *Org) XXX_DiscardUnknown() {
	xxx_messageInfo_Org.DiscardUnknown(m)
}

var xxx_messageInfo_Org proto.InternalMessageInfo

func (m *Org) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Org) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Org) GetAdminUser() string {
	if m != nil {
		return m.AdminUser
	}
	return ""
}

func (m *Org) GetAdminKey() string {
	if m != nil {
		return m.AdminKey
	}
	return ""
}

func (m *Org) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *Org) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOrg)(nil), "chef.automate.domain.infra_proxy.response.CreateOrg")
	proto.RegisterType((*DeleteOrg)(nil), "chef.automate.domain.infra_proxy.response.DeleteOrg")
	proto.RegisterType((*UpdateOrg)(nil), "chef.automate.domain.infra_proxy.response.UpdateOrg")
	proto.RegisterType((*GetOrgs)(nil), "chef.automate.domain.infra_proxy.response.GetOrgs")
	proto.RegisterType((*GetOrg)(nil), "chef.automate.domain.infra_proxy.response.GetOrg")
	proto.RegisterType((*Org)(nil), "chef.automate.domain.infra_proxy.response.Org")
}

func init() {
	proto.RegisterFile("api/interservice/infra_proxy/response/orgs.proto", fileDescriptor_0dc8f1d5db2fd376)
}

var fileDescriptor_0dc8f1d5db2fd376 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x6e, 0xad, 0xed, 0x08, 0x1e, 0x72, 0x0a, 0x8a, 0x50, 0x7a, 0xd2, 0x4b, 0x22,
	0x7a, 0x97, 0x52, 0x05, 0x51, 0x91, 0x42, 0xa1, 0x17, 0x2f, 0x4b, 0xba, 0x99, 0x6e, 0xa3, 0xee,
	0x26, 0x4c, 0x52, 0xb1, 0x7f, 0xc6, 0xdf, 0x2a, 0xc9, 0x52, 0xf0, 0x58, 0x64, 0x6f, 0x99, 0xf7,
	0x78, 0x1f, 0x33, 0xe1, 0xc1, 0xb5, 0x72, 0x46, 0x9a, 0x26, 0x20, 0x79, 0xa4, 0x2f, 0x53, 0xa2,
	0x34, 0xcd, 0x9a, 0x54, 0xe1, 0xc8, 0x7e, 0xef, 0x24, 0xa1, 0x77, 0xb6, 0xf1, 0x28, 0x2d, 0x55,
	0x5e, 0x38, 0xb2, 0xc1, 0xb2, 0xab, 0x72, 0x83, 0x6b, 0xa1, 0xb6, 0xc1, 0xd6, 0x2a, 0xa0, 0xd0,
	0xb6, 0x56, 0xa6, 0x11, 0x7f, 0x52, 0x62, 0x9f, 0x9a, 0xbc, 0xc2, 0xe8, 0x9e, 0x50, 0x05, 0x9c,
	0x53, 0xc5, 0xa6, 0x90, 0x5b, 0xaa, 0x78, 0x36, 0xce, 0x2e, 0x4f, 0x6e, 0x84, 0x38, 0x98, 0x22,
	0xe6, 0x54, 0x2d, 0x62, 0x34, 0xe2, 0x1e, 0xf0, 0x13, 0x3b, 0xc4, 0x2d, 0x9d, 0xee, 0x70, 0xbb,
	0xe3, 0x47, 0x0c, 0x73, 0xaa, 0x3c, 0x9b, 0x41, 0x3f, 0x7e, 0x18, 0xcf, 0xc6, 0xf9, 0x3f, 0x68,
	0x29, 0x3b, 0x79, 0x86, 0x41, 0x8b, 0xeb, 0x60, 0xb5, 0x9f, 0x0c, 0xf2, 0x48, 0x3a, 0x85, 0x9e,
	0xd1, 0x09, 0x34, 0x5a, 0xf4, 0x8c, 0x66, 0x0c, 0xfa, 0x8d, 0xaa, 0x91, 0xf7, 0x92, 0x92, 0xde,
	0xec, 0x02, 0x40, 0xe9, 0xda, 0x34, 0xc5, 0xd6, 0x23, 0xf1, 0x3c, 0x39, 0xa3, 0xa4, 0x2c, 0x3d,
	0x12, 0x3b, 0x87, 0x76, 0x28, 0x3e, 0x70, 0xc7, 0xfb, 0xc9, 0x1d, 0x26, 0xe1, 0x05, 0x77, 0xd1,
	0x8c, 0x2d, 0x42, 0x2a, 0x8c, 0xe6, 0x47, 0xad, 0xd9, 0x0a, 0x4f, 0x9a, 0x9d, 0xc1, 0xd0, 0x91,
	0x7d, 0xc7, 0x32, 0x78, 0x3e, 0x18, 0xe7, 0xd1, 0xdb, 0xcf, 0xb3, 0xe9, 0xdb, 0x5d, 0x65, 0xc2,
	0x66, 0xbb, 0x12, 0xa5, 0xad, 0x65, 0xbc, 0x50, 0xee, 0x2f, 0x94, 0x07, 0x15, 0x74, 0x35, 0x48,
	0xe5, 0xbc, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x87, 0x8a, 0xef, 0x7f, 0xd0, 0x02, 0x00, 0x00,
}
