// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interservice/infra_proxy/response/roles.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Roles struct {
	// List of the roles item.
	Roles                []*RoleListItem `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" toml:"roles,omitempty" mapstructure:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte          `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32           `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Roles) Reset()         { *m = Roles{} }
func (m *Roles) String() string { return proto.CompactTextString(m) }
func (*Roles) ProtoMessage()    {}
func (*Roles) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd54a1c203a9a33, []int{0}
}

func (m *Roles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roles.Unmarshal(m, b)
}
func (m *Roles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roles.Marshal(b, m, deterministic)
}
func (m *Roles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roles.Merge(m, src)
}
func (m *Roles) XXX_Size() int {
	return xxx_messageInfo_Roles.Size(m)
}
func (m *Roles) XXX_DiscardUnknown() {
	xxx_messageInfo_Roles.DiscardUnknown(m)
}

var xxx_messageInfo_Roles proto.InternalMessageInfo

func (m *Roles) GetRoles() []*RoleListItem {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleListItem struct {
	// Name of the role.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	// Desscription of the role.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty" mapstructure:"description,omitempty"`
	// Environment for the role.
	Environments         []string `protobuf:"bytes,3,rep,name=environments,proto3" json:"environments,omitempty" toml:"environments,omitempty" mapstructure:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *RoleListItem) Reset()         { *m = RoleListItem{} }
func (m *RoleListItem) String() string { return proto.CompactTextString(m) }
func (*RoleListItem) ProtoMessage()    {}
func (*RoleListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd54a1c203a9a33, []int{1}
}

func (m *RoleListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListItem.Unmarshal(m, b)
}
func (m *RoleListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListItem.Marshal(b, m, deterministic)
}
func (m *RoleListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListItem.Merge(m, src)
}
func (m *RoleListItem) XXX_Size() int {
	return xxx_messageInfo_RoleListItem.Size(m)
}
func (m *RoleListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListItem.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListItem proto.InternalMessageInfo

func (m *RoleListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleListItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoleListItem) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

type Role struct {
	// Name of the role.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	// Type of the chef object.
	ChefType string `protobuf:"bytes,2,opt,name=chef_type,json=chefType,proto3" json:"chef_type,omitempty" toml:"chef_type,omitempty" mapstructure:"chef_type,omitempty"`
	// Descrption of the role.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty" mapstructure:"description,omitempty"`
	// Role default attributes JSON.
	DefaultAttributes string `protobuf:"bytes,4,opt,name=default_attributes,json=defaultAttributes,proto3" json:"default_attributes,omitempty" toml:"default_attributes,omitempty" mapstructure:"default_attributes,omitempty"`
	// Role override attributes JSON.
	OverrideAttributes string `protobuf:"bytes,5,opt,name=override_attributes,json=overrideAttributes,proto3" json:"override_attributes,omitempty" toml:"override_attributes,omitempty" mapstructure:"override_attributes,omitempty"`
	// Json class name.
	JsonClass string `protobuf:"bytes,6,opt,name=json_class,json=jsonClass,proto3" json:"json_class,omitempty" toml:"json_class,omitempty" mapstructure:"json_class,omitempty"`
	// Run list for the role.
	RunList []string `protobuf:"bytes,7,rep,name=run_list,json=runList,proto3" json:"run_list,omitempty" toml:"run_list,omitempty" mapstructure:"run_list,omitempty"`
	// List of expanded run list for the role.
	ExpandedRunList      []*ExpandedRunList `protobuf:"bytes,8,rep,name=expanded_run_list,json=expandedRunList,proto3" json:"expanded_run_list,omitempty" toml:"expanded_run_list,omitempty" mapstructure:"expanded_run_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte             `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32              `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd54a1c203a9a33, []int{2}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetChefType() string {
	if m != nil {
		return m.ChefType
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Role) GetDefaultAttributes() string {
	if m != nil {
		return m.DefaultAttributes
	}
	return ""
}

func (m *Role) GetOverrideAttributes() string {
	if m != nil {
		return m.OverrideAttributes
	}
	return ""
}

func (m *Role) GetJsonClass() string {
	if m != nil {
		return m.JsonClass
	}
	return ""
}

func (m *Role) GetRunList() []string {
	if m != nil {
		return m.RunList
	}
	return nil
}

func (m *Role) GetExpandedRunList() []*ExpandedRunList {
	if m != nil {
		return m.ExpandedRunList
	}
	return nil
}

type ExpandedRunList struct {
	// ID of the run list collection.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	// List of the run list.
	RunList              []*RunList `protobuf:"bytes,2,rep,name=run_list,json=runList,proto3" json:"run_list,omitempty" toml:"run_list,omitempty" mapstructure:"run_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte     `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32      `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ExpandedRunList) Reset()         { *m = ExpandedRunList{} }
func (m *ExpandedRunList) String() string { return proto.CompactTextString(m) }
func (*ExpandedRunList) ProtoMessage()    {}
func (*ExpandedRunList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd54a1c203a9a33, []int{3}
}

func (m *ExpandedRunList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandedRunList.Unmarshal(m, b)
}
func (m *ExpandedRunList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandedRunList.Marshal(b, m, deterministic)
}
func (m *ExpandedRunList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandedRunList.Merge(m, src)
}
func (m *ExpandedRunList) XXX_Size() int {
	return xxx_messageInfo_ExpandedRunList.Size(m)
}
func (m *ExpandedRunList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandedRunList.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandedRunList proto.InternalMessageInfo

func (m *ExpandedRunList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExpandedRunList) GetRunList() []*RunList {
	if m != nil {
		return m.RunList
	}
	return nil
}

type RunList struct {
	// Type of run list item (e.g. 'recipe').
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" mapstructure:"type,omitempty"`
	// Name of run list item.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	// Version of run list item.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty" mapstructure:"version,omitempty"`
	// Boolean denoting whether or not the run list item was skipped.
	Skipped bool `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty" toml:"skipped,omitempty" mapstructure:"skipped,omitempty"`
	// List of the run list.
	Children             []*RunList `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty" toml:"children,omitempty" mapstructure:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte     `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32      `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *RunList) Reset()         { *m = RunList{} }
func (m *RunList) String() string { return proto.CompactTextString(m) }
func (*RunList) ProtoMessage()    {}
func (*RunList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd54a1c203a9a33, []int{4}
}

func (m *RunList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunList.Unmarshal(m, b)
}
func (m *RunList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunList.Marshal(b, m, deterministic)
}
func (m *RunList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunList.Merge(m, src)
}
func (m *RunList) XXX_Size() int {
	return xxx_messageInfo_RunList.Size(m)
}
func (m *RunList) XXX_DiscardUnknown() {
	xxx_messageInfo_RunList.DiscardUnknown(m)
}

var xxx_messageInfo_RunList proto.InternalMessageInfo

func (m *RunList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RunList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunList) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RunList) GetSkipped() bool {
	if m != nil {
		return m.Skipped
	}
	return false
}

func (m *RunList) GetChildren() []*RunList {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Roles)(nil), "chef.automate.domain.infra_proxy.response.Roles")
	proto.RegisterType((*RoleListItem)(nil), "chef.automate.domain.infra_proxy.response.RoleListItem")
	proto.RegisterType((*Role)(nil), "chef.automate.domain.infra_proxy.response.Role")
	proto.RegisterType((*ExpandedRunList)(nil), "chef.automate.domain.infra_proxy.response.ExpandedRunList")
	proto.RegisterType((*RunList)(nil), "chef.automate.domain.infra_proxy.response.RunList")
}

func init() {
	proto.RegisterFile("interservice/infra_proxy/response/roles.proto", fileDescriptor_ccd54a1c203a9a33)
}

var fileDescriptor_ccd54a1c203a9a33 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xd3, 0x76, 0xdb, 0xce, 0xae, 0x58, 0xad, 0xb9, 0x18, 0x21, 0xa4, 0x2a, 0xa7, 0x72,
	0xd8, 0x44, 0x5a, 0x0e, 0x48, 0x1c, 0x10, 0x1f, 0xe2, 0x80, 0xc4, 0x72, 0x88, 0x10, 0x07, 0x2e,
	0x91, 0x1b, 0x4f, 0xe9, 0x40, 0x62, 0x5b, 0xb6, 0x53, 0x6d, 0x7f, 0x18, 0xbf, 0x86, 0x3f, 0x83,
	0xec, 0x4d, 0x4a, 0x96, 0x45, 0x82, 0xdd, 0x5b, 0xfc, 0xe6, 0xcd, 0x7b, 0x33, 0x7e, 0x31, 0x9c,
	0x93, 0xf2, 0x68, 0x1d, 0xda, 0x1d, 0x55, 0x98, 0x93, 0xda, 0x58, 0x51, 0x1a, 0xab, 0xaf, 0xf6,
	0xb9, 0x45, 0x67, 0xb4, 0x72, 0x98, 0x5b, 0x5d, 0xa3, 0xcb, 0x8c, 0xd5, 0x5e, 0xb3, 0xa7, 0xd5,
	0x16, 0x37, 0x99, 0x68, 0xbd, 0x6e, 0x84, 0xc7, 0x4c, 0xea, 0x46, 0x90, 0xca, 0x06, 0x6d, 0x59,
	0xdf, 0x96, 0x7e, 0x86, 0x69, 0x11, 0x3a, 0xd9, 0x25, 0x4c, 0xa3, 0x04, 0x1f, 0x2d, 0xc7, 0xab,
	0xe3, 0x8b, 0xe7, 0xd9, 0x7f, 0x6b, 0x64, 0x41, 0xe0, 0x03, 0x39, 0xff, 0xde, 0x63, 0x53, 0x5c,
	0xab, 0xa4, 0x5b, 0x38, 0x19, 0xc2, 0x8c, 0xc1, 0x44, 0x89, 0x06, 0xf9, 0x68, 0x39, 0x5a, 0x2d,
	0x8a, 0xf8, 0xcd, 0x96, 0x70, 0x2c, 0xd1, 0x55, 0x96, 0x8c, 0x27, 0xad, 0x78, 0x12, 0x4b, 0x43,
	0x88, 0xa5, 0x70, 0x82, 0x6a, 0x47, 0x56, 0xab, 0x06, 0x95, 0x77, 0x7c, 0xbc, 0x1c, 0xaf, 0x16,
	0xc5, 0x0d, 0x2c, 0xfd, 0x99, 0xc0, 0x24, 0x58, 0xfd, 0xd5, 0xe2, 0x31, 0x2c, 0xc2, 0x1e, 0xa5,
	0xdf, 0x1b, 0xec, 0x0c, 0xe6, 0x01, 0xf8, 0xb4, 0x37, 0xb7, 0xfc, 0xc7, 0xb7, 0xfd, 0xcf, 0x81,
	0x49, 0xdc, 0x88, 0xb6, 0xf6, 0xa5, 0xf0, 0xde, 0xd2, 0xba, 0xf5, 0xe8, 0xf8, 0x24, 0x12, 0xcf,
	0xba, 0xca, 0xeb, 0x43, 0x81, 0xe5, 0xf0, 0x50, 0xef, 0xd0, 0x5a, 0x92, 0x38, 0xe4, 0x4f, 0x23,
	0x9f, 0xf5, 0xa5, 0x41, 0xc3, 0x13, 0x80, 0x6f, 0x4e, 0xab, 0xb2, 0xaa, 0x85, 0x73, 0xfc, 0x28,
	0xf2, 0x16, 0x01, 0x79, 0x1b, 0x00, 0xf6, 0x08, 0xe6, 0xb6, 0x55, 0x65, 0x4d, 0xce, 0xf3, 0x59,
	0x5c, 0x7d, 0x66, 0x5b, 0x15, 0xee, 0x94, 0x6d, 0xe0, 0x0c, 0xaf, 0x8c, 0x50, 0x12, 0x65, 0x79,
	0xe0, 0xcc, 0x63, 0x74, 0x2f, 0xee, 0x10, 0xdd, 0xbb, 0x4e, 0xa3, 0xb8, 0x96, 0x2d, 0x4e, 0xf1,
	0x26, 0x90, 0x1a, 0x38, 0xfd, 0x83, 0xc3, 0x1e, 0x40, 0x42, 0xb2, 0xbb, 0xe5, 0x84, 0x24, 0xbb,
	0x1c, 0x4c, 0x99, 0xc4, 0x09, 0x2e, 0xee, 0xf2, 0xf3, 0x74, 0xce, 0xfd, 0x66, 0xe9, 0x8f, 0x11,
	0xcc, 0x7a, 0x2b, 0x06, 0x93, 0x98, 0x5c, 0x17, 0x69, 0xf8, 0x3e, 0xc4, 0x9c, 0x0c, 0x62, 0xe6,
	0x30, 0xdb, 0xa1, 0x75, 0xbf, 0x53, 0xec, 0x8f, 0xa1, 0xe2, 0xbe, 0x93, 0x31, 0x28, 0x63, 0x6c,
	0xf3, 0xa2, 0x3f, 0xb2, 0x8f, 0x30, 0xaf, 0xb6, 0x54, 0x4b, 0x8b, 0x8a, 0x4f, 0xef, 0x3d, 0xf6,
	0x41, 0xe3, 0xcd, 0xab, 0x2f, 0x2f, 0xbf, 0x92, 0xdf, 0xb6, 0xeb, 0xac, 0xd2, 0x4d, 0x1e, 0x94,
	0xf2, 0x5e, 0x29, 0x17, 0x86, 0xf2, 0x7f, 0x3e, 0xe1, 0xf5, 0x51, 0x7c, 0xbd, 0xcf, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x25, 0x23, 0x41, 0xbf, 0xee, 0x03, 0x00, 0x00,
}
