#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0
export CURRENT_ACCESS_KEY="{{cfg.bookshelf.aws_access_id}}"
export CURRENT_SECRET_KEY="{{cfg.bookshelf.aws_secret_key}}"

{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

mkdir -p {{pkg.svc_var_path}}/logs

export HOME={{pkg.svc_var_path}}
export RUNNER_LOG_DIR="{{pkg.svc_var_path}}/logs"
export RELX_CONFIG_PATH="{{pkg.svc_config_path}}/sys.config"
export VMARGS_PATH="{{pkg.svc_config_path}}/vm.args"
export DBNAME="{{cfg.sql.db_name}}"

mkdir -p "{{pkg.svc_var_path}}/etc"
render-template sqerl.config "{{pkg.svc_var_path}}/etc/sqerl.config"

pg-helper rename-if-exists bookshelf "$DBNAME"
pg-helper ensure-service-database "$DBNAME"
pg-helper create-extension "$DBNAME" "uuid-ossp"
pg-helper sqitch-deploy "$DBNAME" "{{pkgPathFor "chef/bookshelf"}}/schema"
pg-helper fix-permissions "$DBNAME"

if [[ -z "${CURRENT_SECRET_KEY}" ]]; then
  secrets-helper generate bookshelf.access_key_id 64 --if-not-exists
  secrets-helper generate bookshelf.secret_access_key 64 --if-not-exists
else
  echo -n "${CURRENT_ACCESS_KEY}" | secrets-helper insert bookshelf.access_key_id
  echo -n "${CURRENT_SECRET_KEY}" | secrets-helper insert bookshelf.secret_access_key
fi


exec secrets-helper exec --secret bookshelf.access_key_id --secret bookshelf.secret_access_key -- bookshelf foreground
