#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

# Postgres Database Management
# We do this here because init hooks block the hab supervisor
DBNAME="{{cfg.storage.database}}"
if [ ! -f /hab/.skip_migration ]; then
  echo "/hab/.skip_migration does not exist, running pg-helper command $(pwd)/$0 at $LINENO"
  pg-helper ensure-service-database "$DBNAME"
  pg-helper create-extension "$DBNAME" "pgcrypto"
  pg-helper fix-permissions "$DBNAME"
else 
  echo "/hab/.skip_migration does exist, skipping pg-helper"  
fi

# Start our service
exec config-mgmt-service serve --config {{pkg.svc_config_path}}/config.toml
