source 'https://rubygems.org'

gem 'rake'
gem 'ed25519'
gem 'train'
gem 'net-ssh'
gem 'assert'
gem 'mixlib-shellout', '~> 3.0.9'
gem 'clamp'
gem 'tty-spinner'
gem 'tty-prompt'
gem 'tty-table'
gem 'tty-logger'
gem 'mixlib-config'
gem 'rspec'
gem 'tomlrb'
gem 'bcrypt_pbkdf'

if Gem::Version.new(RUBY_VERSION) <= Gem::Version.new("3.1.0")
  gem "ffi", "< 1.17.0"
  gem "train-core", "< 3.12.5"
end