[global.v1]
  [global.v1.external.minio]
    endpoint = "127.0.0.1:9000"
    root_user = "minioadmin"
    root_password = "minioadmin"
    enable_ssl = false
    cert = """-----BEGIN CERTIFICATE-----
MIIFsDCCA5igAwIBAgIBBzANBgkqhkiG9w0BAQwFADBQMQswCQYDVQQGEwJFWDEQ
MA4GA1UECBMHRXhhbXBsZTEVMBMGA1UEChMMRXhhbXBsZSBJbmMuMRgwFgYDVQQD
Ew9TYWxseSBDZXJ0b3duZXIwHhcNMjIwNTE2MTQyNTMxWhcNMjMwNTE2MTQyNTMx
WjBQMQswCQYDVQQGEwJFWDEQMA4GA1UECBMHRXhhbXBsZTEVMBMGA1UEChMMRXhh
bXBsZSBJbmMuMRgwFgYDVQQDEw9TYWxseSBDZXJ0b3duZXIwggIiMA0GCSqGSIb3
DQEBAQUAA4ICDwAwggIKAoICAQCuhIPy+yJnQnhdi0/U8ZcbfNzZqWy7tVJnt21C
SAg5FreHoQ5pA+tMDuRgoNdmvaFlVujjEAnBJCJh6czDA/wQEOkyUMEVPChAHT1V
8R6XyhtyEBidVh3E4+O+Ikfd6iLZHcdVhPcY1LThSXRhvVrXknlWfoinUrsfe23L
KC8JMXoNxKafW6ryFgFYUQL+N3QmL4aR9VleACMF4jIz4Iey++FUAy/Pk8zNEkcH
vZ1Z/5HfknbdGmBC1UNuSGXuaHVLRX/ofg5Az2XXdAA9rRYGCVvgOBeMjLdTRAmm
gT+BlECf+N5G0owYiFiqp5v8Uj7jySOF9hWdhXhbK5iAqDmboDPfGmSMYVqsqUcV
aEuToNa3E1ISkvJNO3G9/jZHCiNuvOv7CM7V5G6r/pNYZwYb1JD2xady4E2/js0r
oA5DC2sZoKgVDTn19xsXBc/meg4Ah34I/3pIIgRecvEv+cyJhgC9Looc9cutHMrB
7PTNn55nfBWIPcA/ZKzU00+W7eXDZzNuTsnPSbVrNvOXHB7RGW7YNm0jVACWrZ0R
UZOUC3DgZJ6yN8f0AGIKYfENFvFcUy02rN7hapW8mlodJjLbewbrHK2ABSGGWxl3
IoU05bVweGQTSgGwbFsAb/iBUbDURsbVoUXykciViC4rAPQjBC3EBtPfaS1K57t1
O2vG2wIDAQABo4GUMIGRMAwGA1UdEwEB/wQCMAAwPQYDVR0RBDYwNIIyZWMyLTQz
LTIwNC0xNy0xMTYuYXAtc291dGgtMS5jb21wdXRlLmFtYXpvbmF3cy5jb20wEwYD
VR0lBAwwCgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgUgMB0GA1UdDgQWBBTjYT0+
p2W+RLR33P6qOUsh2JPD3zANBgkqhkiG9w0BAQwFAAOCAgEAc9s6sJuA5URcGnBh
Vbx2l+o7JCq8okjlcBp7iOOjZBOt1oAjQncocaVSPfIcLV5e349Ag+fukSyOFwJ6
8AV+syVmEi3GGyEmtYpCe5H4fG0+iF6ILNN9Xe/0USTg5pdfTxp/H3bN/U7D5kOy
FUO0dWyFYjLx7ypnLtzxgEYzfbr3pTqGo+/QXLFsV98Tddk7vDgW8Pdtl7PrwHZ1
YG74QPHX95kU+KU3pQPpY2LQIFnj3YRTEcwRDSr+2lcu4EvanYI2Gg2oGTJOWV/e
es51FORUVTtmEZgamAohGALL578ZN/zDzro8bowxzqLb8Y+Bbnj8LPM8eJPg+1Y+
fFUCV6XhDQtxB7Fz6TNu1xI9og5PowW2iwZfYQfaVmyjZihwMnN3bV2Ddps5Dwkh
YKSblX8Zgxdn3vAxOYrhm+Fwwn3RbTX2gzDsekCfocN7JfnGJ2PAYKlw7N12dEcc
ESwJQ3gafpWB2MxrmncBVowuxlkR5LbiiSMVGNQOsMiA3KEWYpGn5K8Kc+yYbvDl
uHaxjWl1hp3ZmlmGIgg67cAHQmtoDX8NBzdnv7g90U5V7eDyIN8im3NMFiIwzK2k
b5Imk9MSwDmPODwxeyhlkhc1Fc95zvywQXTUKYZSiMhHPqVJNnhKtLlHtH4Rv0ap
Q1lBcRjmrH0NJlDnShLP0vYBc2E=
-----END CERTIFICATE-----"""

  [global.v1.large_reporting]
    enable_large_reporting = false

[report_manager.v1.sys.objstore]
  bucket = "default"