[global.v1]
  [global.v1.disclosure]
    show = true
    message_file_path = "/src/dev/banner_message.txt"
  [global.v1.banner]
    show = true
    message = "Hooray, I'm a banner"
    background_color = "3864f2" # Must be a hex value minus the hash symbol
    text_color = "FFF" # Must be a hex value minus the hash symbol