// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/automate-gateway/api/iam/v2/response/teams.proto

package response

import (
	fmt "fmt"
	common "github.com/chef/automate/components/automate-gateway/api/iam/v2/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTeamResp struct {
	Team                 *common.Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTeamResp) Reset()         { *m = GetTeamResp{} }
func (m *GetTeamResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamResp) ProtoMessage()    {}
func (*GetTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{0}
}

func (m *GetTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamResp.Unmarshal(m, b)
}
func (m *GetTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamResp.Marshal(b, m, deterministic)
}
func (m *GetTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamResp.Merge(m, src)
}
func (m *GetTeamResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamResp.Size(m)
}
func (m *GetTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamResp proto.InternalMessageInfo

func (m *GetTeamResp) GetTeam() *common.Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type ListTeamsResp struct {
	Teams                []*common.Team `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListTeamsResp) Reset()         { *m = ListTeamsResp{} }
func (m *ListTeamsResp) String() string { return proto.CompactTextString(m) }
func (*ListTeamsResp) ProtoMessage()    {}
func (*ListTeamsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{1}
}

func (m *ListTeamsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTeamsResp.Unmarshal(m, b)
}
func (m *ListTeamsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTeamsResp.Marshal(b, m, deterministic)
}
func (m *ListTeamsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTeamsResp.Merge(m, src)
}
func (m *ListTeamsResp) XXX_Size() int {
	return xxx_messageInfo_ListTeamsResp.Size(m)
}
func (m *ListTeamsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTeamsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListTeamsResp proto.InternalMessageInfo

func (m *ListTeamsResp) GetTeams() []*common.Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type CreateTeamResp struct {
	Team                 *common.Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateTeamResp) Reset()         { *m = CreateTeamResp{} }
func (m *CreateTeamResp) String() string { return proto.CompactTextString(m) }
func (*CreateTeamResp) ProtoMessage()    {}
func (*CreateTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{2}
}

func (m *CreateTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamResp.Unmarshal(m, b)
}
func (m *CreateTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamResp.Marshal(b, m, deterministic)
}
func (m *CreateTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamResp.Merge(m, src)
}
func (m *CreateTeamResp) XXX_Size() int {
	return xxx_messageInfo_CreateTeamResp.Size(m)
}
func (m *CreateTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamResp proto.InternalMessageInfo

func (m *CreateTeamResp) GetTeam() *common.Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type UpdateTeamResp struct {
	Team                 *common.Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateTeamResp) Reset()         { *m = UpdateTeamResp{} }
func (m *UpdateTeamResp) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamResp) ProtoMessage()    {}
func (*UpdateTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{3}
}

func (m *UpdateTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamResp.Unmarshal(m, b)
}
func (m *UpdateTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamResp.Marshal(b, m, deterministic)
}
func (m *UpdateTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamResp.Merge(m, src)
}
func (m *UpdateTeamResp) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamResp.Size(m)
}
func (m *UpdateTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamResp proto.InternalMessageInfo

func (m *UpdateTeamResp) GetTeam() *common.Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type DeleteTeamResp struct {
	Team                 *common.Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteTeamResp) Reset()         { *m = DeleteTeamResp{} }
func (m *DeleteTeamResp) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamResp) ProtoMessage()    {}
func (*DeleteTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{4}
}

func (m *DeleteTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamResp.Unmarshal(m, b)
}
func (m *DeleteTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamResp.Marshal(b, m, deterministic)
}
func (m *DeleteTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamResp.Merge(m, src)
}
func (m *DeleteTeamResp) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamResp.Size(m)
}
func (m *DeleteTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamResp proto.InternalMessageInfo

func (m *DeleteTeamResp) GetTeam() *common.Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type AddTeamMembersResp struct {
	MembershipIds        []string `protobuf:"bytes,1,rep,name=membership_ids,json=membershipIds,proto3" json:"membership_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTeamMembersResp) Reset()         { *m = AddTeamMembersResp{} }
func (m *AddTeamMembersResp) String() string { return proto.CompactTextString(m) }
func (*AddTeamMembersResp) ProtoMessage()    {}
func (*AddTeamMembersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{5}
}

func (m *AddTeamMembersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeamMembersResp.Unmarshal(m, b)
}
func (m *AddTeamMembersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeamMembersResp.Marshal(b, m, deterministic)
}
func (m *AddTeamMembersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeamMembersResp.Merge(m, src)
}
func (m *AddTeamMembersResp) XXX_Size() int {
	return xxx_messageInfo_AddTeamMembersResp.Size(m)
}
func (m *AddTeamMembersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeamMembersResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeamMembersResp proto.InternalMessageInfo

func (m *AddTeamMembersResp) GetMembershipIds() []string {
	if m != nil {
		return m.MembershipIds
	}
	return nil
}

type GetTeamMembershipResp struct {
	MembershipIds        []string `protobuf:"bytes,1,rep,name=membership_ids,json=membershipIds,proto3" json:"membership_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamMembershipResp) Reset()         { *m = GetTeamMembershipResp{} }
func (m *GetTeamMembershipResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamMembershipResp) ProtoMessage()    {}
func (*GetTeamMembershipResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{6}
}

func (m *GetTeamMembershipResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamMembershipResp.Unmarshal(m, b)
}
func (m *GetTeamMembershipResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamMembershipResp.Marshal(b, m, deterministic)
}
func (m *GetTeamMembershipResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamMembershipResp.Merge(m, src)
}
func (m *GetTeamMembershipResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamMembershipResp.Size(m)
}
func (m *GetTeamMembershipResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamMembershipResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamMembershipResp proto.InternalMessageInfo

func (m *GetTeamMembershipResp) GetMembershipIds() []string {
	if m != nil {
		return m.MembershipIds
	}
	return nil
}

type RemoveTeamMembersResp struct {
	MembershipIds        []string `protobuf:"bytes,1,rep,name=membership_ids,json=membershipIds,proto3" json:"membership_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTeamMembersResp) Reset()         { *m = RemoveTeamMembersResp{} }
func (m *RemoveTeamMembersResp) String() string { return proto.CompactTextString(m) }
func (*RemoveTeamMembersResp) ProtoMessage()    {}
func (*RemoveTeamMembersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{7}
}

func (m *RemoveTeamMembersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTeamMembersResp.Unmarshal(m, b)
}
func (m *RemoveTeamMembersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTeamMembersResp.Marshal(b, m, deterministic)
}
func (m *RemoveTeamMembersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTeamMembersResp.Merge(m, src)
}
func (m *RemoveTeamMembersResp) XXX_Size() int {
	return xxx_messageInfo_RemoveTeamMembersResp.Size(m)
}
func (m *RemoveTeamMembersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTeamMembersResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTeamMembersResp proto.InternalMessageInfo

func (m *RemoveTeamMembersResp) GetMembershipIds() []string {
	if m != nil {
		return m.MembershipIds
	}
	return nil
}

type GetTeamsForMemberResp struct {
	Teams                []*common.Team `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTeamsForMemberResp) Reset()         { *m = GetTeamsForMemberResp{} }
func (m *GetTeamsForMemberResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamsForMemberResp) ProtoMessage()    {}
func (*GetTeamsForMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{8}
}

func (m *GetTeamsForMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsForMemberResp.Unmarshal(m, b)
}
func (m *GetTeamsForMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsForMemberResp.Marshal(b, m, deterministic)
}
func (m *GetTeamsForMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsForMemberResp.Merge(m, src)
}
func (m *GetTeamsForMemberResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamsForMemberResp.Size(m)
}
func (m *GetTeamsForMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsForMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsForMemberResp proto.InternalMessageInfo

func (m *GetTeamsForMemberResp) GetTeams() []*common.Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type ApplyV2DataMigrationsResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyV2DataMigrationsResp) Reset()         { *m = ApplyV2DataMigrationsResp{} }
func (m *ApplyV2DataMigrationsResp) String() string { return proto.CompactTextString(m) }
func (*ApplyV2DataMigrationsResp) ProtoMessage()    {}
func (*ApplyV2DataMigrationsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{9}
}

func (m *ApplyV2DataMigrationsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyV2DataMigrationsResp.Unmarshal(m, b)
}
func (m *ApplyV2DataMigrationsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyV2DataMigrationsResp.Marshal(b, m, deterministic)
}
func (m *ApplyV2DataMigrationsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyV2DataMigrationsResp.Merge(m, src)
}
func (m *ApplyV2DataMigrationsResp) XXX_Size() int {
	return xxx_messageInfo_ApplyV2DataMigrationsResp.Size(m)
}
func (m *ApplyV2DataMigrationsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyV2DataMigrationsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyV2DataMigrationsResp proto.InternalMessageInfo

type ResetAllTeamProjectsResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetAllTeamProjectsResp) Reset()         { *m = ResetAllTeamProjectsResp{} }
func (m *ResetAllTeamProjectsResp) String() string { return proto.CompactTextString(m) }
func (*ResetAllTeamProjectsResp) ProtoMessage()    {}
func (*ResetAllTeamProjectsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0fc0626d013215, []int{10}
}

func (m *ResetAllTeamProjectsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetAllTeamProjectsResp.Unmarshal(m, b)
}
func (m *ResetAllTeamProjectsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetAllTeamProjectsResp.Marshal(b, m, deterministic)
}
func (m *ResetAllTeamProjectsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetAllTeamProjectsResp.Merge(m, src)
}
func (m *ResetAllTeamProjectsResp) XXX_Size() int {
	return xxx_messageInfo_ResetAllTeamProjectsResp.Size(m)
}
func (m *ResetAllTeamProjectsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetAllTeamProjectsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetAllTeamProjectsResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetTeamResp)(nil), "chef.automate.api.iam.v2.GetTeamResp")
	proto.RegisterType((*ListTeamsResp)(nil), "chef.automate.api.iam.v2.ListTeamsResp")
	proto.RegisterType((*CreateTeamResp)(nil), "chef.automate.api.iam.v2.CreateTeamResp")
	proto.RegisterType((*UpdateTeamResp)(nil), "chef.automate.api.iam.v2.UpdateTeamResp")
	proto.RegisterType((*DeleteTeamResp)(nil), "chef.automate.api.iam.v2.DeleteTeamResp")
	proto.RegisterType((*AddTeamMembersResp)(nil), "chef.automate.api.iam.v2.AddTeamMembersResp")
	proto.RegisterType((*GetTeamMembershipResp)(nil), "chef.automate.api.iam.v2.GetTeamMembershipResp")
	proto.RegisterType((*RemoveTeamMembersResp)(nil), "chef.automate.api.iam.v2.RemoveTeamMembersResp")
	proto.RegisterType((*GetTeamsForMemberResp)(nil), "chef.automate.api.iam.v2.GetTeamsForMemberResp")
	proto.RegisterType((*ApplyV2DataMigrationsResp)(nil), "chef.automate.api.iam.v2.ApplyV2DataMigrationsResp")
	proto.RegisterType((*ResetAllTeamProjectsResp)(nil), "chef.automate.api.iam.v2.ResetAllTeamProjectsResp")
}

func init() {
	proto.RegisterFile("components/automate-gateway/api/iam/v2/response/teams.proto", fileDescriptor_6a0fc0626d013215)
}

var fileDescriptor_6a0fc0626d013215 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x95, 0x5d, 0x6b, 0xd4, 0x4c,
	0x14, 0xc7, 0x19, 0x9e, 0x47, 0xc1, 0x94, 0xf6, 0x62, 0x41, 0x58, 0x2b, 0x48, 0x18, 0x10, 0xbc,
	0xe8, 0x24, 0xdd, 0xd9, 0x97, 0x76, 0xe3, 0x55, 0xb4, 0xf8, 0x86, 0x0b, 0xb2, 0x54, 0x41, 0xcb,
	0xa2, 0x27, 0xc9, 0x49, 0x76, 0x74, 0x27, 0x33, 0x64, 0xa6, 0x2d, 0xa5, 0xec, 0x97, 0xe8, 0x37,
	0x10, 0x45, 0x85, 0x7e, 0x3c, 0x2f, 0xbd, 0x91, 0x49, 0xfa, 0x7a, 0x51, 0xa8, 0x78, 0xd3, 0xe2,
	0x5d, 0xce, 0xdb, 0xff, 0xfc, 0xe6, 0x64, 0x98, 0xe3, 0x3d, 0x4c, 0x95, 0xd4, 0xaa, 0xc4, 0xd2,
	0x9a, 0x10, 0xb6, 0xad, 0x92, 0x60, 0x91, 0x15, 0x60, 0x71, 0x17, 0xf6, 0x42, 0xd0, 0x22, 0x14,
	0x20, 0xc3, 0x1d, 0x1e, 0x56, 0x68, 0xb4, 0x2a, 0x0d, 0x86, 0x16, 0x41, 0x9a, 0x40, 0x57, 0xca,
	0xaa, 0x56, 0x3b, 0x9d, 0x62, 0x1e, 0x1c, 0x97, 0x05, 0xa0, 0x45, 0x20, 0x40, 0x06, 0x3b, 0x7c,
	0x79, 0xa5, 0x4e, 0x48, 0x59, 0x81, 0x25, 0x33, 0xbb, 0x50, 0x14, 0x58, 0x85, 0x4a, 0x5b, 0xa1,
	0x4a, 0x13, 0x42, 0x59, 0x2a, 0x0b, 0xf5, 0x77, 0xa3, 0xb3, 0x3c, 0xbc, 0x24, 0x44, 0xaa, 0xa4,
	0x54, 0xe5, 0x59, 0x04, 0xfa, 0x85, 0x78, 0x0b, 0x4f, 0xd1, 0x6e, 0x22, 0xc8, 0x31, 0x1a, 0xdd,
	0xe2, 0xde, 0xff, 0x2e, 0xdc, 0x26, 0x3e, 0x79, 0xb0, 0xc0, 0xef, 0x05, 0x17, 0x11, 0x06, 0x75,
	0x45, 0x9d, 0x1b, 0x7d, 0x38, 0x88, 0x27, 0x7c, 0xab, 0xf5, 0x76, 0x9f, 0x3a, 0x93, 0x46, 0xfe,
	0x3e, 0x15, 0x19, 0x8d, 0x7c, 0x6a, 0xd1, 0x58, 0x26, 0x32, 0xba, 0xe2, 0xd3, 0x12, 0x24, 0x3a,
	0xd7, 0x68, 0xcf, 0xdf, 0x44, 0x63, 0x7d, 0x57, 0xee, 0xfc, 0xba, 0x52, 0x1f, 0x31, 0xb5, 0x86,
	0x46, 0xfe, 0xd6, 0xb1, 0xd1, 0x39, 0x13, 0xe0, 0x74, 0x32, 0x9f, 0xd3, 0x9f, 0xc4, 0x5b, 0x7c,
	0x29, 0x4c, 0x8d, 0x69, 0x6a, 0xce, 0x9e, 0x77, 0xa3, 0x3e, 0x46, 0x9b, 0xf8, 0xff, 0x5d, 0x02,
	0xb4, 0x49, 0x8e, 0x0e, 0xc9, 0x41, 0xfc, 0x9d, 0xf0, 0xaf, 0xa4, 0xf5, 0x99, 0x34, 0xb4, 0x75,
	0xe3, 0x73, 0xbc, 0x9d, 0xbf, 0xc5, 0x5d, 0x39, 0x7f, 0x7e, 0x7e, 0x91, 0x9e, 0xcf, 0x2f, 0x56,
	0x9c, 0xcc, 0x27, 0x73, 0xfa, 0x8d, 0x78, 0x4b, 0x8f, 0x2b, 0x04, 0x8b, 0x57, 0xfc, 0xf7, 0x38,
	0xd0, 0xd7, 0x3a, 0xbb, 0x1e, 0xa0, 0x1b, 0x38, 0xc3, 0x2b, 0x0f, 0xfa, 0x83, 0x78, 0xad, 0x38,
	0xcb, 0x5c, 0xd1, 0x08, 0x65, 0x82, 0x55, 0x73, 0xeb, 0xef, 0x7b, 0x4b, 0xb2, 0x31, 0xa7, 0x42,
	0xbf, 0x17, 0x59, 0x73, 0xfd, 0x6f, 0x8d, 0x17, 0x4f, 0xbd, 0xcf, 0x33, 0x13, 0x7d, 0x3a, 0x88,
	0xa7, 0x3c, 0x6f, 0x65, 0xfb, 0xf4, 0x7c, 0x76, 0xdd, 0xb3, 0xcf, 0xd7, 0x30, 0x1b, 0x0e, 0x72,
	0xc6, 0x31, 0x4d, 0x58, 0x2f, 0x5f, 0xcf, 0x19, 0x24, 0xd9, 0x1a, 0x5b, 0x4d, 0xf2, 0x41, 0xbf,
	0xd3, 0xe9, 0xf5, 0x87, 0x90, 0x3a, 0x9e, 0x6e, 0xbf, 0x0b, 0x03, 0x9e, 0xf5, 0xd8, 0x7a, 0x3f,
	0x07, 0xd6, 0xeb, 0xf1, 0x2e, 0x4b, 0x3a, 0x1c, 0x58, 0x3e, 0x18, 0xac, 0xae, 0x43, 0x7f, 0xc0,
	0x01, 0x87, 0x74, 0x32, 0xa7, 0x87, 0xc4, 0xbb, 0x7d, 0xf4, 0x82, 0x8c, 0x4e, 0xba, 0x5d, 0x69,
	0xda, 0x31, 0x4a, 0xb5, 0x83, 0xd7, 0x61, 0xb6, 0xbf, 0x4e, 0x67, 0x6b, 0x9e, 0xa8, 0xaa, 0xc1,
	0xfd, 0x67, 0xde, 0xbf, 0xbb, 0xde, 0x9d, 0x58, 0xeb, 0xd9, 0xde, 0x1b, 0xbe, 0x01, 0x16, 0x46,
	0xa2, 0xa8, 0x9a, 0xad, 0xe7, 0x06, 0x40, 0x97, 0xbd, 0xf6, 0x18, 0x0d, 0xda, 0x78, 0x36, 0x73,
	0x62, 0xaf, 0x8e, 0x64, 0x5c, 0xec, 0xd1, 0x8b, 0x77, 0xcf, 0x0a, 0x61, 0xa7, 0xdb, 0x49, 0x90,
	0x2a, 0x19, 0xba, 0xc9, 0x9c, 0xac, 0xc5, 0xf0, 0x0f, 0xf7, 0x75, 0x72, 0xb3, 0xde, 0x93, 0xdd,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x35, 0x34, 0x05, 0xe9, 0x07, 0x00, 0x00,
}
