#!{{pkgPathFor "core/bash"}}/bin/bash

set -e

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

exec applications-load-gen run \
  --use-builtin-full-profile \
  --svc-count {{cfg.target.svc_count}} \
  --host {{cfg.target.host}} \
  --auth-token {{cfg.target.auth_token}}
