[service]
host = "127.0.0.1"
port = {{cfg.service.port}}
log_level = "{{cfg.log.level}}"

[tls]
cert_path = "{{pkg.svc_config_path}}/service.crt"
key_path = "{{pkg.svc_config_path}}/service.key"
root_ca_path ="{{pkg.svc_config_path}}/root_ca.crt"

[elasticsearch]
{{~#eachAlive bind.automate-es-gateway.members as |member|}}
{{~#if @last}}
url = "http://127.0.0.1:{{member.cfg.http-port}}"
{{~/if}}
{{~/eachAlive}}

[elasticsearch_sidecar]
{{~#eachAlive bind.es-sidecar-service.members as |member|}}
{{~#if @last}}
address = "127.0.0.1:{{member.cfg.port}}"
{{~/if}}
{{~/eachAlive}}

[jobs]
{{~#if cfg.service.purge_event_feed_after_days }}
default_purge_after_days = {{cfg.service.purge_event_feed_after_days}}
{{else}}
default_purge_after_days = 7
{{~/if}}

[cereal]
{{~#eachAlive bind.cereal-service.members as |member|}}
{{~#if @last}}
address = "127.0.0.1:{{member.cfg.port}}"
{{~/if}}
{{~/eachAlive}}

[authz]
{{~#eachAlive bind.authz-service.members as |member|}}
{{~#if @last}}
address = "127.0.0.1:{{member.cfg.port}}"
{{~/if}}
{{~/eachAlive}}
