[service]
{{~#if cfg.service.host}}
host = "{{cfg.service.host}}"
{{~else}}
host = "{{sys.ip}}"
{{~/if}}
port = {{cfg.service.port}}
log_level = "{{cfg.log.level}}"

[tls]
cert_path = "{{pkg.svc_config_path}}/service.crt"
key_path = "{{pkg.svc_config_path}}/service.key"
root_ca_path ="{{pkg.svc_config_path}}/root_ca.crt"

[elasticsearch]
{{~#eachAlive bind.automate-es-gateway.members as |member|}}
{{~#if member.cfg.http-host}}
url = "http://{{member.sys.ip}}:{{member.cfg.http-port}}"
{{else}}
url = "http://127.0.0.1:{{member.cfg.http-port}}"
{{~/if}}
{{~/eachAlive}}

[elasticsearch_sidecar]
{{~#eachAlive bind.es-sidecar-service.members as |member|}}
address = "{{member.sys.ip}}:{{member.cfg.port}}"
{{~/eachAlive}}

[data_lifecycle]
{{~#if cfg.service.purge_event_feed_after_days }}
purge_event_feed_after_days = {{cfg.service.purge_event_feed_after_days}}
{{~/if}}
