[mlsa]
accept = false

[log]
level = "error"

[service]
host = "localhost"
port = 2015

[tls]
key_contents = ""
cert_contents = ""
root_cert_contents = ""

[ngx]
worker_processes = 4

[ngx.events]
worker_connections = 1024

[ngx.http]
sendfile = "on"
default_type = "application/octet-stream"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = 60
gzip = "on"
gzip_vary = "on"
gzip_min_length = 10240
gzip_proxied = "expired no-cache no-store private auth"
gzip_types = "text/plain text/css text/xml text/javascript application/x-javascript application/xml"
gzip_disable = "MSIE [1-6]\\."
client_body_buffer_size = "16k"

# Mutual TLS is currently disabled.
# we could enable mutual TLS by setting "ssl_verify_client" to "on"
# and by setting "ssl_verify_depth" to "2".
ssl_verify_client = "off"
ssl_verify_depth = "1"
ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:AES256-GCM-SHA384:!aNULL:!eNULL:!EXPORT"
ssl_protocols = "TLSv1.2 TLSv1.3"
