#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

pg-helper ensure-service-database "user-settings-service"
pg-helper create-extension "user-settings-service" "pgcrypto"

source {{pkg.svc_config_path}}/init_proxy

exec "user-settings-service" "serve" "--config" "{{pkg.svc_config_path}}/config.toml"
