cookie_domain             = ""
docs_url                  = "https://www.habitat.sh/docs"
environment               = "production"
hosted                    = false
source_code_url           = "https://github.com/habitat-sh/habitat"
tutorials_url             = "https://www.habitat.sh/learn"
use_gravatar              = false
www_url                   = "https://www.habitat.sh"
# How we connect to the proxied backend API service.
#   When true, connect to all backend API services via their IPs provided
#   via the bind
#   By default (load_balanced=false) we connect to a single backend on the same `sys.ip` as this service
load_balanced             = false

[analytics]
enabled                   = false

[github]
app_id                    = 5565
app_url                   = "https://github.com/apps/habitat-builder"
api_url                   = "https://api.github.com"

[oauth]
provider       = "chef-automate"
redirect_url   = "/bldr"
client_id      = "automate-builder-api"
authorize_url  = "/session/new"

[nginx]
worker_connections        = 1024
worker_processes          = "auto"
worker_rlimit_nofile      = 8192
max_body_size             = 0
proxy_send_timeout        = 300
proxy_read_timeout        = 300
proxy_connect_timeout     = 60
enable_caching            = false
enable_gzip               = false

[http]
keepalive_connections     = 16
keepalive_requests        = 128
keepalive_timeout         = 180
sendfile                  = "on"
tcp_nopush                = "on"
tcp_nodelay               = "on"

[service]
host = "0.0.0.0"
port = 10104
