#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

source {{pkg.svc_config_path}}/render-certs.sh

exec {{pkgPathFor "core/nginx"}}/bin/nginx -c {{pkg.svc_config_path}}/nginx.conf
