#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

source {{pkg.svc_config_path}}/render-certs.sh

exec nginx -c {{pkg.svc_config_path}}/nginx.conf
