// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interservice/cfgmgmt/request/root.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacf7481aca99c62, []int{0}
}

func (m *VersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionInfo.Unmarshal(m, b)
}
func (m *VersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionInfo.Marshal(b, m, deterministic)
}
func (m *VersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionInfo.Merge(m, src)
}
func (m *VersionInfo) XXX_Size() int {
	return xxx_messageInfo_VersionInfo.Size(m)
}
func (m *VersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VersionInfo proto.InternalMessageInfo

type Health struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacf7481aca99c62, []int{1}
}

func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (m *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(m, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

type Organizations struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Organizations) Reset()         { *m = Organizations{} }
func (m *Organizations) String() string { return proto.CompactTextString(m) }
func (*Organizations) ProtoMessage()    {}
func (*Organizations) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacf7481aca99c62, []int{2}
}

func (m *Organizations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organizations.Unmarshal(m, b)
}
func (m *Organizations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organizations.Marshal(b, m, deterministic)
}
func (m *Organizations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organizations.Merge(m, src)
}
func (m *Organizations) XXX_Size() int {
	return xxx_messageInfo_Organizations.Size(m)
}
func (m *Organizations) XXX_DiscardUnknown() {
	xxx_messageInfo_Organizations.DiscardUnknown(m)
}

var xxx_messageInfo_Organizations proto.InternalMessageInfo

type SourceFQDNS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *SourceFQDNS) Reset()         { *m = SourceFQDNS{} }
func (m *SourceFQDNS) String() string { return proto.CompactTextString(m) }
func (*SourceFQDNS) ProtoMessage()    {}
func (*SourceFQDNS) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacf7481aca99c62, []int{3}
}

func (m *SourceFQDNS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceFQDNS.Unmarshal(m, b)
}
func (m *SourceFQDNS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceFQDNS.Marshal(b, m, deterministic)
}
func (m *SourceFQDNS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceFQDNS.Merge(m, src)
}
func (m *SourceFQDNS) XXX_Size() int {
	return xxx_messageInfo_SourceFQDNS.Size(m)
}
func (m *SourceFQDNS) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceFQDNS.DiscardUnknown(m)
}

var xxx_messageInfo_SourceFQDNS proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VersionInfo)(nil), "chef.automate.domain.cfgmgmt.request.VersionInfo")
	proto.RegisterType((*Health)(nil), "chef.automate.domain.cfgmgmt.request.Health")
	proto.RegisterType((*Organizations)(nil), "chef.automate.domain.cfgmgmt.request.Organizations")
	proto.RegisterType((*SourceFQDNS)(nil), "chef.automate.domain.cfgmgmt.request.SourceFQDNS")
}

func init() {
	proto.RegisterFile("interservice/cfgmgmt/request/root.proto", fileDescriptor_bacf7481aca99c62)
}

var fileDescriptor_bacf7481aca99c62 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x40, 0xb7, 0x22, 0x91, 0x22, 0xf8, 0x09, 0x45, 0x70, 0x4b, 0x06, 0x27, 0x71, 0x13, 0x11,
	0x5d, 0x14, 0x29, 0x38, 0xb8, 0xa5, 0xf1, 0x9a, 0x1e, 0x98, 0x5c, 0xbd, 0x5c, 0x1c, 0xfc, 0x7a,
	0xa9, 0xd4, 0xd5, 0xfd, 0x3d, 0xde, 0x53, 0x4b, 0x8c, 0x02, 0x9c, 0x80, 0x5f, 0xe8, 0xc0, 0xb8,
	0xd6, 0x07, 0x1f, 0xc4, 0x30, 0x3c, 0x33, 0x24, 0x31, 0x4c, 0x24, 0xba, 0x67, 0x12, 0x9a, 0x2f,
	0x5c, 0x07, 0xad, 0xb6, 0x59, 0x28, 0x58, 0x01, 0x7d, 0xa7, 0x60, 0x31, 0xea, 0x51, 0xd0, 0xa3,
	0x50, 0x95, 0x6a, 0x7a, 0x05, 0x4e, 0x48, 0xf1, 0x18, 0x5b, 0xaa, 0x26, 0xaa, 0x38, 0x80, 0x7d,
	0x48, 0x57, 0xcd, 0x54, 0x79, 0x66, 0x6f, 0x23, 0xbe, 0xad, 0x20, 0xc5, 0x34, 0x90, 0x35, 0x65,
	0x76, 0xb0, 0xbf, 0xec, 0x4e, 0xf5, 0x76, 0x73, 0x5b, 0x7b, 0x94, 0x2e, 0x37, 0xda, 0x51, 0x30,
	0x43, 0xcb, 0xfc, 0x5a, 0xc6, 0xf6, 0x68, 0xfe, 0x6d, 0x36, 0xc5, 0x77, 0x71, 0xf5, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0xed, 0x81, 0xe0, 0xcd, 0x00, 0x00, 0x00,
}
