export enum FilterOptions {
  Platform = 'Platform',
  PlatformVersion = 'Platform Version',
  Domain = 'Domain',
  Tag = 'Tag',
  ChefVersion = 'Chef Version',
  IpAddress = 'IP address',
  Ip6Address = 'IP 6 address',
  MacAddress = 'MAC address',
  Uptime = 'Uptime',
  MemoryTotal = 'Memory Total',
  VirtualizationSystem = 'Virtualization System',
  VirtualizationRole = 'Virtualization Role',
  KernelRelease = 'Kernel Release',
  KernelVersion = 'Kernel Version',
  Hostname = 'Hostname',
  Timezone = 'Timezone',
  LastCheckInTime = 'Last Check In Time',
  DMIsystemManufacturer = 'DMI System Manufacturer',
  DMIsystemSerialNumber = 'DMI System Serial Number',
  CloudProvider = 'Cloud Provider'
}

export const FilterableOptions = [
  FilterOptions.Platform,
  FilterOptions.PlatformVersion,
  FilterOptions.Domain,
  FilterOptions.Tag,
  FilterOptions.ChefVersion,
  FilterOptions.IpAddress,
  FilterOptions.Ip6Address,
  FilterOptions.MacAddress,
  FilterOptions.Uptime,
  FilterOptions.MemoryTotal,
  FilterOptions.VirtualizationSystem,
  FilterOptions.VirtualizationRole,
  FilterOptions.KernelRelease,
  FilterOptions.KernelVersion,
  FilterOptions.Hostname,
  FilterOptions.Timezone,
  FilterOptions.LastCheckInTime,
  FilterOptions.DMIsystemManufacturer,
  FilterOptions.DMIsystemSerialNumber,
  FilterOptions.CloudProvider
]