#!{{pkgPathFor "core/bash"}}/bin/bash
#
curlOpts="-sS --fail --max-time 2"
curlOpts="$curlOpts --cert {{pkg.svc_config_path}}/service.crt"
curlOpts="$curlOpts --key {{pkg.svc_config_path}}/service.key"
curlOpts="$curlOpts --cacert {{pkg.svc_config_path}}/root_ca.crt"
curlOpts="$curlOpts --resolve automate-builder-api:{{cfg.service.port}}:127.0.0.1"
curlOpts="$curlOpts --noproxy automate-builder-api"

# shellcheck disable=SC2086
output=$({{pkgPathFor "core/curl"}}/bin/curl $curlOpts "https://automate-builder-api:{{cfg.service.port}}/v1/status")
res=$?
if [ "0" != "$res" ]; then
    echo "health check curl command returned exit code ${res}:"
    echo "$output"
    exit 2
fi
