# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
    - 'coverage/**/*.*'
    - 'src/assets/chef-ui-library/**/*.*'
# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2

  # Disallows
  no-warn: 2
  no-debug: 2
  no-important: 2
  no-trailing-whitespace: 2
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 2
  property-sort-order:
    - 2
    - order:
        - display
        - margin
      ignore-custom-properties: true

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
