#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

export ZONEINFO={{pkgPathFor "core/glibc"}}/share/zoneinfo

# If the gateway was shut down cleanly the socket should be cleaned up. We'll
# make sure it's gone before we start.
{{~#if cfg.service.null_backend_sock}}
[ -e "{{cfg.service.null_backend_sock}}" ] && rm -f "{{cfg.service.null_backend_sock}}"
{{~ else}}
[ -e "{{pkg.svc_var_path}}/null_backend.sock" ] && rm -f "{{pkg.svc_var_path}}/null_backend.sock"
{{~/if}}

# Start our service
exec automate-gateway serve --config {{pkg.svc_config_path}}/config.toml
