@startuml
skinparam backgroundColor white
skinparam arrowColor black
skinparam activityBackgroundColor "#fdb714" 
skinparam activityBorderColor	#3e4346
skinparam activityDiamondBackgroundColor	#fdb714
skinparam activityDiamondBorderColor	#3e4346	
skinparam activityStartColor	black	
skinparam activityEndColor	black	
skinparam activityBarColor	black
skinparam actorBackgroundColor	#fdb714
skinparam actorBorderColor	#3e4346
skinparam usecaseBackgroundColor	#fdb714
skinparam usecaseBorderColor	#3e4346
skinparam classBackgroundColor	#fdb714
skinparam classBorderColor	#3e4346
skinparam objectBackgroundColor	#fdb714
skinparam objectBorderColor	#3e4346
skinparam packageBackgroundColor	#fdb714
skinparam packageBorderColor	#3e4346
skinparam stereotypeCBackgroundColor	#ADD1B2
skinparam stereotypeABackgroundColor	#A9DCDF
skinparam stereotypeIBackgroundColor	#B4A7E5
skinparam stereotypeEBackgroundColor	#EB937F	
skinparam componentBackgroundColor	#fdb714
skinparam componentBorderColor	#3e4346
skinparam componentInterfaceBackgroundColor	#fdb714
skinparam componentInterfaceBorderColor	#3e4346
skinparam noteBackgroundColor	#FBFB77
skinparam noteBorderColor	#3e4346
skinparam stateBackgroundColor	#fdb714
skinparam stateBorderColor	#3e4346
skinparam stateStartColor	black
skinparam stateEndColor	black
skinparam sequenceDividerBackgroundColor	#EEEEEE
skinparam sequenceGroupBackgroundColor	#EEEEEE
skinparam sequenceLifeLineBackgroundColor	white
skinparam sequenceLifeLineBorderColor	#3e4346
skinparam sequenceParticipantBackgroundColor	#fdb714
skinparam sequenceParticipantBorderColor	#3e4346
skinparam sequenceBoxLineColor	#3e4346
skinparam sequenceBoxBackgroundColor	#DDDDDD
skinparam agentBackgroundColor #fbd714
skinparam agentBorderColor #3e4346
@enduml