#!{{pkgPathFor "core/bash"}}/bin/bash

# restrict permissions of keys for postgres usage
chmod 0600 {{pkg.svc_config_path}}/service.crt
chmod 0600 {{pkg.svc_config_path}}/service.key
chmod 0600 {{pkg.svc_config_path}}/root_ca.crt
