#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

export HOME={{pkg.svc_var_path}}

# Start pg-sidecar-service
exec pg-sidecar-service serve --config {{pkg.svc_config_path}}/config.toml
