#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

export HOME={{pkg.svc_var_path}}

source {{pkg.svc_path}}/hooks/reconfigure

# Start pg-sidecar-service
exec pg-sidecar-service serve --config {{pkg.svc_config_path}}/config.toml
