[mlsa]
accept = false

[tls]
key_contents =""
cert_contents = ""
root_cert_contents = ""

[logger]
format = "text"
level = "info"

[service]
host = "localhost"
port = 10153

[authz]
host = "localhost"
port = 10130

[secrets]
host = "localhost"
port = 10131

[local-user]
host ="localhost"
port = 10127


[storage]
database = "chef_infra_proxy"
user = "chef_infra"
