[automate]
  root_ca = "../../pkg/testfiles/certs/test_root_ca.pem"

  [[automate.ips]]
    ip = "198.51.100.0"
    public_key = "../../pkg/testfiles/certs/test_a2_public_key_1.pem"
    private_key = "../../pkg/testfiles/certs/test_a2_private_key_1.pem"

[chef_server]
  root_ca = "../../pkg/testfiles/certs/test_root_ca.pem"

  [[chef_server.ips]]
    ip = "198.51.100.2"
    public_key = "../../pkg/testfiles/certs/test_cs_public_key_1.pem"
    private_key = "../../pkg/testfiles/certs/test_cs_private_key_1.pem"

[opensearch]
  root_ca = "../../pkg/testfiles/certs/test_root_ca.pem"
  admin_public_key = "../../pkg/testfiles/certs/test_admin_cert.pem"
  admin_private_key = "../../pkg/testfiles/certs/test_admin_key.pem"
  [[opensearch.ips]]
    ip = "198.51.100.4"
    public_key = "../../pkg/testfiles/certs/test_os_public_key_1.pem"
    private_key = "../../pkg/testfiles/certs/test_os_private_key_1.pem"

  [[opensearch.ips]]
    ip = "198.51.100.5"
    public_key = "../../pkg/testfiles/certs/test_os_public_key_2.pem"
    private_key = "../../pkg/testfiles/certs/test_os_private_key_2.pem"

  [[opensearch.ips]]
    ip = "198.51.100.6"
    public_key = "../../pkg/testfiles/certs/test_os_public_key_3.pem"
    private_key = "../../pkg/testfiles/certs/test_os_private_key_3.pem"