[automate]
  root_ca = "../../../../lib/config/testdata/root-ca.pem"

  [[automate.ips]]
    ip = "10.1.0.130"
    public_key = "/home/ubuntu/certs/automate1.pem"
    private_key = "/home/ubuntu/certs/automate1-key.pem"

[chef_server]
  root_ca = "/home/ubuntu/certs/root-ca.pem"

  [[chef_server.ips]]
    ip = "10.1.0.16"
    public_key = "/home/ubuntu/certs/cs1.pem"
    private_key = "/home/ubuntu/certs/cs1-key.pem"

[postgresql]
  root_ca = "/home/ubuntu/certs/root-ca.pem"

  [[postgresql.ips]]
    ip = "10.1.0.141"
    public_key = "/home/ubuntu/certs/pg1.pem"
    private_key = "/home/ubuntu/certs/pg1-key.pem"

  [[postgresql.ips]]
    ip = "10.1.1.190"
    public_key = "/home/ubuntu/certs/pg2.pem"
    private_key = "/home/ubuntu/certs/pg2-key.pem"

  [[postgresql.ips]]
    ip = "10.1.2.130"
    public_key = "/home/ubuntu/certs/pg3.pem"
    private_key = "/home/ubuntu/certs/pg3-key.pem"

[opensearch]
  root_ca = "/home/ubuntu/certs/root-ca.pem"
  admin_public_key = "/home/ubuntu/certs/os-admin.pem"
  admin_private_key = "/home/ubuntu/certs/os-admin-key.pem"
  [[opensearch.ips]]
    ip = "10.1.0.176"
    public_key = "/home/ubuntu/certs/os1.pem"
    private_key = "/home/ubuntu/certs/os1-key.pem"

  [[opensearch.ips]]
    ip = "10.1.1.125"
    public_key = "/home/ubuntu/certs/os2.pem"
    private_key = "/home/ubuntu/certs/os2-key.pem"

  [[opensearch.ips]]
    ip = "10.1.2.247"
    public_key = "/home/ubuntu/certs/os3.pem"
    private_key = "/home/ubuntu/certs/os3-key.pem"