[global]
  [global.v1]
    [global.v1.external]
      [global.v1.external.postgresql]
        [global.v1.external.postgresql.auth]
          [global.v1.external.postgresql.auth.password]
            [global.v1.external.postgresql.auth.password.superuser]
              username = "admin"
              password = "admin"
            [global.v1.external.postgresql.auth.password.dbuser]
              username = "admin"
              password = "admin"
      [global.v1.external.opensearch]
        [global.v1.external.opensearch.auth]
          scheme = "basic_auth"
          [global.v1.external.opensearch.auth.basic_auth]
            username = "admin"
            password = "admin"
