#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

export A2_SVC_DB_USER="dex"

{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}


chmod 0600 {{pkg.svc_config_path}}/service.crt
chmod 0600 {{pkg.svc_config_path}}/service.key
chmod 0600 {{pkg.svc_config_path}}/root_ca.crt

source {{pkg.svc_config_path}}/run_environment.sh
mkdir -p {{pkg.svc_var_path}}/etc

render-template config.yml {{pkg.svc_var_path}}/etc/config.yml --conf {{pkg.svc_config_path}}/config.json

if [ ! -f /hab/.skip_migration ]; then
  echo "/hab/.skip_migration does not exist, running pg-helper command $(pwd)/$0 at $LINENO"
  pg-helper ensure-service-database "{{cfg.storage.database}}"
  pg-helper create-extension "{{cfg.storage.database}}" "pgcrypto"
else 
  echo "/hab/.skip_migration does exist, skipping pg-helper"  
fi


# cleanup static path
rm -rf "{{pkg.svc_static_path}}/web"

exec secrets-helper exec \
  --watch \
  --optional-secret userconfig.ldap_password \
  --optional-secret userconfig.msad_password \
  -- dex serve {{pkg.svc_var_path}}/etc/config.yml
