#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

# From memcache 1.5.19:
#
# - ssl_chain_cert:      certificate chain file in PEM format
# - ssl_key:             private key, if not part of the -ssl_chain_cert
# - ssl_keyformat:         private key format (PEM, DER or ENGINE) PEM default
# - ssl_verify_mode:     peer certificate verification mode, default is 0(None).
#                        valid values are 0(None), 1(Request), 2(Require)
#                        or 3(Once)
# - ssl_ciphers:         specify cipher list to be used
# - ssl_ca_cert:         PEM format file of acceptable client CA's
#
ssl_options="ssl_key={{pkg.svc_config_path}}/service.key"
ssl_options="${ssl_options},ssl_chain_cert={{pkg.svc_config_path}}/service.crt"
ssl_options="${ssl_options},ssl_ca_cert={{pkg.svc_config_path}}/root_ca.crt"
ssl_options="${ssl_options},ssl_verify_mode=2"
ssl_options="${ssl_options},ssl_ciphers=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!EXPORT"

memcacheArgs="-m {{cfg.service.mem_limit}} -l 127.0.0.1 -p {{cfg.service.port}}"
memcacheArgs="$memcacheArgs --enable-ssl"
memcacheArgs="$memcacheArgs -o $ssl_options"
# shellcheck disable=SC2086
exec memcached $memcacheArgs
