---
grpc: "127.0.0.1:10153"
log-level: "info"
log-format: "text"

tls:
  cert_path: /hab/svc/infra-proxy-service/config/service.crt
  key_path: /hab/svc/infra-proxy-service/config/service.key
  root_ca_path: /hab/svc/infra-proxy-service/config/root_ca.crt

pg_url: "postgresql://postgres@127.0.0.1:5432/infra_proxy_test?sslmode=disable"
database: chef_infra_proxy
migrations-path: /src/components/infra-proxy-service/storage/postgres/migration/sql/
authz-address: "0.0.0.0:10130"
secrets-address: "0.0.0.0:10131"
