#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

if [ ! -f /hab/.skip_migration ]; then
  echo "/hab/.skip_migration does not exist, running pg-helper command $(pwd)/$0 at $LINENO"
  pg-helper ensure-service-database "{{cfg.storage.database}}"
  pg-helper create-extension "{{cfg.storage.database}}" "pgcrypto"
  pg-helper fix-permissions "{{cfg.storage.database}}"
else 
  echo "/hab/.skip_migration does exist, skipping pg-helper"  
fi

# cleanup old migration files
rm -rf "{{pkg.svc_static_path}}/schema"

exec report-manager-service serve --config {{pkg.svc_config_path}}/config.toml