# ======================== Elasticsearch Configuration =========================
# The es_yaml top level key contains whatever data will be written to elasticsearch.yml
#
[es_yaml]
  [es_yaml.bootstrap]
    memory_lock = false  #true

  [es_yaml.cluster]
    name = "chef-insights"
    [es_yaml.cluster.routing.allocation.disk.watermark]
      low = "85%"
      high = "90%"
      flood_stage = "95%"

  [es_yaml.discovery.zen]
    minimum_master_nodes = 1

  [es_yaml.http]
    port = 9200

  [es_yaml.transport.tcp]
    port = 9300

  [es_yaml.indices.recovery]
    max_bytes_per_sec = "250mb"

  [es_yaml.network]
    host = "0.0.0.0"

  [es_yaml.node]
    max_local_storage_nodes = 1

  [es_yaml.path]
    data = "/hab/svc/automate-backend-elasticsearch/data"
    logs = "/hab/svc/automate-backend-elasticsearch/logs"

  [es_yaml.opendistro_security]
    enable_snapshot_restore_privilege = true
    check_snapshot_restore_write_privileges = true
    # These are the dns we use for our generated certificates. Override if you're generating your own
    nodes_dn = [ "CN=chefnode,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.authcz]
      admin_dn = [ "CN=chefadmin,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.ssl]
      [es_yaml.opendistro_security.ssl.http]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"

        enabled_ciphers = [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        ]
        enabled_protocols = [
          "TLSv1.2"
        ]

      [es_yaml.opendistro_security.ssl.transport]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"
        enforce_hostname_verification = false

# Fill these in in your user.toml to override automatic SSL Cert generation
[opendistro_ssl]

# root pem cert that signed the two cert/key pairs below
rootCA = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAIfV5Bn17FIuMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0xOTA1MjkxOTIxMTRaFw0yOTA1MjYxOTIxMTRaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAK9Wz4TINtE4AwUx56YGIE+8ceeJn3A3PAiH
HCukwxEQ5bMloRejCMDftMttW7dcMYVAJIc5eST2UdNgDsknsI+pXA0pYsII9Zdh
UNzHisAISn+NGReQ6WgrkbbZe3sMZ2Cer+uBfJC9xaefw+u9u8Y2lDCIAcpgQ6dB
1aZM4GQgQk5187ur2wIAzyH9R1GI+YkiUgp0qNly1yqk/wZXKvZStVlmVcOylg/M
YSkD290kZLmfyzhstfUIGXH7bN5VYuM6K08wn1yqLDDVMlkGDVN7jpaiaS+b0goq
Cc1QkDpcU4Kt7ddU4bnHP9XmY0htGbfW7vR8+5028suj+kuGb5UCAwEAAaNQME4w
HQYDVR0OBBYEFLY+eWTH4oNaN6Ki2zbkimO68WLWMB8GA1UdIwQYMBaAFLY+eWTH
4oNaN6Ki2zbkimO68WLWMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AATwZZuDw3lb7EC7/14EWR5kke4mGpn4PVpsPffV2/6xkh7JGFjJUPA+s37VtJ1F
UoulL7lVsNcGYpuZdwnjEDcBfbtyoiz54z50DkuuSI8JREiXjq3ITw0UUCGjMR2X
dbA1KYSWTDM28YuJeUCgK0u8tB1kdygcORHMLmR0KG7NJvFFXv5iT34XpdgSEZWC
L9wNRG5gHo42r/Wfhk6N+BZm3Cax7glsbotCGUq+8fzxHp0EzE6Bu8+GhCnISNHG
4kYI75qH04NxFr8n0rBFK5crOHFbvoKnk8JALFkyJ/8U83fRkN2acXdwQ7Kv4bg6
0VblmlLHieFP9mO6eDqNRGA=
-----END CERTIFICATE-----"""

# Certificate used for admin actions against https://9200
admin_cert   = """-----BEGIN CERTIFICATE-----
MIIDRTCCAi0CCQCq5i+UCFN1WzANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMTkw
NTI5MTkyODMyWhcNMjkwNTI2MTkyODMyWjBkMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALO59Y+JGsZxkAW8+3ZsZ5YO/LehWnn3yhIci4cEnEnZ
2c6qRMUBtmNRZfIcJcckgE8VhzOlFf4mTevLC3aqhe6Ec1+DBo7xSiOn3CVkqp3Y
yAmS2g0+zTl0civJXh80nY6kZvqvdZRF9vmGwZFO9M8B68SnjO/ShhYxaguOxC0m
P/4zVvcMXALrQxzz8BhPC1g8jQriBkkXU8rkv7F0zOrQqFJvR3u3cvnJzlXNrUTs
yfxpyQ/8yux8FY9xHCPvO0WDQ9zig5bt+ILUceHpGw/IXi3039iOSjYRN2z/Ez9u
NYYl7RJs6PkNxZWk8nDa8j6z8ilpjkAOuACelpWALVcCAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAnpO0cqxcnHrEEY5mFibsU6SvRLTB0yEo+ED5mrKPDaoSkfV1zbQv
zPzqZM27FLu/GZP4HiuUwPn0/ZYv/RsppxFNwGFIzXuZUd9sYiB2rcnG9OAc7AIo
c+xTrwTeTGzgUFzY8FEfs9EaPC/FDEahaUHuwByiWZExVpaHJF6Cg5RsStI6T4kP
TH5jfy8/fsQu4xwDqlczPiqm0PSWfEVyryWMzHbsWvFgNjj07kaIbMbqZjtifYnw
1Bk2Nr/MVJ7KeacjNEGlLmpPGLY8z+miMlMEepClqulW/6Ptwy2PyvGs8Sj5sqFH
B9qwJW30GBvjZj5eEgyE9waea3v4oVrcPA==
-----END CERTIFICATE-----"""

# the private key associated with the above pem cert
admin_key    = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzufWPiRrGcZAF
vPt2bGeWDvy3oVp598oSHIuHBJxJ2dnOqkTFAbZjUWXyHCXHJIBPFYczpRX+Jk3r
ywt2qoXuhHNfgwaO8Uojp9wlZKqd2MgJktoNPs05dHIryV4fNJ2OpGb6r3WURfb5
hsGRTvTPAevEp4zv0oYWMWoLjsQtJj/+M1b3DFwC60Mc8/AYTwtYPI0K4gZJF1PK
5L+xdMzq0KhSb0d7t3L5yc5Vza1E7Mn8ackP/MrsfBWPcRwj7ztFg0Pc4oOW7fiC
1HHh6RsPyF4t9N/Yjko2ETds/xM/bjWGJe0SbOj5DcWVpPJw2vI+s/IpaY5ADrgA
npaVgC1XAgMBAAECggEAYowBwJ195/fW776K54lTVy2KlqnLsXsT+tBaFUOK6teg
HTixkpB40IaObq3ObR5vmG2Gf+PyZjPcoADqnTutSnanyGRQ0Uouy9Q72ukSwJBg
RxeVppOb9fgKrkWw7U1tYwx0Rtq0jwO6A2JHewSfKW61N1Rj7BA0Y7Deo825dcNL
Bkq/bsauM/PUjw43+5NVMtAkhKqVyTERgUnof89dBqKjYj9EAjueW0StxgHgq3nv
TnNhnn+deUN3juUGPaTNrxXldTNsqajmQDeDY8lKtNZn3ab4TSc1EEq0lwVP0qIp
RPHo/EkwBir5kDDEr4jtbvSLAYFFXZAbiV3/xkozWQKBgQDe36jRi7e3T3Lq2o3Y
556v3v2uazl3ZrHgdGc+OEHwSWEeOe63flV/LX/iJVD6xHq+djM15RwHGVaIgCEG
dEoeKXBuB6rMjSyUjWvot6RBrtI1xJWHp1sbIw7m1Rx4uPFQTIBkczeXT/LcPy33
wnhKJxTc7A1MtPjeQZSMwmKeKwKBgQDOcIv59reuVdUUvTmNHWNHDFMguncX2foP
DRbJZFc1ozZDNoZuSF9KeBVIhLHolZ0W8PYGKAp9gUHMgNuSNy2inRz0X2b2UAlb
hBFOOB7GbZWdqii2CREk3K7qUPzy/cHvPaCs9bwd2j06xU3nPNp18LmFMyDdSBwI
kZlDzfyDhQKBgQCfIIGgW2locElUdYchfv5GA6iMh/IX1jLaV0H/opsxvLKiqipO
yNyyWQIdrRcMdIxOwIX/zP0d9HFcNF9gBFeHAX9MkBzav1E9H1wUZEnau79KtHku
yca6sWVKWo5hg2qIMpbZIYpndqWnq1ReuXK5Pv4eXkuAoRWvWpN9jKxs0QKBgQDM
vRhGJycScrPqZqS+TIgafaGwEt5sPFXhOYUA5VAMtTrqvBflJkfDjoblLh1X45Ix
n3cQsgN9Z4U/cgjR4YGUBigiQL/Xx5cQOVIEdmonN6WsAYdwyltDaM7dOsczovIE
+OTyxJ/2J2yUbfwOOu8bC0yjSwrsC0kqQmRzt8YZFQKBgQCws4tgpiRMGeTD8q0F
sCW8cUnXm4VlpWWLNlP2B+9Sylr1N7cnIeRmE3IRX0KQSHf2xZcUgw3S+M5EPH5C
0zn2opFyG2Ylv/81NuYJFuq4wuzyvYbg6zkeWrqS9OTznj6gZAu0q4++4o4rEBZb
Hze/nF2wg5KZauv0eOy64chmkA==
-----END PRIVATE KEY-----"""

# Certificate used for intracluster ssl on port 9300
ssl_cert    = """-----BEGIN CERTIFICATE-----
MIIDRDCCAiwCCQCq5i+UCFN1WjANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMTkw
NTI5MTkyODE5WhcNMjkwNTI2MTkyODE5WjBjMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxETAPBgNVBAMMCGNoZWZub2RlMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAs3/oNBNb2X8OIyXM7rsTk9uiJFP7+HGrFvFHtXPcTDW1
JDs3q0D74/VWUR+3jtv+4ycEsEw4xZd0LUivRBuRS8ppju7mTdBYu4faUT97lbDj
N2/EiAXHn5K2fMd8LlJQsIrsmS21JhdfO/U0tTHxDvPUs2LmUZPxikRyHoGkrwXP
I+YIJh6Lh+MBgTYj76zAP1RP6orkWgN72rOOdaWNrfoXQ0aRU7uI55AbukB/0HOj
wjs1bk9ynWzkxMZkRVh/IM/weSGpXX23VHacMy1hjokC/DBroLiNf/e52+E0A5zV
5D64iNr1edhqNuECSwQxET9uID0Ng2Loh9ElK13DvwIDAQABMA0GCSqGSIb3DQEB
CwUAA4IBAQAKv3jUlljcnDXXXLSdzB/vbfbPXhuBltR93jTEfFAhgsP/Q41tGxaC
MYAXJZtnnmxdZ4Dl+pX8/eQ3ZMmwC0xAGia44qf08468KwfIndQbr8HicAOc20US
RV+WZWwJYi1fiWOdofIGF4s0ribcXq7vM95KWN8nBodiW/ckPnDOlrLb8J/z6mLv
5Cl3DWGfo0nQr0RxL/ZDYl72+2ZuWXy6d1Ps1NHB/u9AHtTG8nK39Th7KCUjutwA
QeGqnZ9y5OSkTAaVVtyFrnK8BLmBNrfmzedKjc8sXBsI6Ue2tgMHe2ISDBPYY06m
oq6fKOM1/QcmyFKgkDr04EGUbuh3ibUc
-----END CERTIFICATE-----"""

# the private key associated with the above pem cert
ssl_key     = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCzf+g0E1vZfw4j
JczuuxOT26IkU/v4casW8Ue1c9xMNbUkOzerQPvj9VZRH7eO2/7jJwSwTDjFl3Qt
SK9EG5FLymmO7uZN0Fi7h9pRP3uVsOM3b8SIBcefkrZ8x3wuUlCwiuyZLbUmF187
9TS1MfEO89SzYuZRk/GKRHIegaSvBc8j5ggmHouH4wGBNiPvrMA/VE/qiuRaA3va
s451pY2t+hdDRpFTu4jnkBu6QH/Qc6PCOzVuT3KdbOTExmRFWH8gz/B5IaldfbdU
dpwzLWGOiQL8MGuguI1/97nb4TQDnNXkPriI2vV52Go24QJLBDERP24gPQ2DYuiH
0SUrXcO/AgMBAAECggEAa1Aj9cZBGmXggNjfjTZg/PvJEyj2slDatYuokG3lHdba
JgAVRxhBv8Z0RWnN5uXVm94+6luXcWIbvdr/lZtZoVMxCpf/LjRKaEtPFVX7v8GS
BhmXCK9T6i3fVfg5YMQro3BbBTUTYOOGNyVgzpc+A+94kYqmIc1uEXjcNSrS1yOD
2TtHd84ZCMvEXg7wFqbR4jLhpKvvynX7RM9bfCTQqpsmlZgcSrHHJXYQEfr35ZeC
V3ZFwuvjgDoJL2/tdkeX7YRylrma/H9pIS5wbhCdr2CcOx0iJMkTPlyCEhEvDzwy
+5jrddeEQqptUciD9wE4qR/JhMGEbUngeq4lcD1jQQKBgQDn3GSKb/sLaaLBPAJA
e0Zu0FlT7ziEjhs1ZdUnGCBG4zZgPRqH39NWCFeTILmgSauTZE23ME5+eXrBaSQM
K4iNGzyEnKNBhSes3ITT4X63gjkb2EifIcI39trOb5GhqEZntewqFJJGNanBeFz5
lBiBNRXvOEunYpX3NI8ykvRtnwKBgQDGL/hmuZ+/c2aGXagY6rAUumG6oJOtIl7M
u8ueArSlzbMKG/vYMiTisBdgspjBxJul0h0n1OqtYPsc4uv+WfrsWYhQLt7R6ewk
0mn6/eSOdmfbuJRISROk+8agC7AJHK1PAnY8r3/tVFr8AmIZZ6opcDVD8RBa03H2
GQfwofi14QKBgG4hUBw1jl/gYC86qrMoGs9d5WAp24WS3jeh0/oKyqIBIH3b6DMr
zH0r3zUCMUmCVJ3g4c0mg9ItL3KY10d0khq8GiW/JQhlD/Bamjjt/bt6flfMhsoX
ReJBPbMaaWkIvdBbJ/7g4I26xZQg8MCXaIBOz8ldywmJmUPfUjkqdjFvAoGADW4I
viVL/vQ5+Vb1YiLdJbpvju78stnGZMdBCAcU6Ltkq4Wz7jWPrFDUdLgFg/PnvDfd
w+o4sOEGgzGZXlYIm+WBSDW04bKhTul3RwvXZhP9+7SpT7CsBR0Om5/PIP7xe44m
JvyZhaKWu8cJkMEmlcJFycHXIuB7M3sEv7iqGuECgYB/CNwS2MovDeyt8o9Ka6he
5pnnSqf0b/an1Tc8rUt3mpv9mDCHRgV7WQc+lZ0f1UHHf/EWXCU2ahfBNQuoLUDi
fQFkUxCFH9wYmMoeBvZJYUBtYSiOoVdN1lEIDwjpTc2WnVwB1iuXCB5laVXSPaKI
xtbi72PUsHClCAhAS0tv9w==
-----END PRIVATE KEY-----"""

# Runtime settings for jvm.options and the systemd service
[runtime]
  max_open_files = ""
  max_locked_memory = ""
  es_startup_sleep_time = ""
  # This config variable becomes the value of ES_JAVA_OPTS.
  # Note: JVM values for -Xms and -Xmx are auto calculated in the run hook.
  # Any value defined here will override the calculation in the hook.
  es_java_opts = ""
  # It looks like the default NewRatio is ignored when setting UseConcMarkSweepGC
  # https://bugs.openjdk.java.net/browse/JDK-8153578. If we set it explicitly we
  # can get the expected behavior
  new_ratio = 2

# This section contains any settings that need to applied on startup for opendistro.
# Any values put under this hash will be rendered into yaml and applied with
# securityadmin.sh. These should be your basic admin credentials, as long term you
# can manage your creds outside of habitat with securityadmin.sh.

[opendistro_auth]
  admin_username = "admin"
  admin_password = "admin"
  dashboard_username = "kibana"
  dashboard_password = "kibana"
