# ======================== Elasticsearch Configuration =========================
# The es_yaml top level key contains whatever data will be written to elasticsearch.yml
#
[es_yaml]
  [es_yaml.bootstrap]
    memory_lock = false  #true

  [es_yaml.cluster]
    name = "chef-insights"
    [es_yaml.cluster.routing.allocation.disk.watermark]
      low = "85%"
      high = "90%"
      flood_stage = "95%"

  [es_yaml.discovery.zen]
    minimum_master_nodes = 1

  [es_yaml.http]
    port = 9200

  [es_yaml.transport.tcp]
    port = 9300

  [es_yaml.indices.recovery]
    max_bytes_per_sec = "250mb"

  [es_yaml.network]
    host = "0.0.0.0"

  [es_yaml.node]
    max_local_storage_nodes = 1

  [es_yaml.path]
    data = "/hab/svc/automate-ha-elasticsearch/data"
    logs = "/hab/svc/automate-ha-elasticsearch/logs"

  [es_yaml.opendistro_security]
    enable_snapshot_restore_privilege = true
    check_snapshot_restore_write_privileges = true
    # These are the dns we use for our generated certificates. Override if you're generating your own
    nodes_dn = [ "CN=chefnode,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.authcz]
      admin_dn = [ "CN=chefadmin,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.ssl]
      [es_yaml.opendistro_security.ssl.http]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"

        enabled_ciphers = [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        ]
        enabled_protocols = [
          "TLSv1.2"
        ]

      [es_yaml.opendistro_security.ssl.transport]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"
        enforce_hostname_verification = false

# Runtime settings for jvm.options and the systemd service
[runtime]
  max_open_files = ""
  max_locked_memory = ""
  es_startup_sleep_time = ""
  # This config variable becomes the value of ES_JAVA_OPTS.
  # Note: JVM values for -Xms and -Xmx are auto calculated in the run hook.
  # Any value defined here will override the calculation in the hook.
  es_java_opts = ""
  # It looks like the default NewRatio is ignored when setting UseConcMarkSweepGC
  # https://bugs.openjdk.java.net/browse/JDK-8153578. If we set it explicitly we
  # can get the expected behavior
  new_ratio = 2

# This section contains any settings that need to applied on startup for opendistro.
# Any values put under this hash will be rendered into yaml and applied with
# securityadmin.sh. These should be your basic admin credentials, as long term you
# can manage your creds outside of habitat with securityadmin.sh.

[opendistro_auth]
  admin_username = "admin"
  admin_password = "admin"
  dashboard_username = "kibana"
  dashboard_password = "kibana"

# Fill these in in your user.toml to override automatic SSL Cert generation
[opendistro_ssl]

# root pem cert that signed the two cert/key pairs below
rootCA = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAIj3HLZyQC91MA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yNDAxMjkwNTIxMzVaFw0yNzAxMjgwNTIxMzVaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBALaUMyEddXwP0xb9HTEBwDLjRD9gyB5GMnC7
W/DfbtmEfRTS9o0son8oexZekG/JpU+D8J70S5KGUnum3moi8BayqXPQvBbN8lLg
gcQko2UWGBJdGGue6EW/xNSiYcmOyLBCpo/nI59HG2BWwMaORMR2E1TOpLYCK0mT
ANySL8ZXAt0+bB8MK2eJurJNF2jnKMkZPJEVOIx0m0wPfZt4gQQiOVMFbbfcBy9v
VFt1o0wuuZTgvMnJreFL0hOk4hF3SbwWcqf8ebtnYualvK5xcSYxz7ElqfrWlVJg
IMbA9gQWePCl+RDAi+hnrl6lNBzFwZcKlpCfRaZmbWEHq959JLsCAwEAAaNQME4w
HQYDVR0OBBYEFBQFdNMCJScFIxEk5nnwIcJjtbQdMB8GA1UdIwQYMBaAFBQFdNMC
JScFIxEk5nnwIcJjtbQdMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AA5OqOI9k7n2Mt0n9VDL87WNsHIHLfAxholVwI3zPshntExk6S2D5O/52Ox8t+QP
b+6FUZyTKjfx9SMYLtgQ9e2URRQ5vAXyZ6d2GKRZulw3X7axVH+eVcP+US41f7jA
mRqKyzCX30v6at7u5+xCJC7RVuV8ivXMyImkZW/XtpMbfwqXNXsx+QkgJpepJbaM
JTf9gG/B8qNhbkMDlm/LIQyNpfpy0k0U/2fDFmTf6GBv5FtBtNh9sEkoIZYxkXBq
6j/zQTNlAm8gv27+f8QYI6dqFsjmqYovSD6p4RxnBSP66GsAtc+2f8VWHUDjZMuS
3CXRXq9NEjNn3bNhLJ2G99g=
-----END CERTIFICATE-----"""
# Certificate used for admin actions against https://9200
admin_cert = """-----BEGIN CERTIFICATE-----
MIIDZDCCAkygAwIBAgIJAMCjyUR56UmiMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yNDAxMjkwNTIxMzVaFw0yNzAxMjgwNTIxMzVaMGQxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzESMBAGA1UEAwwJY2hlZmFkbWluMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzbeojqdOeRY1kxS6+ivUhS5eMoLvmJfHIPQI
CkKmuwzQL2sqFrJA/sGjMk++TKTEaL56e8jUWJlFybUfsms9+WUdX7vHssciZmng
H4kNEdr7Y1WCqCnS3ia9LVvXSernuqJQjUK2T6IX6PKwxjPxJ4tz3fE4j75dM1Pw
aLcJThmUWGffHvFoI5tMLd/+RDTu5CR+T/BvJ+wM99oQNcnBBAnPUft33+QsEc4q
Qg/0bFEcx7feYzimnmdlp9cH2r/7u1/Ht1lRYRF39alJ0cli9tjRWC2THmkO/V07
gsxCZ7SN5yazhfl30MKi7FxsR3ypKH8c7672xBDVrnvr5qm7RQIDAQABoxgwFjAU
BgNVHREEDTALggljaGVmYWRtaW4wDQYJKoZIhvcNAQELBQADggEBAK3rgFGSxLyU
YRKR3uF//0/g2AiOLVLRozeMkZWYPHRd4RjNTtfWcpEtis2bZ98Nd+QMYLhQ9WvO
05SeApns9Tej39EJh7AY8vN6FWR8C3MkzU85intEOUMP8XXfWsUqz7Y4Qc6FIstw
T1IflONoj7v78g8i6dmlkhYoimjTUXwyJ1YW1n6xzKGD3j8YHZAhgHiNwcxAlBty
BFBM8ArEvrBiAbS9ZZpVMmGJwP2iO+g/CpebDgVTCbuX/xTkTTJwLWIjG182FGqA
hh8uFpVWBKAT3EXvrCv9otJ35BPY4hCQCUd7KhQmZdNe1emEHrSs/3NjIXLRRaQS
xB3gQgQe9Pk=
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
admin_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNt6iOp055FjWT
FLr6K9SFLl4ygu+Yl8cg9AgKQqa7DNAvayoWskD+waMyT75MpMRovnp7yNRYmUXJ
tR+yaz35ZR1fu8eyxyJmaeAfiQ0R2vtjVYKoKdLeJr0tW9dJ6ue6olCNQrZPohfo
8rDGM/Eni3Pd8TiPvl0zU/BotwlOGZRYZ98e8Wgjm0wt3/5ENO7kJH5P8G8n7Az3
2hA1ycEECc9R+3ff5CwRzipCD/RsURzHt95jOKaeZ2Wn1wfav/u7X8e3WVFhEXf1
qUnRyWL22NFYLZMeaQ79XTuCzEJntI3nJrOF+XfQwqLsXGxHfKkofxzvrvbEENWu
e+vmqbtFAgMBAAECggEAMTZkbmv7y9/SRTNKX5qopounITJNmxWEH5ABdGLpfAne
q9lZIkDWZ5tvLRQClFc+XUhkCMTMd72DAnP/9zDMjKLx2fsUFOKqihF9+k1RARp/
1Q2ZyhznQxnFW9qCsD4v3WgDGSgCcR531dRpEaFPaYRk3Y1dWJXTufm0o3hWE4aA
kjdNIqnJD0U4Ppi5r+5UncJuG0Cryf5yB/ldqlOms/yJ4LHHFBbr6IP49sA0r05V
Xx5eungKRP6pBwl/Ihk8V3rRfMsYuZNrgsZXBQ2S5GQG7YHZTqfa07vQHutu6QKT
2erPXgKa4xr72rgjphsfuAuiOMOW0kZkPzP8JM2HwQKBgQD/zq/qunMpyYYI/qzR
g0QalMaqASiJAaFqGQRHKVR8YKvrg00b7MaBbbbrNI8wdqKsTOm8QxYIVVgvqeB4
O66eKeWRJ0+fh539i9EdQUMfIOaBhcc4UwKm+3+tYdV4Uc6MlYai3mV2D6ld5Hgq
egfxb0LDb7osT0be13p7kzESTQKBgQDN31Cz/jpzoZkK0i0g68lnM2UU1/YPMFic
8+BOjnHrlnrC1gjbJthNeqaWXcm7HhgsIxeU96CyH8P34ghbPus/UOUmVp3vCb+u
scptwh8A9E2AfR5+1wHMPTF0ODkm0yfLn05V8JmkU6JARIlEm2mVnD8nXU9bKZ/1
YH0fUsIY2QKBgH5uIiYqZtblYli5vqKCdTuKArJthiJI6wVsPeAJ/lbG1NG/AHJn
0SiRGFIhlQ/H4tiz3uYMZixSOha8qFPkc4Z6gJsASes39Q8mdoE2Cz2sXiDwBKnC
5VGwhcckzoP8MtDq6jM/Jfh2/yeHzxh3XcunSOEdLG/P8uAasc+3zQ4VAoGBAMUB
H/8+Fr00NHmQarMILzDck6wAhWw/fWykS0+hLA6fb1Ym706Xu4FZDzTxBuxSfhsu
cZCR7mrFzwfUet6mNQPf64hmdreaAp2vcODbVEPbhJaiJJ6ILSY+oKZwbvBiO8C0
74d5t+zyQ19wtlK6zaznWd/XgOrhyDpNXS6uSSLxAoGBAMmDiHno/biDfvKpW6qJ
3d5GdgCVnbydi+HiRsWkkw756Bq44vWwGNxkoC/6gdQxwEWoHR8SE4LMjVal/w2W
gl6syWrIiy/FvIr6fJ/EdNtkJ/VHK8QdxAr0+XhYyBqiRQBiEbGpj2OG0F/A/KaS
jKLBN4IT6Ybyy8tGvRwZMDYs
-----END PRIVATE KEY-----"""
# Certificate used for intracluster ssl on port 9300
ssl_cert = """-----BEGIN CERTIFICATE-----
MIIDYjCCAkqgAwIBAgIJAMCjyUR56UmjMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yNDAxMjkwNTIxMzZaFw0yNzAxMjgwNTIxMzZaMGMxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzERMA8GA1UEAwwIY2hlZm5vZGUwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDH6+zyBliKTQbM9P4MgLEMfAs3WEqvhOme0HcJ
PD9VECGvFlWdNRkpHuFtyIxHJHcmhUqgNOW6xWNLBIVOg26S1303NJD8FjsHN8m9
wvjE6+z6eRVeKE5VFYgS6joKfjGu9u+4t73vDalusRYGvGRqW/w7UN5kmDQpyByO
GLfpsHDO/QeM6PAWEPbQp3irDGzcZoHX7COqgm/BrKLNkfW1fHRGQlfMx4BAKo+H
N+89vJHtW6AcMVAO4XcNx7qROXDq6k4QqkIhXjqxxv74Dhf5kp5BDZMtqjyR5K3j
qyeNqcvaSg9w2EH5KTqNA1/w7lHftaVCfYhZ4ItarSjt5vHvAgMBAAGjFzAVMBMG
A1UdEQQMMAqCCGNoZWZub2RlMA0GCSqGSIb3DQEBCwUAA4IBAQCYL1F140ADn2q0
W69hpWpA9my6Iep1ehHmfw+l2MzU2SOBJdFm7zu179T1dpPawwhYoIzdX4dgffqd
2VHCRUML9sEbklatfGZU4KDrK9I871ZyjT72YYxKH8sBeaXRd1fe5U8qSm8LW6A+
/HfG3G8fVKvr+diLIEHsc5ywwMVOrFQPMjx+nSpKqgvANdhF4WUdT0OWK7Y5LoGZ
4WcUpFly8lPF19mQkaWaZfu2j+R+vZ/Q2oRGxMUJMxdbXmETq09cLlSV/Ck6VwnV
sPWtJLzuQpsQFCkyqRpZ9TBegu6Lyerk1l/eQzrRqHXz7iabUfWwuOZVMB7DtcoN
qatc9Wk3
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
ssl_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDH6+zyBliKTQbM
9P4MgLEMfAs3WEqvhOme0HcJPD9VECGvFlWdNRkpHuFtyIxHJHcmhUqgNOW6xWNL
BIVOg26S1303NJD8FjsHN8m9wvjE6+z6eRVeKE5VFYgS6joKfjGu9u+4t73vDalu
sRYGvGRqW/w7UN5kmDQpyByOGLfpsHDO/QeM6PAWEPbQp3irDGzcZoHX7COqgm/B
rKLNkfW1fHRGQlfMx4BAKo+HN+89vJHtW6AcMVAO4XcNx7qROXDq6k4QqkIhXjqx
xv74Dhf5kp5BDZMtqjyR5K3jqyeNqcvaSg9w2EH5KTqNA1/w7lHftaVCfYhZ4Ita
rSjt5vHvAgMBAAECggEAQRB+Z/I6xJ/286NUPxtvA6InQFbiz6bRJZew9fd+oR+D
5ui86lIKo0Bim4kmZkzu3kGJHQS6M4PkIdkRzZCm3vF01g+sk+5kPaAhbznSHryt
voLDuoYhoD1GsOk8BIg3gTrqn9Jk5TUsDFNj2MNdZuQS/fb+ufxzFZoD+RcAW/Q2
ICibVrDKGCj2oTAi06G4Or/7Co0lAF3ikQFYMVPkvMfQm0bjDTBk7DRujAYRWsvZ
fuCPb3fMRtgUzXP7MLXGhNp3i7tsfeYgayEoZm01j1YLlOjgGOusHOoFiysvIFyG
qazBuBeVRzcEwC6fR4+yg2nPMLehKTfLRSCnMxsogQKBgQDpJvStT0HcNDoICfU6
IfTAIaXgNFUR/eEl1/vunyuGxwlfi9Od82sdf6wy23s2z/IZttm94VqfQ70ozrcg
o0aA1xV6uwY18VNJlv1EApmuNBV2fvLko45OIkUUax499vQGw/NzF/XAJb2Tatzq
As5Vvv9UDZi6E7prUM4aij23rwKBgQDbg1IEetbsBc9o4xvdlSX7uVJX8AsdLbSj
MDSk7hoe/LOpVE9S2vCaPneJHEPBXD2qXMU81f3JHWDTgMTPZ3Ak/RlRkuO96ngc
t+rBMWxxlyoKFrdHC3+G980t5AkZH7Kya8pn0Hk0jnypJbwHjbWqmAla1pfAZqoA
iHlU5P65wQKBgBXllbctKWdP9F9K6CAUjlL5FgYPhCnTaTDPrxaDFmhrCwNRM4ez
E81Kb1a7bEACmZ82oA6IOqWYjAxoFaTYEMgK6zaCmBu61XKk3pZjlCFbPOTLGW7F
uZi2+Tvor4dsSRDVmGinyGnKYZqVv7eumchNztcLC9v1/F0V0rWFZDR7AoGAKUB4
fVcIZLqCy9dCOVX6GWAuVVBLBmS8eZ5phkUoq4IZ0UyCy7NRW+s5U474PLI09HsS
peghFVZsB9M/KSrrLEhUJbxRCDOz9tGpUD0VgBNEVzkFoFhM0vRmnqUoAIywbE9N
bk0DOhk83By3RUQgS7repy+EvSeN8yOyiX2vUQECgYEApELVJh88qNSYBBa0m/bE
pwUphnTU/ZyBWA2xJ9UcWrSFIEzRislSdwwMPwbgRld9Hq1zIBbgp/Ww3sQsfRif
NV4JphK+5DCaH7jTXW1+GsJkiaj13BXt2rKnk+7FD2X43AYYHd1ILP0Ln8mTVwz/
wTKclbz+1olA1Gbbn9L4flM=
-----END PRIVATE KEY-----"""
