#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

{{#if cfg.disable ~}}
while true
do
  sleep 60
done

exit 0
{{~else}}

{{#if cfg.runtime.es_startup_sleep_time ~}}
export ES_STARTUP_SLEEP_TIME={{cfg.runtime.es_startup_sleep_time}}
{{/if ~}}

export OPENSEARCH_PATH_CONF="{{pkg.svc_config_path}}"

export TMPDIR="{{pkg.svc_var_path}}/tmp"
export ES_TMPDIR="{{pkg.svc_var_path}}/tmp"
export ES_PATH_CONF="{{pkg.svc_config_path}}"
JDK_PKG_PATH=`HAB_LICENSE=accept-no-persist hab pkg path chef/automate-openjdk`
export JDK_PKG_PATH

# Initialize the secrets keystore and trusted certs ca keystore
source {{pkg.svc_config_path}}/init_keystore
source {{pkg.svc_config_path}}/init_ca

# cp {{pkg.path}}/os/config/certificates/* {{pkg.svc_config_path}}/

echo "JDK PATH"
echo $JDK_PKG_PATH
# /hab/pkgs/core/bash/5.0.16/20200305233030/bin/sh 





hab pkg exec chef/automate-openjdk keytool -printcert -sslserver s3.amazonaws.com:443 -rfc >> {{pkg.svc_config_path}}/aws-s3.crt

hab pkg exec chef/automate-openjdk keytool -noprompt -importcert -alias s3.amazonaws.com -keystore {{pkg.svc_var_path}}/ca.jks -storepass changeit -file {{pkg.svc_config_path}}/aws-s3.crt

hab pkg exec chef/automate-openjdk keytool -noprompt -importcert -alias s3.amazonaws.com -keystore $JDK_PKG_PATH/lib/security/cacerts -storepass changeit -file {{pkg.svc_config_path}}/aws-s3.crt

#exec opensearch
#hab pkg exec core/bash {{pkg.path}}/os/plugins/opensearch-security/tools/securityadmin.sh -h localhost -p 9201 -cacert {{pkg.svc_config_path}}/root-ca.pem -cert {{pkg.svc_config_path}}/admin.pem -key {{pkg.svc_config_path}}/admin-key.pem -nhnv -icl -cd {{pkg.svc_config_path}}/securityconfig
#hab pkg exec core/bash {{pkg.path}}/os/opensearch-tar-install.sh

#chmod +x {{pkg.path}}/os/plugins/opensearch-security/tools/securityadmin.sh


#Generate securityadmin_demo.sh
# echo "#!/bin/bash" | tee securityadmin_demo.sh > /dev/null 

# chmod +x {{pkg.path}}/os/securityadmin_demo.sh
# hab pkg exec core/bash {{pkg.path}}/os/securityadmin_demo.sh
exec opensearch


{{~/if}}
