listen_address = "{{cfg.service.listen_address}}"
port = {{cfg.service.port}}
log_level = "{{cfg.log.level}}"

{{#if cfg.gather_logs.staging_dir ~}}
staging_dir = "{{cfg.gather_logs.staging_dir}}"
{{/if ~}}
