#!{{pkgPathFor "core/bash"}}/bin/bash

exec service-health 127.0.0.1 {{cfg.service.port}} "license-control-service" \
 {{pkg.svc_config_path}}/service.crt \
 {{pkg.svc_config_path}}/service.key \
 {{pkg.svc_config_path}}/root_ca.crt
