#!/bin/bash

set -ex

automate-ctl stop
chef-server-ctl stop

## This package contains data with es2 indices in it so we test the reindex
## code path
## see https://chefio.atlassian.net/wiki/spaces/ENG/pages/455147533/Migrating+A1+Elasticsearch+data
## and https://drive.google.com/open?id=1dtdt8kRXywDAE9G03WX7a3mWQoAWsYY1
DATA_PACKAGE_RELEASE="20190530183952"
HAB_LICENSE=accept-no-persist hab pkg install "devchef/a1-migration-data-full/0.0.1/$DATA_PACKAGE_RELEASE" --channel unstable

echo "waiting for migration data to sync..."

until [[ -f /etc/delivery/.a1-migration-data-ready ]]; do
  # print dots?
  ls /etc/delivery || true
  sleep 1
done

echo "done!"

# In case our a1 artifact has an old license in it
[[ ! -d /var/opt/delivery/license ]] && mkdir -p /var/opt/delivery/license
cp /a1-migration/delivery.license /var/opt/delivery/license/delivery.license

# loading the data can leave us with incorrect rabbit password among other
# things, reconfigure fixes it
automate-ctl reconfigure --chef-license=accept-no-persist

# reconfigure doesn't start statistics service tho?
automate-ctl start

chef-server-ctl reconfigure
chef-server-ctl start

function wait_for_healthy_status() {
  for attempt in {1..4}; do
    if curl -skL "$1" && curl -skL "$1" | grep pong && curl -skL "$1" | grep -v fail; then
      break
    fi

    if [ $attempt -eq 4 ]; then
      echo "Timed out waiting for healhty status for $1"
      exit 1
    fi

    sleep $(( attempt**attempt ))
  done
}

# Wait for A1 and Chef server to come up healthy
wait_for_healthy_status https://localhost/api/_status
wait_for_healthy_status https://localhost/_status
