#!{{pkgPathFor "core/bash"}}/bin/bash

if output=$(curl --max-time 2 -k --fail --silent --show-error "https://{{sys.ip}}:{{cfg.ssl_port}}/api/_status"); then
  exit 0
else
  echo "$output"
  exit 2
fi
