#!{{pkgPathFor "core/bash"}}/bin/bash
exec 2>&1

echo "Reloading Nginx configuration"

exec hab pkg exec chef/openresty-noroot openresty \
  -c "{{pkg.svc_config_path}}/nginx.conf" \
  -p "{{pkg.svc_var_path}}" \
  -s reload
