#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}
if [ ! -f /hab/.skip_migration ]; then
  pg-helper ensure-service-database "chef_cereal_service"
fi


exec cereal-service serve --config {{pkg.svc_config_path}}/config.json
