#!/bin/bash

document "automate_load_balancer_integration" <<DOC
  Runs some integration tests for automate-load-balancer
DOC
automate_load_balancer_integration() {

  local target=${1:-"https://127.0.0.1"}
  local output

  install_if_missing core/curl curl
  install_if_missing core/jq-static jq
  if ! output=$(curl --http2 -vk "$target" 2>&1); then
    log_error "non-zero exit code from curl: ${output}"
    return 1
  fi
  if ! grep -q "ALPN: server accepted h2" <<< "${output}"; then
    log_error "server did NOT accept to use HTTP/2"
    return 1
  fi

  log_line "/api/v0/status responds correctly"
  local status api_token
  api_token="$(get_admin_token)"
  status="$(curl -fsS --insecure -H "api-token: ${api_token}" "${target}/api/v0/status")"
  jq -ne --argjson status "$status" '$status.ok' || return 1
}
