#!/bin/bash

document "datafeed_start_service" <<DOC
  Build and start the local data-feed-service
DOC
function datafeed_start_service() {
  build components/data-feed-service
  start_deployment_service
  chef-automate dev deploy-some $HAB_ORIGIN/data-feed-service
}

document "datafeed_build" <<DOC
  Build components required for data-feed-service demo
DOC
function datafeed_build() {
  rm results/*

  components=("data-feed-service")
  for component in "${components[@]}"; do
    if ! build components/"$component"; then
      log_line "${RED}ERROR:${NC} Unable to compile component '$component'"
      return 1
    fi
  done
}

document "datafeed_quick_build" <<DOC
  Build components required for data-feed-service demo
DOC
function datafeed_quick_build() {
  rm results/*

  components=("data-feed-service")
  for component in "${components[@]}"; do
    if ! NO_INSTALL_DEPS=1 build components/"$component"; then
      log_line "${RED}ERROR:${NC} Unable to compile component '$component'"
      return 1
    fi
  done
  (cd components/data-feed-service && make hab_test)
}


document "datafeed_init_integration_tests" <<DOC
  Start all services so that data feed service's integration tests can run
DOC
function datafeed_init_integration_tests() {
  start_all_services
}

document "datafeed_run_integration_tests" <<DOC
  Run the data feed service's integration tests
DOC
function datafeed_run_integration_tests() {
  chef-automate config patch components/data-feed-service/integration_test/patch.toml
  api_token=$(get_admin_token)
  export AUTOMATE_API_TOKEN="${api_token}"
  export AWS_REGION="${AWS_REGION}"
  export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
  export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
  go_test -v github.com/chef/automate/components/data-feed-service/integration_test/...
}