#!/bin/bash

document "datafeed_start_service" <<DOC
  Build and start the local data-feed-service
DOC
function datafeed_start_service() {
  build components/data-feed-service
  start_deployment_service
  chef-automate dev deploy-some $HAB_ORIGIN/data-feed-service
}

document "datafeed_build" <<DOC
  Build components required for data-feed-service demo
DOC
function datafeed_build() {
  rm results/*

  components=("data-feed-service")
  for component in "${components[@]}"; do
    if ! build components/"$component"; then
      log_line "${RED}ERROR:${NC} Unable to compile component '$component'"
      return 1
    fi
  done
}

document "datafeed_quick_build" <<DOC
  Build components required for data-feed-service demo
DOC
function datafeed_quick_build() {
  rm results/*

  components=("data-feed-service")
  for component in "${components[@]}"; do
    if ! NO_INSTALL_DEPS=1 build components/"$component"; then
      log_line "${RED}ERROR:${NC} Unable to compile component '$component'"
      return 1
    fi

  done
}
