#!/bin/bash
#
# Helper methods specific for the nodemanager-service

document "nodemanager_cloud_scans_integration" <<DOC
  Runs the nodemanager scan jobs for aws and azure
DOC
function nodemanager_cloud_scans_integration() {
  go_test -v ./components/nodemanager-service/tests/cloud...
}

document "nodemanager_nodes_scans_integration" <<DOC
  Runs the nodemanager scan jobs for nodes
DOC
function nodemanager_nodes_scans_integration() {
  go_test -v ./components/nodemanager-service/tests/nodes...
}