#!/bin/bash
#
# Helper methods specific for the sample-data-service

document "start_sample_data_service" <<DOC
  Build and start the local sample-data-service
DOC
function start_sample_data_service() {
  install_if_missing core/jq-static jq
  install_if_missing core/grpcurl grpcurl

  build components/sample-data-service/
  start_deployment_service
  chef-automate dev deploy-some $HAB_ORIGIN/sample-data-service --with-deps
}

document "enable_sample_data_service" <<DOC
  Enable the sample-data-service
DOC
function enable_sample_data_service() {
  check_if_deployinate_started || return 1
  printf "[deployment.v1.svc]\n products = [\"sample-data\"]\n" > /tmp/enable_sample_data_patch.toml
  chef-automate config patch /tmp/enable_sample_data_patch.toml
}
