#!{{pkgPathFor "core/bash"}}/bin/bash

curlOpts="-sS --fail --max-time 2"
curlOpts="$curlOpts --resolve automate-builder-api-proxy:{{cfg.service.port}}:127.0.0.1"
curlOpts="$curlOpts --noproxy automate-builder-api-proxy"
curlOpts="$curlOpts --cacert {{pkg.svc_config_path}}/root_ca.crt"
curlOpts="$curlOpts --cert {{pkg.svc_config_path}}/service.crt"
curlOpts="$curlOpts --key {{pkg.svc_config_path}}/service.key"

# shellcheck disable=SC2086
output=$(curl $curlOpts https://automate-builder-api-proxy:{{cfg.service.port}} 2>&1)
res=$?
if [[ "$res" != "0" ]] ; then
    echo "health check curl command failed with exit code $res:"
    echo "$output"
    exit 2
fi
