#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

mkdir -p "{{pkg.svc_var_path}}/nginx"
chown -R hab:hab "{{pkg.svc_config_path}}" "{{pkg.svc_data_path}}" "{{pkg.svc_var_path}}"

exec {{pkgPathFor "core/nginx"}}/bin/nginx -c {{pkg.svc_config_path}}/nginx.conf
