# NOTE(ssd) 2018-07-25: These two are not exposed in public-facing
# configuration as changing them would break everything.
fips_enabled = false
ip_mode = "ipv4"

[network]
port=9090
listen_ip="0.0.0.0"

[log]
level = "info"
rotation_max_bytes = 104857600
rotation_max_files = 10
rotation_max_megabytes = 100
max_error_logs_per_second = 1000


[sql]
timeout = 5000
pool_init_size = 20
pool_max_size = 50
pool_queue_max = 20
pool_queue_timeout = 2000
user="automate-cs-ocid"
db_name="automate-cs-ocid"


[depsolver]
pool_max_size=5
pool_init_size=5
pool_queue_max=50
