# NOTE(ssd) 2018-07-25: These two are not exposed in public-facing
# configuration as changing them would break everything.
fips_enabled = false
ip_mode = "ipv4"
rails_env="production"
rack_env="production"
ruby_bin_directory="/hab/pkgs/core/ruby27/2.7.5/20220312100031/bin"
database_url="postgresql://automate@127.0.0.1:5432/automate-cs-ocid?sslmode=verify-ca&sslcert=/hab/svc/automate-postgresql/config/server.crt&sslkey=/hab/svc/automate-postgresql/config/server.key&sslrootcert=/hab/svc/automate-postgresql/config/root.crt"

[network]
port=9090
listen_ip="0.0.0.0"

[tls]
root_cert_contents = ""
cert_contents = ""
key_contents = ""

[log]
level = "info"
rotation_max_bytes = 104857600
rotation_max_files = 10
rotation_max_megabytes = 100
max_error_logs_per_second = 1000


[sql]
timeout = 5000
pool_init_size = 20
pool_max_size = 50
pool_queue_max = 20
pool_queue_timeout = 2000
user="automate-cs-ocid"
db_name="automate-cs-ocid"


[depsolver]
pool_max_size=5
pool_init_size=5
pool_queue_max=50