# NOTE(ssd) 2018-07-25: These two are not exposed in public-facing
# configuration as changing them would break everything.
fips_enabled = false
ip_mode = "ipv4"
rails_env="production"
rack_env="production"

[network]
port=10114
listen_ip="0.0.0.0"

[tls]
root_cert_contents = ""
cert_contents = ""
key_contents = ""

[log]
level = "info"
rotation_max_bytes = 104857600
rotation_max_files = 10
rotation_max_megabytes = 100
max_error_logs_per_second = 1000


[sql]
timeout = 5000
pool_init_size = 20
pool_max_size = 50
pool_queue_max = 20
pool_queue_timeout = 2000
user="automate-cs-ocid"
db_name="automate-cs-ocid"


[depsolver]
pool_max_size=5
pool_init_size=5
pool_queue_max=50

[ocid]
  secret_key_base = ""
  [ocid.chef_server_config]
    endpoint="https://127.0.0.1:443"
    superuser="pivotal"
    # By default the certificate verification is disabled for chef-server(erchef)
    # But if you have a valid certificate in your chef-server then you should
    # set it to: verify_peer
    ssl_verify_mode="verify_none"
  [ocid.v1.sys.ocid.oauth_application_config]
    [[ocid.v1.sys.ocid.oauth_application_config.oauth_applications]]