#!{{pkgPathFor "core/bash"}}/bin/bash

# *** WARNING ***
# Please put potentially long-running and/or complex operations in the run
# hook rather than the run init until the issue described in
#
# https://github.com/habitat-sh/habitat/issues/1973
#
# has been resolved.
#
# Currently, the Habitat `init` hook runs directly from the main loop of the
# Habitat supervisor. If these hooks hang or take too long to run, they can block
# execution of the supervisor.
#

# Make sure the old post-run sentinel file does not exist
source {{pkg.svc_config_path}}/health_check
[[ -f ${POST_RUN_SENTINEL} ]] && rm ${POST_RUN_SENTINEL}

mkdir -p {{pkg.svc_var_path}}/logs
mkdir -p {{pkg.svc_var_path}}/plugins
mkdir -p {{pkg.svc_var_path}}/tmp
