// Code generated by protoc-gen-policy. DO NOT EDIT.
// source: components/automate-gateway/api/iam/v2/rules.proto

package v2

import (
	policy "github.com/chef/automate/components/automate-gateway/api/authz/policy"
	request "github.com/chef/automate/components/automate-gateway/api/iam/v2/request"
)

func init() {
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/CreateRule", "auth:projects:{project_id}", "update", "POST", "/iam/v2/projects/{project_id}/rules", func(unexpandedResource string, input interface{}) string {
		if m, ok := input.(*request.CreateRuleReq); ok {
			return policy.ExpandParameterizedResource(unexpandedResource, func(want string) string {
				switch want {
				case "id":
					return m.Id
				case "project_id":
					return m.ProjectId
				case "name":
					return m.Name
				default:
					return ""
				}
			})
		}
		return ""
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/UpdateRule", "auth:projects:{project_id}", "update", "PUT", "/iam/v2/projects/{project_id}/rules/{id}", func(unexpandedResource string, input interface{}) string {
		if m, ok := input.(*request.UpdateRuleReq); ok {
			return policy.ExpandParameterizedResource(unexpandedResource, func(want string) string {
				switch want {
				case "id":
					return m.Id
				case "project_id":
					return m.ProjectId
				case "name":
					return m.Name
				default:
					return ""
				}
			})
		}
		return ""
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/GetRule", "auth:projects:{project_id}", "get", "GET", "/iam/v2/projects/{project_id}/rules/{id}", func(unexpandedResource string, input interface{}) string {
		if m, ok := input.(*request.GetRuleReq); ok {
			return policy.ExpandParameterizedResource(unexpandedResource, func(want string) string {
				switch want {
				case "id":
					return m.Id
				case "project_id":
					return m.ProjectId
				default:
					return ""
				}
			})
		}
		return ""
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/ListRulesForProject", "auth:projects:{id}", "get", "GET", "/iam/v2/projects/{id}/rules", func(unexpandedResource string, input interface{}) string {
		if m, ok := input.(*request.ListRulesForProjectReq); ok {
			return policy.ExpandParameterizedResource(unexpandedResource, func(want string) string {
				switch want {
				case "id":
					return m.Id
				default:
					return ""
				}
			})
		}
		return ""
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/DeleteRule", "auth:projects:{project_id}", "update", "DELETE", "/iam/v2/projects/{project_id}/rules/{id}", func(unexpandedResource string, input interface{}) string {
		if m, ok := input.(*request.DeleteRuleReq); ok {
			return policy.ExpandParameterizedResource(unexpandedResource, func(want string) string {
				switch want {
				case "id":
					return m.Id
				case "project_id":
					return m.ProjectId
				default:
					return ""
				}
			})
		}
		return ""
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/ApplyRulesStart", "auth:rules", "apply-rules-start", "POST", "/iam/v2/apply-rules", func(unexpandedResource string, input interface{}) string {
		return unexpandedResource
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/ApplyRulesCancel", "auth:rules", "apply-rules-cancel", "DELETE", "/iam/v2/apply-rules", func(unexpandedResource string, input interface{}) string {
		return unexpandedResource
	})
	policy.MapMethodTo("/chef.automate.api.iam.v2.Rules/ApplyRulesStatus", "auth:rules", "apply-rules-status", "GET", "/iam/v2/apply-rules", func(unexpandedResource string, input interface{}) string {
		return unexpandedResource
	})
}
