// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/automate-gateway/api/iam/v2/teams.proto

package v2

import (
	context "context"
	fmt "fmt"
	request "github.com/chef/automate/components/automate-gateway/api/iam/v2/request"
	response "github.com/chef/automate/components/automate-gateway/api/iam/v2/response"
	_ "github.com/chef/automate/components/automate-grpc/protoc-gen-policy/api"
	_ "github.com/chef/automate/components/automate-grpc/protoc-gen-policy/iam"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("components/automate-gateway/api/iam/v2/teams.proto", fileDescriptor_16a78463b445c3d8)
}

var fileDescriptor_16a78463b445c3d8 = []byte{
	// 766 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x80, 0xe5, 0xe8, 0xde, 0xdc, 0x76, 0xee, 0xed, 0x4f, 0x4e, 0x7b, 0x83, 0x15, 0x2a, 0x40,
	0x43, 0x0b, 0x55, 0xa0, 0xb6, 0x14, 0x58, 0x99, 0x05, 0x14, 0x10, 0xb0, 0x00, 0x16, 0x55, 0xbb,
	0xc9, 0x6e, 0x12, 0x0f, 0x89, 0xa5, 0x38, 0x9e, 0x7a, 0x26, 0x45, 0x05, 0x21, 0xa4, 0x48, 0x6c,
	0x82, 0x60, 0x01, 0x12, 0x48, 0x48, 0xac, 0x78, 0x06, 0x3f, 0x02, 0x2f, 0x00, 0x2f, 0xc0, 0x02,
	0x89, 0xd7, 0x40, 0x33, 0x4e, 0x63, 0x3b, 0xb6, 0x13, 0x97, 0x65, 0x7c, 0xbe, 0x89, 0xcf, 0x77,
	0x7e, 0x6c, 0xa3, 0x46, 0xdb, 0x73, 0x99, 0xd7, 0xa7, 0x7d, 0xc1, 0x4d, 0x32, 0x10, 0x9e, 0x4b,
	0x04, 0xdd, 0xe9, 0x10, 0x41, 0x9f, 0x92, 0x63, 0x93, 0x30, 0xc7, 0x74, 0x88, 0x6b, 0x1e, 0x35,
	0x4c, 0x41, 0x89, 0xcb, 0x0d, 0xe6, 0x7b, 0xc2, 0x03, 0xbd, 0xdd, 0xa5, 0x4f, 0x8c, 0x13, 0xda,
	0x20, 0xcc, 0x31, 0x1c, 0xe2, 0x1a, 0x47, 0x8d, 0xda, 0x46, 0xc7, 0xf3, 0x3a, 0x3d, 0xaa, 0x0e,
	0x92, 0x7e, 0xdf, 0x13, 0x44, 0x38, 0x5e, 0x7f, 0x7c, 0xae, 0x66, 0x15, 0xbc, 0x97, 0x4f, 0x0f,
	0x07, 0x94, 0x8b, 0xf8, 0x3d, 0x6b, 0x37, 0x0a, 0x9f, 0xe5, 0xcc, 0xeb, 0x73, 0x9a, 0x38, 0x7c,
	0x2b, 0xf3, 0xb0, 0xcf, 0xda, 0xa6, 0x8a, 0xb7, 0x77, 0x3a, 0xb4, 0xbf, 0xc3, 0xbc, 0x9e, 0xd3,
	0x3e, 0xce, 0x49, 0xfd, 0x34, 0xff, 0x20, 0x33, 0x49, 0xfd, 0x43, 0xe3, 0x5d, 0x05, 0xfd, 0xbd,
	0x2f, 0x73, 0x82, 0xaf, 0x1a, 0x5a, 0x7c, 0xe8, 0x70, 0x11, 0xfe, 0xba, 0x64, 0xe4, 0x55, 0xd3,
	0x98, 0x40, 0x7b, 0xf4, 0xb0, 0x76, 0xb9, 0x10, 0xc7, 0x19, 0xee, 0x0c, 0x03, 0xfd, 0x3f, 0x84,
	0xc8, 0x40, 0x74, 0x2d, 0x55, 0x84, 0x61, 0xa0, 0x97, 0xe1, 0x2f, 0x9f, 0x12, 0x7b, 0x14, 0xe8,
	0xff, 0xa2, 0x45, 0x87, 0xb8, 0x61, 0x60, 0x14, 0xe8, 0xab, 0xb0, 0x3c, 0xf9, 0x69, 0xf5, 0x1c,
	0x2e, 0x86, 0xdf, 0x7f, 0xbe, 0x2f, 0x6d, 0xc2, 0x52, 0xa2, 0xef, 0xcd, 0x35, 0xa8, 0x8c, 0x2f,
	0xb4, 0xa8, 0x20, 0xe1, 0x45, 0xf8, 0xa6, 0xa1, 0x7f, 0xee, 0x53, 0x75, 0x67, 0xd8, 0xcc, 0xcf,
	0x6e, 0x8c, 0x48, 0x87, 0xad, 0x02, 0x14, 0x67, 0xf8, 0xd9, 0x30, 0xd0, 0x2b, 0x68, 0x25, 0x32,
	0xb0, 0x9e, 0x3b, 0xf6, 0x8b, 0x84, 0xc6, 0x2a, 0x8a, 0xe5, 0x2d, 0xa3, 0xa3, 0x40, 0x5f, 0x81,
	0xa5, 0xe8, 0x5a, 0x87, 0x86, 0x2a, 0x06, 0x40, 0x42, 0xc5, 0x94, 0x70, 0x53, 0x87, 0x6a, 0xca,
	0x47, 0x45, 0xa4, 0x14, 0xba, 0xe3, 0x53, 0x22, 0xa8, 0xf2, 0x9a, 0x51, 0xf5, 0x88, 0x92, 0x6a,
	0xdb, 0xc5, 0x40, 0xce, 0xf0, 0x61, 0x46, 0x7f, 0x16, 0xa0, 0xdc, 0x56, 0x54, 0xba, 0x43, 0x00,
	0xab, 0x91, 0x55, 0x08, 0x29, 0xb1, 0x3a, 0x4e, 0xf6, 0xc8, 0xd2, 0xea, 0xcd, 0x2a, 0x4e, 0xb7,
	0xc9, 0xd2, 0xea, 0xf0, 0x4b, 0x43, 0xe8, 0x80, 0xd9, 0x05, 0xa4, 0x22, 0x6a, 0x8e, 0x54, 0x1c,
	0xe4, 0x0c, 0xbf, 0xd2, 0xf2, 0x7a, 0xb6, 0x00, 0xe5, 0x81, 0x62, 0x73, 0xba, 0x96, 0xf0, 0x0b,
	0x49, 0xe5, 0x77, 0xbd, 0x96, 0xd1, 0x38, 0x29, 0x79, 0xb6, 0x96, 0xd3, 0x3b, 0x69, 0xfa, 0x43,
	0x43, 0xe8, 0x2e, 0xed, 0xd1, 0xf9, 0xa6, 0x11, 0x35, 0xc7, 0x34, 0x0e, 0x72, 0x86, 0x5f, 0xce,
	0x10, 0xb5, 0x15, 0x5a, 0x44, 0x34, 0x24, 0xc3, 0x09, 0xad, 0x67, 0x4e, 0x68, 0x3d, 0x6f, 0x42,
	0xdf, 0x96, 0x50, 0x65, 0xbc, 0x2d, 0x8f, 0xa8, 0xdb, 0xa2, 0x3e, 0xef, 0x3a, 0x0c, 0x8c, 0xb9,
	0xab, 0x15, 0xc1, 0x52, 0xd8, 0x3c, 0x15, 0xcf, 0x19, 0xfe, 0x28, 0x3b, 0x7c, 0x06, 0xfd, 0x3f,
	0x25, 0x6e, 0x0d, 0x38, 0xf5, 0x93, 0x8f, 0x98, 0x2a, 0x5a, 0x4f, 0xca, 0x87, 0xcc, 0x28, 0xd0,
	0xd7, 0x01, 0x4e, 0x22, 0x07, 0xf2, 0x52, 0xf4, 0xc4, 0xb1, 0x40, 0x4f, 0x17, 0xc1, 0x54, 0xe7,
	0x9a, 0xe7, 0x60, 0x23, 0xbb, 0x14, 0x61, 0x1c, 0x5e, 0x97, 0xd0, 0xf2, 0xae, 0x6d, 0xc7, 0x72,
	0x86, 0x2b, 0xf9, 0x76, 0x49, 0x52, 0x96, 0xe2, 0x6a, 0x71, 0x98, 0x33, 0xfc, 0x79, 0xd6, 0xa4,
	0x4f, 0x96, 0x38, 0x6b, 0x00, 0xaa, 0xb0, 0x9e, 0xb4, 0x8f, 0x6d, 0xf3, 0x03, 0xbc, 0x91, 0xe7,
	0x6f, 0x11, 0xdb, 0x96, 0x73, 0xbf, 0x85, 0x2f, 0xcc, 0x2a, 0xc3, 0x18, 0x83, 0x4f, 0x25, 0x54,
	0xd9, 0xa3, 0xae, 0x77, 0x44, 0xe3, 0x05, 0x99, 0x31, 0x1e, 0x29, 0x78, 0xce, 0x78, 0x64, 0xf0,
	0x9c, 0xe1, 0x2f, 0xda, 0x9f, 0xee, 0x45, 0xaa, 0x2c, 0xb1, 0xdd, 0x78, 0x8c, 0xcf, 0xe7, 0x96,
	0xc5, 0x57, 0x79, 0xc8, 0xca, 0x6c, 0xe3, 0x8b, 0x33, 0x2b, 0x33, 0x21, 0xe1, 0x4d, 0xb4, 0x3b,
	0xfc, 0x9e, 0xe7, 0x87, 0x02, 0x05, 0x76, 0x27, 0x82, 0x8b, 0xed, 0x4e, 0x9c, 0xe7, 0x0c, 0x7f,
	0x88, 0xef, 0x4e, 0x98, 0x93, 0xda, 0x8b, 0xf4, 0xeb, 0x79, 0xbc, 0x3b, 0xd3, 0xcc, 0x28, 0xd0,
	0xd7, 0xa0, 0x72, 0x12, 0xd9, 0x4f, 0xbc, 0xe1, 0x62, 0xab, 0xa3, 0x8e, 0x85, 0xe6, 0xe1, 0x7b,
	0x7b, 0x6a, 0x75, 0xa6, 0xe3, 0xb7, 0x77, 0x9b, 0x37, 0x3b, 0x8e, 0xe8, 0x0e, 0x5a, 0x46, 0xdb,
	0x73, 0x4d, 0x69, 0x35, 0xf9, 0xba, 0x31, 0x8b, 0x7d, 0x70, 0xb5, 0xca, 0xea, 0xf3, 0xe6, 0xda,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x8b, 0xad, 0x06, 0x49, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TeamsClient is the client API for Teams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamsClient interface {
	ListTeams(ctx context.Context, in *request.ListTeamsReq, opts ...grpc.CallOption) (*response.ListTeamsResp, error)
	GetTeam(ctx context.Context, in *request.GetTeamReq, opts ...grpc.CallOption) (*response.GetTeamResp, error)
	CreateTeam(ctx context.Context, in *request.CreateTeamReq, opts ...grpc.CallOption) (*response.CreateTeamResp, error)
	UpdateTeam(ctx context.Context, in *request.UpdateTeamReq, opts ...grpc.CallOption) (*response.UpdateTeamResp, error)
	DeleteTeam(ctx context.Context, in *request.DeleteTeamReq, opts ...grpc.CallOption) (*response.DeleteTeamResp, error)
	GetTeamMembership(ctx context.Context, in *request.GetTeamMembershipReq, opts ...grpc.CallOption) (*response.GetTeamMembershipResp, error)
	AddTeamMembers(ctx context.Context, in *request.AddTeamMembersReq, opts ...grpc.CallOption) (*response.AddTeamMembersResp, error)
	RemoveTeamMembers(ctx context.Context, in *request.RemoveTeamMembersReq, opts ...grpc.CallOption) (*response.RemoveTeamMembersResp, error)
	GetTeamsForMember(ctx context.Context, in *request.GetTeamsForMemberReq, opts ...grpc.CallOption) (*response.GetTeamsForMemberResp, error)
}

type teamsClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamsClient(cc grpc.ClientConnInterface) TeamsClient {
	return &teamsClient{cc}
}

func (c *teamsClient) ListTeams(ctx context.Context, in *request.ListTeamsReq, opts ...grpc.CallOption) (*response.ListTeamsResp, error) {
	out := new(response.ListTeamsResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/ListTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeam(ctx context.Context, in *request.GetTeamReq, opts ...grpc.CallOption) (*response.GetTeamResp, error) {
	out := new(response.GetTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/GetTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) CreateTeam(ctx context.Context, in *request.CreateTeamReq, opts ...grpc.CallOption) (*response.CreateTeamResp, error) {
	out := new(response.CreateTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) UpdateTeam(ctx context.Context, in *request.UpdateTeamReq, opts ...grpc.CallOption) (*response.UpdateTeamResp, error) {
	out := new(response.UpdateTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/UpdateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) DeleteTeam(ctx context.Context, in *request.DeleteTeamReq, opts ...grpc.CallOption) (*response.DeleteTeamResp, error) {
	out := new(response.DeleteTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeamMembership(ctx context.Context, in *request.GetTeamMembershipReq, opts ...grpc.CallOption) (*response.GetTeamMembershipResp, error) {
	out := new(response.GetTeamMembershipResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/GetTeamMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) AddTeamMembers(ctx context.Context, in *request.AddTeamMembersReq, opts ...grpc.CallOption) (*response.AddTeamMembersResp, error) {
	out := new(response.AddTeamMembersResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/AddTeamMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) RemoveTeamMembers(ctx context.Context, in *request.RemoveTeamMembersReq, opts ...grpc.CallOption) (*response.RemoveTeamMembersResp, error) {
	out := new(response.RemoveTeamMembersResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/RemoveTeamMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeamsForMember(ctx context.Context, in *request.GetTeamsForMemberReq, opts ...grpc.CallOption) (*response.GetTeamsForMemberResp, error) {
	out := new(response.GetTeamsForMemberResp)
	err := c.cc.Invoke(ctx, "/chef.automate.api.iam.v2.Teams/GetTeamsForMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamsServer is the server API for Teams service.
type TeamsServer interface {
	ListTeams(context.Context, *request.ListTeamsReq) (*response.ListTeamsResp, error)
	GetTeam(context.Context, *request.GetTeamReq) (*response.GetTeamResp, error)
	CreateTeam(context.Context, *request.CreateTeamReq) (*response.CreateTeamResp, error)
	UpdateTeam(context.Context, *request.UpdateTeamReq) (*response.UpdateTeamResp, error)
	DeleteTeam(context.Context, *request.DeleteTeamReq) (*response.DeleteTeamResp, error)
	GetTeamMembership(context.Context, *request.GetTeamMembershipReq) (*response.GetTeamMembershipResp, error)
	AddTeamMembers(context.Context, *request.AddTeamMembersReq) (*response.AddTeamMembersResp, error)
	RemoveTeamMembers(context.Context, *request.RemoveTeamMembersReq) (*response.RemoveTeamMembersResp, error)
	GetTeamsForMember(context.Context, *request.GetTeamsForMemberReq) (*response.GetTeamsForMemberResp, error)
}

// UnimplementedTeamsServer can be embedded to have forward compatible implementations.
type UnimplementedTeamsServer struct {
}

func (*UnimplementedTeamsServer) ListTeams(ctx context.Context, req *request.ListTeamsReq) (*response.ListTeamsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeams not implemented")
}
func (*UnimplementedTeamsServer) GetTeam(ctx context.Context, req *request.GetTeamReq) (*response.GetTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeam not implemented")
}
func (*UnimplementedTeamsServer) CreateTeam(ctx context.Context, req *request.CreateTeamReq) (*response.CreateTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedTeamsServer) UpdateTeam(ctx context.Context, req *request.UpdateTeamReq) (*response.UpdateTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (*UnimplementedTeamsServer) DeleteTeam(ctx context.Context, req *request.DeleteTeamReq) (*response.DeleteTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedTeamsServer) GetTeamMembership(ctx context.Context, req *request.GetTeamMembershipReq) (*response.GetTeamMembershipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamMembership not implemented")
}
func (*UnimplementedTeamsServer) AddTeamMembers(ctx context.Context, req *request.AddTeamMembersReq) (*response.AddTeamMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeamMembers not implemented")
}
func (*UnimplementedTeamsServer) RemoveTeamMembers(ctx context.Context, req *request.RemoveTeamMembersReq) (*response.RemoveTeamMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTeamMembers not implemented")
}
func (*UnimplementedTeamsServer) GetTeamsForMember(ctx context.Context, req *request.GetTeamsForMemberReq) (*response.GetTeamsForMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsForMember not implemented")
}

func RegisterTeamsServer(s *grpc.Server, srv TeamsServer) {
	s.RegisterService(&_Teams_serviceDesc, srv)
}

func _Teams_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ListTeamsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/ListTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).ListTeams(ctx, req.(*request.ListTeamsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/GetTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeam(ctx, req.(*request.GetTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.CreateTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).CreateTeam(ctx, req.(*request.CreateTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.UpdateTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/UpdateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).UpdateTeam(ctx, req.(*request.UpdateTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).DeleteTeam(ctx, req.(*request.DeleteTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeamMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetTeamMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeamMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/GetTeamMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeamMembership(ctx, req.(*request.GetTeamMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_AddTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.AddTeamMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).AddTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/AddTeamMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).AddTeamMembers(ctx, req.(*request.AddTeamMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_RemoveTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.RemoveTeamMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).RemoveTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/RemoveTeamMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).RemoveTeamMembers(ctx, req.(*request.RemoveTeamMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeamsForMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetTeamsForMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeamsForMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.api.iam.v2.Teams/GetTeamsForMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeamsForMember(ctx, req.(*request.GetTeamsForMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Teams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chef.automate.api.iam.v2.Teams",
	HandlerType: (*TeamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTeams",
			Handler:    _Teams_ListTeams_Handler,
		},
		{
			MethodName: "GetTeam",
			Handler:    _Teams_GetTeam_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _Teams_CreateTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _Teams_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _Teams_DeleteTeam_Handler,
		},
		{
			MethodName: "GetTeamMembership",
			Handler:    _Teams_GetTeamMembership_Handler,
		},
		{
			MethodName: "AddTeamMembers",
			Handler:    _Teams_AddTeamMembers_Handler,
		},
		{
			MethodName: "RemoveTeamMembers",
			Handler:    _Teams_RemoveTeamMembers_Handler,
		},
		{
			MethodName: "GetTeamsForMember",
			Handler:    _Teams_GetTeamsForMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/automate-gateway/api/iam/v2/teams.proto",
}
