# If we have a config pointing to an specific host,
# lets use it, otherwise use the ipaddress of the server
host = "127.0.0.1"
port = "{{cfg.service.port}}"
log_level = "{{cfg.log.level}}"

[tls]
  cert_path = "{{pkg.svc_config_path}}/service.crt"
  key_path = "{{pkg.svc_config_path}}/service.key"
  root_ca_path ="{{pkg.svc_config_path}}/root_ca.crt"
