#!{{pkgPathFor "core/bash"}}/bin/bash
#
shopt -s extglob

exec 2>&1

# *** WARNING ***
# Please put potentially long-running and/or complex operations in the init hook rather
# than the run hook until the issue described in
#
# https://github.com/habitat-sh/habitat/issues/1973
#
# has been resolved.
# Currently, the Habitat `init` and `health_check` hooks run directly from the main loop
# of the Habitat supervisor. If these hooks hang or take too long to run, they can block
# execution of the supervisor.
#

{{#if cfg.disable ~}}
exit 0
{{~else}}

source {{pkg.svc_config_path}}/functions.sh

mkdir -p {{pkg.svc_config_path}}/conf.d
mkdir -p {{pkg.svc_var_path}}/pg_stat_tmp

# Auto-detect pg data in the root of svc_data_path, where older versions of this plan had it
if [[ -f "{{pkg.svc_data_path}}/PG_VERSION" ]]; then
  echo "PGDATA detected in the root of the data path ( {{pkg.svc_data_path}} ), relocating it to {{pkg.svc_data_path}}/pgdata13"
  mkdir -p {{pkg.svc_data_path}}/pgdata13
  # bash extended globbing can cleanly move everything under a subfolder http://www.linuxjournal.com/content/bash-extended-globbing
  mv {{pkg.svc_data_path}}/!(pgdata13) {{pkg.svc_data_path}}/pgdata13/
  chmod 0700 {{pkg.svc_data_path}}/pgdata13
else
  mkdir -p {{pkg.svc_data_path}}/pgdata13
fi

mkdir -p {{pkg.svc_data_path}}/archive

ensure_dir_ownership
ensure_key_ownership

if [[ ! -f "{{pkg.svc_data_path}}/pgdata13/PG_VERSION" ]]; then
  echo " Database does not exist, creating with 'initdb'"
    initdb -U {{cfg.superuser.name}} \
    -E utf8 \
    -D {{pkg.svc_data_path}}/pgdata13 \
    --locale POSIX \
    --data-checksums
fi

{{~/if}}
