#!{{pkgPathFor "core/bash"}}/bin/bash

set -e

exec 2>&1
export ZONEINFO={{pkgPathFor "core/glibc"}}/share/zoneinfo

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

{{#eachAlive bind.automate-es-gateway.members as |member|}}
{{~#if member.cfg.http-host}}
addNoProxy {{member.sys.ip}}
{{~/if}}
{{~/eachAlive}}

# Start our service
exec event-feed-service serve --config {{pkg.svc_config_path}}/config.toml
