#!{{pkgPathFor "core/bash"}}/bin/bash
echo "------------- starting opensearch sidecar -------------------"
HAB_LICENSE=accept-no-persist GEM_PATH={{pkg.path}}/lib/gems {{pkgPathFor "core/ruby30"}}/bin/ruby {{pkg.path}}/bin/opensearch_sidecar.rb
echo "-------------------------------------------------------------"