#!/usr/bin/env escript
%%! -name d_oauth_application@127.0.0.1

-define(SELF, 'd_oauth_application@127.0.0.1').
-define(TARGET, 'delivery@127.0.0.1').

main(Args) ->
    init_network(),
    [OauthAppName] = parse_args(Args),
    case rpc_call(?TARGET, deliv_oauth_application, delete, [OauthAppName]) of
        ok ->
            io:format("You have successfully deleted the OAuth Application: ~s~n", [OauthAppName]);
	{error, not_found} ->
	    perror(io:format("Error: OAuth Application ~s not found.~n", [OauthAppName]));
        {error, Why} ->
            perror(io:format("~nError: ~s~n~n", [Why]))
    end.

init_network() ->
    {ok, _} = net_kernel:start([?SELF, longnames]),
    true = erlang:set_cookie(node(), get_cookie()),
    pong = net_adm:ping(?TARGET).

parse_args([_OauthAppName] = Args) ->
    Args;
parse_args(Other) ->
    perror(io:format("Invalid Arguments: ~p~nUse option -h for help.~n", [Other])).

rpc_call(Node, Module, Function, Args) ->
    case rpc:call(Node, Module, Function, Args) of
        {badrpc, Reason} ->
            perror(io_lib:format("RPC call ~p:~p:~p:~p failed with error ~p~n",
                                 [Node, Module, Function, Args, Reason]));
        Res ->
            Res
    end.

perror(Msg) ->
    io:format(Msg),
    erlang:halt(1).

get_cookie() ->
    case os:getenv("ERL_COOKIE") of
        false ->
            'delivery';
        Cookie ->
            list_to_atom(Cookie)
    end.
