#!/usr/bin/env escript
%%! -name l_oauth_application@127.0.0.1

-define(SELF, 'l_oauth_application@127.0.0.1').
-define(TARGET, 'delivery@127.0.0.1').

main(_Args) ->
    init_network(),
    case rpc_call(?TARGET, deliv_oauth_application, list, []) of
	{ok, empty_list} ->
	    io:format("There are no OAuth Applications configured on the system. ~n");
        {ok, Output} ->
            io:format("OAuth Applications: ~n"),
	    lists:foreach(fun(A) -> io:format(" ~s~n", [element(3, A)]) end, Output);
        {error, Why} ->
            perror(io:format("~nError: ~s~n~n", [Why]))
    end.

init_network() ->
    {ok, _} = net_kernel:start([?SELF, longnames]),
    true = erlang:set_cookie(node(), get_cookie()),
    pong = net_adm:ping(?TARGET).

rpc_call(Node, Module, Function, Args) ->
    case rpc:call(Node, Module, Function, Args) of
        {badrpc, Reason} ->
            perror(io_lib:format("RPC call ~p:~p:~p:~p failed with error ~p~n",
                                 [Node, Module, Function, Args, Reason]));
        Res ->
            Res
    end.

perror(Msg) ->
    io:format(Msg),
    erlang:halt(1).

get_cookie() ->
    case os:getenv("ERL_COOKIE") of
        false ->
            'delivery';
        Cookie ->
            list_to_atom(Cookie)
    end.
