#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

# Set our IP address to whatever Habitat thinks it is
export AUTOMATE_SYS_IP={{sys.ip}}

# set the proxy environment variables so they're inherited by our sub-processes
# when they run
source {{pkg.svc_config_path}}/init_proxy

# ensure the backup repository is configured and has the correct permissions
source {{pkg.svc_config_path}}/init_backup

# Initialize the secrets store. This store is used fore shared secrets
# between services. The deployment-service sets up the base directory
# that shared secrets are stored in.
secrets-helper init

# Start our server
exec deployment-service serve {{pkg.svc_config_path}}/config.toml
