package constants

const (
	MIN_CPU_COUNT = 4
	MIN_CPU_SPEED = 2.0
	MIN_MEMORY    = 14

	HAB_FREE_DISK_BEFORE_DEP_A2      = 80
	HAB_FREE_DISK_BEFORE_DEP_CS      = 80
	HAB_FREE_DISK_BEFORE_DEP_PG      = 150
	HAB_FREE_DISK_BEFORE_DEP_OS      = 150
	HAB_FREE_DISK_BEFORE_DEP_BASTION = 150

	
	HAB_FREE_DISK_AFTER_DEP_A2      = 10
	HAB_FREE_DISK_AFTER_DEP_CS      = 10
	HAB_FREE_DISK_AFTER_DEP_PG      = 50
	HAB_FREE_DISK_AFTER_DEP_OS      = 50
	HAB_FREE_DISK_AFTER_DEP_BASTION = 30

	HAB_FREE_DISK_AFTER_DEP_A2_IN_PER      = 0.05
	HAB_FREE_DISK_AFTER_DEP_CS_IN_PER      = 0.05
	HAB_FREE_DISK_AFTER_DEP_PG_IN_PER      = 0.15
	HAB_FREE_DISK_AFTER_DEP_OS_IN_PER      = 0.15
	HAB_FREE_DISK_AFTER_DEP_BASTION_IN_PER = 0.15

	TMP_FREE_DISK_IN_GB  = 10
	TMP_FREE_DISK_IN_PER = 0.05

	ROOT_FREE_DISK_IN_GB  = 20
	ROOT_FREE_DISK_IN_PER = 0.20
)
