#!/bin/bash

set -eu

docker ps || true
free -m

# We've now seen cases where origin/main on the build hosts can get
# out of date. This causes us to build components unnecessarily.
# Fetching it here hopefully will prevent this situation.
echo "Fetching origin/main"
git fetch origin main

# DEBUGGING FOR RELENG
# Fetch the git tags to see if that addresses the weird smart build behavior for Habitat
git fetch --tags --force

# Count retries as BK annotations; don't make all jobs explode if the script
# is removed.
[[ -x "scripts/count_retries.sh" ]] && scripts/count_retries.sh
