#!/bin/bash

set -eu

# We've now seen cases where origin/master on the build hosts can get
# out of date. This causes us to build components unnecessarily.
# Fetching it here hopefully will prevent this situation.
echo "Fetching origin/master"
git fetch origin master

# DEBUGGING FOR RELENG
# Fetch the git tags to see if that addresses the weird smart build behavior for Habitat
git fetch --tags --force

# Count retries as BK annotations; don't make all jobs explode if the script
# is removed.
[[ -x "scripts/count_retries" ]] && scripts/count_retries

git diff-tree -s --pretty=%B HEAD | buildkite-agent annotate --context built-commit --style info
