#!{{pkgPathFor "core/bash"}}/bin/bash

set -Exeuo pipefail

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

echo 'Executing run hook'

source {{pkg.svc_config_path}}/functions.sh

write_local_conf

ensure_dir_ownership

{{#if svc.me.follower }}
wait_for_leader
echo 'Bootstrapping replica via pg_basebackup from leader'
rm -rf {{pkg.svc_data_path}}/pgdata/*
pg_basebackup --verbose --progress --wal-method=stream --checkpoint=fast --pgdata={{pkg.svc_data_path}}/pgdata --dbname='postgres://{{cfg.replication.name}}@{{svc.leader.sys.ip}}:{{svc.leader.cfg.port}}/postgres'
{{/if}}

#cp {{pkg.svc_config_path}}/recovery.conf {{pkg.svc_data_path}}/pgdata/recovery.conf
cp {{pkg.svc_config_path}}/standby.signal {{pkg.svc_data_path}}/pgdata/standby.signal
echo "Starting PostgreSQL"

{{#if cfg.wal_archive.enable }}
echo "INFO: Write Ahead Log archive_mode is enabled - archive files located in: {{cfg.wal_archive.path}}"
{{/if}}

{{#if cfg.pg_dump.enable }}
echo "INFO: The cluster_backup() function will save backups to: {{cfg.pg_dump.path}}"
echo "INFO: The Backup/Restore documentation covers how to call this function."
{{/if}}

export PGDATA={{pkg.svc_data_path}}/pgdata
exec postgres \
  -c config_file={{pkg.svc_config_path}}/postgresql.conf
