// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/interservice/authz/v2/project.proto

package v2 // import "github.com/chef/automate/api/interservice/authz/v2"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	Type                 Type     `protobuf:"varint,3,opt,name=type,proto3,enum=chef.automate.domain.authz.v2.Type" json:"type,omitempty" toml:"type,omitempty" mapstructure:"type,omitempty"`
	Projects             []string `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_CHEF_MANAGED
}

func (m *Project) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

type CreateProjectReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *CreateProjectReq) Reset()         { *m = CreateProjectReq{} }
func (m *CreateProjectReq) String() string { return proto.CompactTextString(m) }
func (*CreateProjectReq) ProtoMessage()    {}
func (*CreateProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{1}
}
func (m *CreateProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectReq.Unmarshal(m, b)
}
func (m *CreateProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectReq.Marshal(b, m, deterministic)
}
func (dst *CreateProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectReq.Merge(dst, src)
}
func (m *CreateProjectReq) XXX_Size() int {
	return xxx_messageInfo_CreateProjectReq.Size(m)
}
func (m *CreateProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectReq proto.InternalMessageInfo

func (m *CreateProjectReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateProjectResp struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty" toml:"project,omitempty" mapstructure:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *CreateProjectResp) Reset()         { *m = CreateProjectResp{} }
func (m *CreateProjectResp) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResp) ProtoMessage()    {}
func (*CreateProjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{2}
}
func (m *CreateProjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResp.Unmarshal(m, b)
}
func (m *CreateProjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResp.Marshal(b, m, deterministic)
}
func (dst *CreateProjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResp.Merge(dst, src)
}
func (m *CreateProjectResp) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResp.Size(m)
}
func (m *CreateProjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResp proto.InternalMessageInfo

func (m *CreateProjectResp) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type GetProjectReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetProjectReq) Reset()         { *m = GetProjectReq{} }
func (m *GetProjectReq) String() string { return proto.CompactTextString(m) }
func (*GetProjectReq) ProtoMessage()    {}
func (*GetProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{3}
}
func (m *GetProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectReq.Unmarshal(m, b)
}
func (m *GetProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectReq.Marshal(b, m, deterministic)
}
func (dst *GetProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectReq.Merge(dst, src)
}
func (m *GetProjectReq) XXX_Size() int {
	return xxx_messageInfo_GetProjectReq.Size(m)
}
func (m *GetProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectReq proto.InternalMessageInfo

func (m *GetProjectReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProjectResp struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty" toml:"project,omitempty" mapstructure:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetProjectResp) Reset()         { *m = GetProjectResp{} }
func (m *GetProjectResp) String() string { return proto.CompactTextString(m) }
func (*GetProjectResp) ProtoMessage()    {}
func (*GetProjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{4}
}
func (m *GetProjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectResp.Unmarshal(m, b)
}
func (m *GetProjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectResp.Marshal(b, m, deterministic)
}
func (dst *GetProjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectResp.Merge(dst, src)
}
func (m *GetProjectResp) XXX_Size() int {
	return xxx_messageInfo_GetProjectResp.Size(m)
}
func (m *GetProjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectResp proto.InternalMessageInfo

func (m *GetProjectResp) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ListProjectsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ListProjectsReq) Reset()         { *m = ListProjectsReq{} }
func (m *ListProjectsReq) String() string { return proto.CompactTextString(m) }
func (*ListProjectsReq) ProtoMessage()    {}
func (*ListProjectsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{5}
}
func (m *ListProjectsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsReq.Unmarshal(m, b)
}
func (m *ListProjectsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsReq.Marshal(b, m, deterministic)
}
func (dst *ListProjectsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsReq.Merge(dst, src)
}
func (m *ListProjectsReq) XXX_Size() int {
	return xxx_messageInfo_ListProjectsReq.Size(m)
}
func (m *ListProjectsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsReq proto.InternalMessageInfo

type ListProjectsResp struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte     `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32      `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ListProjectsResp) Reset()         { *m = ListProjectsResp{} }
func (m *ListProjectsResp) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResp) ProtoMessage()    {}
func (*ListProjectsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{6}
}
func (m *ListProjectsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResp.Unmarshal(m, b)
}
func (m *ListProjectsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResp.Marshal(b, m, deterministic)
}
func (dst *ListProjectsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResp.Merge(dst, src)
}
func (m *ListProjectsResp) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResp.Size(m)
}
func (m *ListProjectsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResp proto.InternalMessageInfo

func (m *ListProjectsResp) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type UpdateProjectReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpdateProjectReq) Reset()         { *m = UpdateProjectReq{} }
func (m *UpdateProjectReq) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectReq) ProtoMessage()    {}
func (*UpdateProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{7}
}
func (m *UpdateProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectReq.Unmarshal(m, b)
}
func (m *UpdateProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectReq.Marshal(b, m, deterministic)
}
func (dst *UpdateProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectReq.Merge(dst, src)
}
func (m *UpdateProjectReq) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectReq.Size(m)
}
func (m *UpdateProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectReq proto.InternalMessageInfo

func (m *UpdateProjectReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateProjectResp struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty" toml:"project,omitempty" mapstructure:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpdateProjectResp) Reset()         { *m = UpdateProjectResp{} }
func (m *UpdateProjectResp) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResp) ProtoMessage()    {}
func (*UpdateProjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{8}
}
func (m *UpdateProjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResp.Unmarshal(m, b)
}
func (m *UpdateProjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResp.Marshal(b, m, deterministic)
}
func (dst *UpdateProjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResp.Merge(dst, src)
}
func (m *UpdateProjectResp) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResp.Size(m)
}
func (m *UpdateProjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResp proto.InternalMessageInfo

func (m *UpdateProjectResp) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type DeleteProjectReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *DeleteProjectReq) Reset()         { *m = DeleteProjectReq{} }
func (m *DeleteProjectReq) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectReq) ProtoMessage()    {}
func (*DeleteProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{9}
}
func (m *DeleteProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectReq.Unmarshal(m, b)
}
func (m *DeleteProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectReq.Marshal(b, m, deterministic)
}
func (dst *DeleteProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectReq.Merge(dst, src)
}
func (m *DeleteProjectReq) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectReq.Size(m)
}
func (m *DeleteProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectReq proto.InternalMessageInfo

func (m *DeleteProjectReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProjectResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *DeleteProjectResp) Reset()         { *m = DeleteProjectResp{} }
func (m *DeleteProjectResp) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectResp) ProtoMessage()    {}
func (*DeleteProjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{10}
}
func (m *DeleteProjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectResp.Unmarshal(m, b)
}
func (m *DeleteProjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectResp.Marshal(b, m, deterministic)
}
func (dst *DeleteProjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectResp.Merge(dst, src)
}
func (m *DeleteProjectResp) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectResp.Size(m)
}
func (m *DeleteProjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectResp proto.InternalMessageInfo

type ListProjectRulesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ListProjectRulesReq) Reset()         { *m = ListProjectRulesReq{} }
func (m *ListProjectRulesReq) String() string { return proto.CompactTextString(m) }
func (*ListProjectRulesReq) ProtoMessage()    {}
func (*ListProjectRulesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{11}
}
func (m *ListProjectRulesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectRulesReq.Unmarshal(m, b)
}
func (m *ListProjectRulesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectRulesReq.Marshal(b, m, deterministic)
}
func (dst *ListProjectRulesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectRulesReq.Merge(dst, src)
}
func (m *ListProjectRulesReq) XXX_Size() int {
	return xxx_messageInfo_ListProjectRulesReq.Size(m)
}
func (m *ListProjectRulesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectRulesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectRulesReq proto.InternalMessageInfo

type ProjectCollectionRulesResp struct {
	ProjectRules         map[string]*ProjectRules `protobuf:"bytes,2,rep,name=project_rules,json=projectRules,proto3" json:"project_rules,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" toml:"project_rules,omitempty" mapstructure:"project_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ProjectCollectionRulesResp) Reset()         { *m = ProjectCollectionRulesResp{} }
func (m *ProjectCollectionRulesResp) String() string { return proto.CompactTextString(m) }
func (*ProjectCollectionRulesResp) ProtoMessage()    {}
func (*ProjectCollectionRulesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{12}
}
func (m *ProjectCollectionRulesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectCollectionRulesResp.Unmarshal(m, b)
}
func (m *ProjectCollectionRulesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectCollectionRulesResp.Marshal(b, m, deterministic)
}
func (dst *ProjectCollectionRulesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectCollectionRulesResp.Merge(dst, src)
}
func (m *ProjectCollectionRulesResp) XXX_Size() int {
	return xxx_messageInfo_ProjectCollectionRulesResp.Size(m)
}
func (m *ProjectCollectionRulesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectCollectionRulesResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectCollectionRulesResp proto.InternalMessageInfo

func (m *ProjectCollectionRulesResp) GetProjectRules() map[string]*ProjectRules {
	if m != nil {
		return m.ProjectRules
	}
	return nil
}

type GetProjectRulesReq struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" toml:"project_id,omitempty" mapstructure:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetProjectRulesReq) Reset()         { *m = GetProjectRulesReq{} }
func (m *GetProjectRulesReq) String() string { return proto.CompactTextString(m) }
func (*GetProjectRulesReq) ProtoMessage()    {}
func (*GetProjectRulesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{13}
}
func (m *GetProjectRulesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRulesReq.Unmarshal(m, b)
}
func (m *GetProjectRulesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRulesReq.Marshal(b, m, deterministic)
}
func (dst *GetProjectRulesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRulesReq.Merge(dst, src)
}
func (m *GetProjectRulesReq) XXX_Size() int {
	return xxx_messageInfo_GetProjectRulesReq.Size(m)
}
func (m *GetProjectRulesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRulesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRulesReq proto.InternalMessageInfo

func (m *GetProjectRulesReq) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetProjectRulesResp struct {
	RulesForProject      *ProjectRules `protobuf:"bytes,2,opt,name=rules_for_project,json=rulesForProject,proto3" json:"rules_for_project,omitempty" toml:"rules_for_project,omitempty" mapstructure:"rules_for_project,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte        `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32         `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetProjectRulesResp) Reset()         { *m = GetProjectRulesResp{} }
func (m *GetProjectRulesResp) String() string { return proto.CompactTextString(m) }
func (*GetProjectRulesResp) ProtoMessage()    {}
func (*GetProjectRulesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{14}
}
func (m *GetProjectRulesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRulesResp.Unmarshal(m, b)
}
func (m *GetProjectRulesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRulesResp.Marshal(b, m, deterministic)
}
func (dst *GetProjectRulesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRulesResp.Merge(dst, src)
}
func (m *GetProjectRulesResp) XXX_Size() int {
	return xxx_messageInfo_GetProjectRulesResp.Size(m)
}
func (m *GetProjectRulesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRulesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRulesResp proto.InternalMessageInfo

func (m *GetProjectRulesResp) GetRulesForProject() *ProjectRules {
	if m != nil {
		return m.RulesForProject
	}
	return nil
}

type ProjectRules struct {
	Rules                []*ProjectRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty" toml:"rules,omitempty" mapstructure:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte         `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32          `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ProjectRules) Reset()         { *m = ProjectRules{} }
func (m *ProjectRules) String() string { return proto.CompactTextString(m) }
func (*ProjectRules) ProtoMessage()    {}
func (*ProjectRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{15}
}
func (m *ProjectRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRules.Unmarshal(m, b)
}
func (m *ProjectRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRules.Marshal(b, m, deterministic)
}
func (dst *ProjectRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRules.Merge(dst, src)
}
func (m *ProjectRules) XXX_Size() int {
	return xxx_messageInfo_ProjectRules.Size(m)
}
func (m *ProjectRules) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRules.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRules proto.InternalMessageInfo

func (m *ProjectRules) GetRules() []*ProjectRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type ProjectRule struct {
	Conditions           []*Condition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty" toml:"conditions,omitempty" mapstructure:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte       `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32        `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ProjectRule) Reset()         { *m = ProjectRule{} }
func (m *ProjectRule) String() string { return proto.CompactTextString(m) }
func (*ProjectRule) ProtoMessage()    {}
func (*ProjectRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{16}
}
func (m *ProjectRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRule.Unmarshal(m, b)
}
func (m *ProjectRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRule.Marshal(b, m, deterministic)
}
func (dst *ProjectRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRule.Merge(dst, src)
}
func (m *ProjectRule) XXX_Size() int {
	return xxx_messageInfo_ProjectRule.Size(m)
}
func (m *ProjectRule) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRule.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRule proto.InternalMessageInfo

func (m *ProjectRule) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

// type = "ChefServers"
// values = ['chef_server_1.org', 'chef_server_2.org', 'chef_*']
type Condition struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" mapstructure:"type,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty" mapstructure:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_9b25ea54a908580b, []int{17}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (dst *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(dst, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Condition) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "chef.automate.domain.authz.v2.Project")
	proto.RegisterType((*CreateProjectReq)(nil), "chef.automate.domain.authz.v2.CreateProjectReq")
	proto.RegisterType((*CreateProjectResp)(nil), "chef.automate.domain.authz.v2.CreateProjectResp")
	proto.RegisterType((*GetProjectReq)(nil), "chef.automate.domain.authz.v2.GetProjectReq")
	proto.RegisterType((*GetProjectResp)(nil), "chef.automate.domain.authz.v2.GetProjectResp")
	proto.RegisterType((*ListProjectsReq)(nil), "chef.automate.domain.authz.v2.ListProjectsReq")
	proto.RegisterType((*ListProjectsResp)(nil), "chef.automate.domain.authz.v2.ListProjectsResp")
	proto.RegisterType((*UpdateProjectReq)(nil), "chef.automate.domain.authz.v2.UpdateProjectReq")
	proto.RegisterType((*UpdateProjectResp)(nil), "chef.automate.domain.authz.v2.UpdateProjectResp")
	proto.RegisterType((*DeleteProjectReq)(nil), "chef.automate.domain.authz.v2.DeleteProjectReq")
	proto.RegisterType((*DeleteProjectResp)(nil), "chef.automate.domain.authz.v2.DeleteProjectResp")
	proto.RegisterType((*ListProjectRulesReq)(nil), "chef.automate.domain.authz.v2.ListProjectRulesReq")
	proto.RegisterType((*ProjectCollectionRulesResp)(nil), "chef.automate.domain.authz.v2.ProjectCollectionRulesResp")
	proto.RegisterMapType((map[string]*ProjectRules)(nil), "chef.automate.domain.authz.v2.ProjectCollectionRulesResp.ProjectRulesEntry")
	proto.RegisterType((*GetProjectRulesReq)(nil), "chef.automate.domain.authz.v2.GetProjectRulesReq")
	proto.RegisterType((*GetProjectRulesResp)(nil), "chef.automate.domain.authz.v2.GetProjectRulesResp")
	proto.RegisterType((*ProjectRules)(nil), "chef.automate.domain.authz.v2.ProjectRules")
	proto.RegisterType((*ProjectRule)(nil), "chef.automate.domain.authz.v2.ProjectRule")
	proto.RegisterType((*Condition)(nil), "chef.automate.domain.authz.v2.Condition")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectsClient is the client API for Projects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectsClient interface {
	UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*UpdateProjectResp, error)
	CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error)
	GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectResp, error)
	DeleteProject(ctx context.Context, in *DeleteProjectReq, opts ...grpc.CallOption) (*DeleteProjectResp, error)
	ListProjects(ctx context.Context, in *ListProjectsReq, opts ...grpc.CallOption) (*ListProjectsResp, error)
	// Note: POC functions that are not ready to expose outside of our
	// spike (aka keep them out of the gateway for now).
	ListProjectRules(ctx context.Context, in *ListProjectRulesReq, opts ...grpc.CallOption) (*ProjectCollectionRulesResp, error)
	GetProjectRules(ctx context.Context, in *GetProjectRulesReq, opts ...grpc.CallOption) (*GetProjectRulesResp, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*UpdateProjectResp, error) {
	out := new(UpdateProjectResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error) {
	out := new(CreateProjectResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectResp, error) {
	out := new(GetProjectResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) DeleteProject(ctx context.Context, in *DeleteProjectReq, opts ...grpc.CallOption) (*DeleteProjectResp, error) {
	out := new(DeleteProjectResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/DeleteProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) ListProjects(ctx context.Context, in *ListProjectsReq, opts ...grpc.CallOption) (*ListProjectsResp, error) {
	out := new(ListProjectsResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) ListProjectRules(ctx context.Context, in *ListProjectRulesReq, opts ...grpc.CallOption) (*ProjectCollectionRulesResp, error) {
	out := new(ProjectCollectionRulesResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/ListProjectRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProjectRules(ctx context.Context, in *GetProjectRulesReq, opts ...grpc.CallOption) (*GetProjectRulesResp, error) {
	out := new(GetProjectRulesResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.authz.v2.Projects/GetProjectRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectsServer is the server API for Projects service.
type ProjectsServer interface {
	UpdateProject(context.Context, *UpdateProjectReq) (*UpdateProjectResp, error)
	CreateProject(context.Context, *CreateProjectReq) (*CreateProjectResp, error)
	GetProject(context.Context, *GetProjectReq) (*GetProjectResp, error)
	DeleteProject(context.Context, *DeleteProjectReq) (*DeleteProjectResp, error)
	ListProjects(context.Context, *ListProjectsReq) (*ListProjectsResp, error)
	// Note: POC functions that are not ready to expose outside of our
	// spike (aka keep them out of the gateway for now).
	ListProjectRules(context.Context, *ListProjectRulesReq) (*ProjectCollectionRulesResp, error)
	GetProjectRules(context.Context, *GetProjectRulesReq) (*GetProjectRulesResp, error)
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).UpdateProject(ctx, req.(*UpdateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).CreateProject(ctx, req.(*CreateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProject(ctx, req.(*GetProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/DeleteProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).DeleteProject(ctx, req.(*DeleteProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ListProjects(ctx, req.(*ListProjectsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_ListProjectRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ListProjectRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/ListProjectRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ListProjectRules(ctx, req.(*ListProjectRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProjectRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProjectRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.authz.v2.Projects/GetProjectRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProjectRules(ctx, req.(*GetProjectRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chef.automate.domain.authz.v2.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProject",
			Handler:    _Projects_UpdateProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _Projects_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Projects_GetProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _Projects_DeleteProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _Projects_ListProjects_Handler,
		},
		{
			MethodName: "ListProjectRules",
			Handler:    _Projects_ListProjectRules_Handler,
		},
		{
			MethodName: "GetProjectRules",
			Handler:    _Projects_GetProjectRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/interservice/authz/v2/project.proto",
}

func init() {
	proto.RegisterFile("api/interservice/authz/v2/project.proto", fileDescriptor_project_9b25ea54a908580b)
}

var fileDescriptor_project_9b25ea54a908580b = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x8e, 0x13, 0xfe, 0x32, 0xfc, 0x25, 0x1b, 0x71, 0x4e, 0x64, 0x09, 0x29, 0xda, 0x83, 0xce,
	0x89, 0x38, 0xc4, 0x06, 0x83, 0x4a, 0x69, 0xa5, 0x8a, 0x42, 0x7f, 0xd5, 0x5e, 0x20, 0xab, 0x14,
	0xa9, 0x55, 0x8b, 0x4c, 0xbc, 0x14, 0x17, 0xc7, 0x5e, 0xec, 0x4d, 0xa4, 0x50, 0xf5, 0xa6, 0x7d,
	0xab, 0x5e, 0xf5, 0x09, 0xfa, 0x1e, 0x7d, 0x87, 0x5e, 0x54, 0x5e, 0xef, 0x82, 0xed, 0x40, 0x9d,
	0x20, 0xee, 0xec, 0xf1, 0x7e, 0xdf, 0x7c, 0x33, 0xe3, 0xf9, 0x6c, 0xf8, 0xcf, 0xa2, 0x8e, 0xee,
	0x78, 0x8c, 0x04, 0x21, 0x09, 0x7a, 0x4e, 0x9b, 0xe8, 0x56, 0x97, 0x9d, 0x9c, 0xeb, 0x3d, 0x43,
	0xa7, 0x81, 0xff, 0x91, 0xb4, 0x99, 0x46, 0x03, 0x9f, 0xf9, 0x68, 0xb1, 0x7d, 0x42, 0x8e, 0x35,
	0xab, 0xcb, 0xfc, 0x8e, 0xc5, 0x88, 0x66, 0xfb, 0x1d, 0xcb, 0xf1, 0x34, 0x7e, 0x58, 0xeb, 0x19,
	0xea, 0xdf, 0x3d, 0xcb, 0x75, 0x6c, 0x8b, 0x11, 0x5d, 0x5e, 0xc4, 0x38, 0x75, 0xe9, 0xfa, 0x04,
	0xac, 0x4f, 0xc5, 0x29, 0xfc, 0x45, 0x81, 0xc9, 0xbd, 0x38, 0x1f, 0x42, 0x30, 0xe6, 0x59, 0x1d,
	0x52, 0x57, 0x1a, 0x4a, 0xb3, 0x6c, 0xf2, 0x6b, 0x34, 0x07, 0x45, 0xc7, 0xae, 0x17, 0x79, 0xa4,
	0xe8, 0xd8, 0x68, 0x13, 0xc6, 0x22, 0x74, 0xbd, 0xd4, 0x50, 0x9a, 0x73, 0xc6, 0x3f, 0xda, 0x1f,
	0xc5, 0x69, 0xaf, 0xfa, 0x94, 0x98, 0x1c, 0x80, 0x54, 0x98, 0x12, 0x75, 0x85, 0xf5, 0xb1, 0x46,
	0xa9, 0x59, 0x36, 0x2f, 0xee, 0xb1, 0x09, 0x95, 0xdd, 0x80, 0x58, 0x8c, 0x08, 0x25, 0x26, 0x39,
	0xbb, 0x52, 0xcc, 0xf2, 0xa5, 0x98, 0x1d, 0xf5, 0xdb, 0xcf, 0xef, 0xa5, 0x85, 0xa0, 0x66, 0x54,
	0xdf, 0xbf, 0xb5, 0x5a, 0xe7, 0xab, 0xad, 0xad, 0xd6, 0xbb, 0x4f, 0x6b, 0x2b, 0x77, 0x36, 0x3e,
	0x2f, 0x45, 0x42, 0xf1, 0x3e, 0x54, 0x33, 0x9c, 0x21, 0x45, 0xdb, 0x30, 0x29, 0x92, 0x72, 0xde,
	0x69, 0xe3, 0xdf, 0x9c, 0x02, 0x24, 0x58, 0xc2, 0xf0, 0x7d, 0x98, 0x7d, 0x4a, 0x58, 0x42, 0x67,
	0xac, 0x49, 0x19, 0x4a, 0x93, 0x09, 0x73, 0x49, 0xf0, 0xad, 0x08, 0xaa, 0xc2, 0xfc, 0x4b, 0x27,
	0x94, 0xa4, 0xa1, 0x49, 0xce, 0xf0, 0x6b, 0xa8, 0xa4, 0x43, 0x21, 0x45, 0x3b, 0x89, 0xf6, 0x2b,
	0x8d, 0xd2, 0x08, 0x99, 0x52, 0x63, 0xda, 0xa7, 0xf6, 0xad, 0x8f, 0x29, 0xc3, 0x79, 0x2b, 0x5d,
	0x79, 0x00, 0x95, 0x47, 0xc4, 0x25, 0x29, 0xa9, 0xa3, 0x4c, 0xaa, 0x06, 0xd5, 0x0c, 0x3e, 0xa4,
	0x78, 0x01, 0x6a, 0x89, 0xbe, 0x9a, 0x5d, 0x97, 0xf0, 0x76, 0xff, 0x52, 0x40, 0x15, 0xb1, 0x5d,
	0xdf, 0x75, 0x49, 0x9b, 0x39, 0xbe, 0x27, 0x9e, 0x86, 0x14, 0x51, 0x98, 0x15, 0xaa, 0x0e, 0x83,
	0x28, 0x58, 0x2f, 0xf2, 0xf6, 0xbf, 0x18, 0xae, 0xa4, 0x2b, 0x18, 0xb5, 0xa4, 0x80, 0xc7, 0x1e,
	0x0b, 0xfa, 0xe6, 0x0c, 0x4d, 0x84, 0x54, 0x17, 0xaa, 0x03, 0x47, 0x50, 0x05, 0x4a, 0xa7, 0xa4,
	0x2f, 0xe6, 0x14, 0x5d, 0xa2, 0x87, 0x30, 0xde, 0xb3, 0xdc, 0x2e, 0xe1, 0x93, 0x9a, 0x36, 0xfe,
	0x1f, 0xb2, 0xc7, 0x5c, 0x46, 0x8c, 0xbc, 0x57, 0xbc, 0xab, 0xe0, 0x75, 0x40, 0x89, 0x97, 0x5a,
	0x34, 0x05, 0x2d, 0x02, 0xc8, 0xaa, 0x65, 0xd3, 0xcd, 0xb2, 0x88, 0x3c, 0xb7, 0xb1, 0x07, 0xb5,
	0x01, 0x50, 0x48, 0xd1, 0x01, 0x54, 0x79, 0x8f, 0x0e, 0x8f, 0xfd, 0xe0, 0x50, 0xbe, 0x02, 0x37,
	0x90, 0x37, 0xcf, 0x59, 0x9e, 0xf8, 0x81, 0x88, 0xe2, 0x3d, 0x98, 0x49, 0x1e, 0x40, 0xdb, 0x30,
	0x9e, 0x1c, 0xc6, 0xf2, 0xf0, 0xe4, 0x66, 0x0c, 0xc4, 0x07, 0x30, 0x9d, 0x88, 0xa2, 0x67, 0x00,
	0x6d, 0xdf, 0xb3, 0x9d, 0x68, 0x52, 0x92, 0xb5, 0x99, 0xc3, 0xba, 0x2b, 0x01, 0x66, 0x02, 0x8b,
	0x37, 0xa1, 0x7c, 0xf1, 0x20, 0x5a, 0x2f, 0x6e, 0xb7, 0x62, 0xbd, 0xb8, 0x93, 0xfe, 0x05, 0x13,
	0xbc, 0xfb, 0x71, 0x9a, 0xb2, 0x29, 0xee, 0x8c, 0x1f, 0x13, 0x30, 0x25, 0x77, 0x1e, 0x31, 0x98,
	0x4d, 0xed, 0x15, 0xd2, 0x73, 0xc4, 0x64, 0x37, 0x5b, 0x5d, 0x1d, 0x0d, 0x10, 0x52, 0x5c, 0x88,
	0xb2, 0xa6, 0x4c, 0x37, 0x37, 0x6b, 0xd6, 0xf6, 0x73, 0xb3, 0x0e, 0x78, 0x3a, 0x2e, 0xa0, 0x53,
	0x80, 0xcb, 0x97, 0x09, 0xad, 0xe4, 0x30, 0xa4, 0xec, 0x5b, 0x6d, 0x8d, 0x70, 0x5a, 0x96, 0x98,
	0x72, 0x86, 0xdc, 0x12, 0xb3, 0x3e, 0x94, 0x5b, 0xe2, 0xa0, 0xf1, 0x14, 0xd0, 0x19, 0xcc, 0x24,
	0x2d, 0x1d, 0x69, 0x39, 0x1c, 0x99, 0x4f, 0x82, 0xaa, 0x8f, 0x74, 0x9e, 0xa7, 0xfc, 0xaa, 0xa4,
	0x3e, 0x23, 0xf1, 0xde, 0x18, 0xc3, 0xf3, 0x48, 0x2b, 0x50, 0xb7, 0x6e, 0xec, 0x74, 0xb8, 0x80,
	0xce, 0x61, 0x3e, 0x63, 0x14, 0x68, 0x6d, 0xf8, 0x91, 0x49, 0x09, 0xc6, 0xa8, 0x90, 0x28, 0xf7,
	0xce, 0xc6, 0x1b, 0xe3, 0x83, 0xc3, 0x4e, 0xba, 0x47, 0x5a, 0xdb, 0xef, 0xe8, 0x11, 0x83, 0x2e,
	0x19, 0xf4, 0x6b, 0x7f, 0xae, 0x8e, 0x26, 0xf8, 0x8f, 0xd5, 0xfa, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x13, 0x14, 0x5c, 0x2a, 0xe1, 0x09, 0x00, 0x00,
}
