#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

if [[ -f ${pkg_prefix}/es/config/opensearch.keystore.tmp ]]; then
  echo "Removing stale keystore temporary file"
  rm {{pkg.svc_config_path}}/opensearch.keystore.tmp
fi

if [[ -f ${pkg_prefix}/es/config/opensearch.keystore ]]; then
  opensearch-keystore upgrade
else
  opensearch-keystore create
fi

chown hab:hab ${pkg_prefix}/es/config/opensearch.keystore

secrets-helper show backup-gateway.access_key | opensearch-keystore add \
  --stdin \
  --force \
  s3.client.{{cfg.s3.client.name}}.access_key

secrets-helper show backup-gateway.secret_key | opensearch-keystore add \
  --stdin \
  --force \
  s3.client.{{cfg.s3.client.name}}.secret_key


#https://opensearch.org/docs/latest/upgrade-to/upgrade-to/