#!{{pkgPathFor "core/bash"}}/bin/bash
echo "i am at init_keystore"
echo {{pkg.svc_config_path}}
exec 2>&1

if [[ -f {{pkg.svc_config_path}}/opensearch.keystore.tmp ]]; then
  echo "Removing stale keystore temporary file"
  rm {{pkg.svc_config_path}}/opensearch.keystore.tmp
fi
chown hab:hab -RL {{pkg.svc_config_path}}/
if [[ -f {{pkg.svc_config_path}}/opensearch.keystore ]]; then
  opensearch-keystore upgrade
#else
#  opensearch-keystore create
fi

#chown hab:hab {{pkg.svc_config_path}}/opensearch.keystore

#secrets-helper show backup-gateway.access_key | opensearch-keystore add \
#  --stdin \
#  --force \
#  s3.client.{{cfg.s3.client.name}}.access_key

#secrets-helper show backup-gateway.secret_key | opensearch-keystore add \
#  --stdin \
#  --force \
#  s3.client.{{cfg.s3.client.name}}.secret_key
