habitatConfig({
  cookie_domain : "{{cfg.web.cookie_domain}}",
  docs_url : "{{cfg.docs_url}}",
  enable_builder : false,
  enable_publisher_amazon : false,
  enable_publisher_azure : false,
  enable_publisher_docker : false,
  enable_statuspage : false,
  environment : "{{cfg.web.environment}}",
  github_api_url : "{{cfg.github.api_url}}",
  github_app_url : "{{cfg.github.app_url}}",
  github_app_id : "{{cfg.github.app_id}}",
  oauth_authorize_url : "{{cfg.oauth.authorize_url}}",
  oauth_client_id : "{{cfg.oauth.client_id}}",
  oauth_provider : "{{cfg.oauth.provider}}",
  oauth_redirect_url : "{{cfg.oauth.redirect_url}}",
  source_code_url : "{{cfg.source_code_url}}",
  tutorials_url : "{{cfg.tutorials_url}}",
  use_gravatar : {{ cfg.web.use_gravatar }},
  version : "{{pkg.ident}}",
  www_url : "{{cfg.www_url}}",
});
