#!/usr/bin/env bash
# Usage: automate-cluster-ctl credentials
# Summary: Manage cluster credentials including ssl and passwords
# Built-in help

RUBY_PATH=$(HAB_LICENSE=accept-no-persist hab pkg list --origin core | grep ruby30 | tail -1)
[ -d "./test/vendor/bundle" ] || (cd test && /hab/pkgs/$RUBY_PATH/bin/bundle install --path vendor/bundle)
cd test && /hab/pkgs/$RUBY_PATH/bin/bundle exec /hab/pkgs/$RUBY_PATH/bin/ruby lib/credentials "$@"
