#!/usr/bin/env bash
# Usage: automate-cluster-ctl credentials
# Summary: Manage cluster credentials including ssl and passwords
# Built-in help


[ -d "./test/vendor/bundle" ] || (cd test && $(hab pkg path core/ruby30)/bin/bundle install --path vendor/bundle)
cd test && $(hab pkg path core/ruby30)/bin/bundle exec $(hab pkg path core/ruby30)/bin/ruby lib/credentials "$@"
