#!/bin/bash
set -euo pipefail

export HAB_NONINTERACTIVE=true
export HAB_NOCOLORING=true

desired_inspec_version() {
    local top_level
    top_level=$(git rev-parse --show-toplevel)
    cat "$top_level/INSPEC_VERSION"
}

install_inspec() {
    hab pkg install core/ruby -b -f
    hab pkg install core/gcc -b -f
    gem install inspec --no-document --version $(desired_inspec_version)
}

install_inspec
