package opensearchbackupservice

const TEST_REPO_NAME = "S3BackupVerifyNew"
const TEST_SNAPSHOT_NAME = "test-snapshot-managed"
const TEST_INDEX_NAME = "test-index-managed"
const INDEX_CREATE_FAILED_MESSAGE = "Failed to create an index on the Opensearch Domain"
const INDEX_CREATE_FAILED_RESOLUTION = "Setup Opensearch with valid Configuration and provide the IAM user proper permissions to create an index."
const SNAPSHOT_REPO_CREATE_FAILED_MESSAGE = "Failed to create the Snapshot Repository on the Opensearch Domain"
const SNAPSHOT_REPO_CREATE_FAILED_RESOLUTION = "Setup Opensearch with valid Configuration and provide the IAM user proper permissions to create the Snapsshot Repository."
const SNAPSHOT_CREATE_FAILED_MESSAGE = "Failed to create the Snapshot on the Opensearch Domain"
const SNAPSHOT_CREATE_FAILED_RSOLUTION = "Setup Opensearch with valid Configuration and provide the IAM user proper permissions to create a Snapshot."
const INDEX_DELETE_FAILED_MESSAGE = "Failed to delete an index on the Opensearch Domain"
const INDEX_DELETE_FAILED_RESOLUTION = "Provide the IAM user proper permissions to delete an index."
const SNAPSHOT_REPO_DELETE_FAILED_MESSAGE = "Failed to delete the Snapshot Repository on the Opensearch Domain"
const SNAPSHOT_REPO_DELETE_FAILED_RESOLUTION = "Provide the IAM user proper permissions to delete the Snapshot Repository."
const SNAPSHOT_DELETE_FAILED_MESSAGE = "Failed to delete the Snapshot on the Opensearch Domain"
const SNAPSHOT_DELETE_FAILED_RESOLUTION = "Provide the IAM user proper permissions to delete the Snapshot."
