source "https://rubygems.org"

gem "highline"
gem "httpclient"
gem "mixlib-config"
gem "mixlib-install"
gem "mixlib-shellout"
gem "train"

gem "chef", "~> 15.4", ">= 15.4.45"
gem "ohai", "~> 8.26", ">= 8.26.1"

group :development, :test do
  gem "pry"
  gem "rspec"
  gem "rb-readline"
end
