source "https://rubygems.org"

gem "omnibus-ctl", git: "https://github.com/chef/omnibus-ctl.git"

# The elasticsearch gem's major version should be the same as the version of
# Elasticsearch that we require.
gem 'elasticsearch', "~> 5"
gem "highline"
gem "httpclient"
gem "mixlib-config"
gem "mixlib-install"
gem "mixlib-shellout"
gem "train"
gem "tty-spinner"

# To prevent gem conflicts we must keep the Chef and Ohai version here
# in sync with the versions in `omnibus_overrides.rb`
gem "chef", "~> 12.21"
gem "ohai", "~> 8.24"

group :development, :test do
  gem "pry"
  gem "rspec"
  gem "rb-readline"
end
