source "https://rubygems.org"

gem "highline"
gem "httpclient"
gem "mixlib-config"
gem "mixlib-install"
gem "mixlib-shellout"
gem "train"

gem "chef", "~> 12.21"
gem "ohai", "~> 8.24"

group :development, :test do
  gem "pry"
  gem "rspec"
  gem "rb-readline"
end
