#!{{pkgPathFor "core/bash"}}/bin/bash

exec service-health {{cfg.service.host}} {{cfg.service.port}} "authn-service" \
 {{pkg.svc_config_path}}/service.crt \
 {{pkg.svc_config_path}}/service.key \
 {{pkg.svc_config_path}}/root_ca.crt
