#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1


# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

if [ ! -f /hab/.skip_migration ]; then
  pg-helper ensure-service-database "{{cfg.storage.database}}"

  pg-helper create-extension "{{cfg.storage.database}}" "pgcrypto"
fi


exec authn-service serve {{pkg.svc_config_path}}/config.yml
