#!{{pkgPathFor "core/bash"}}/bin/bash
#
curlOpts="-sS --fail --max-time 2"
# shellcheck disable=SC2086
output=$({{pkgPathFor "core/curl"}}/bin/curl $curlOpts "http://localhost:{{cfg.service.port}}/automate_es_gateway_status")
res=$?
if [[ "$res" != "0" ]];then
    echo "health check curl command returned ${res}:"
    echo "$output"
    exit 2
fi
