[mlsa]
accept = false

[service]
host = "localhost"
port = 10107

[storage]
database = "chef_user_settings_service"
user = "user_settings"
max_open_conns = 10
max_idle_conns = 10

[tls]
key_contents = ""
cert_contents = ""
root_cert_contents = ""
