-module(eu_test_helpers).

-include_lib("delivery/include/deliv_types.hrl").

-compile([export_all]).

phase_run_summary_example() ->
    [#phase_run_summary{stage_id = 1,stage = <<"verify">>,
                        stage_status = <<"passed">>,phase_id = 3,phase = <<"unit">>,
                        phase_status = <<"passed">>, search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 1,stage = <<"verify">>,
                        stage_status = <<"passed">>,phase_id = 1,phase = <<"lint">>,
                        phase_status = <<"passed">>, search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 1,stage = <<"verify">>,
                        stage_status = <<"passed">>,phase_id = 2,
                        phase = <<"syntax">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 10,
                        phase = <<"unit">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 11,
                        phase = <<"lint">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 12,
                        phase = <<"syntax">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 14,
                        phase = <<"quality">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 15,
                        phase = <<"security">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>},
     #phase_run_summary{stage_id = 2,stage = <<"build">>,
                        stage_status = <<"passed">>,phase_id = 16,
                        phase = <<"publish">>,phase_status = <<"passed">>,
                        search_query = <<"[builder*]">>,
                        search_description = <<"An awesome search">>}].
