#!{{pkgPathFor "core/bash"}}/bin/bash -e

echo "RUN HOOK CALLED ************"
echo "UPDATED RUN HOOK CALLED ************"


exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

mkdir -p {{pkg.svc_var_path}}/logs

export RAILS_ENV={{cfg.rails_env}}
export HOME={{pkg.svc_files_path}}

export LD_RUN_PATH=$(hab pkg path "core/gcc-libs")/lib:$LD_RUN_PATH
export VERSION=`ls -1 {{pkg.svc_files_path}}/db/migrate | tail -n 1 | $(hab pkg path "core/sed")/bin/sed -e "s/_.*//g"`
export LD_LIBRARY_PATH=$LD_RUN_PATH
export PATH=$HOME/bin:$PATH
export CHEF_SECRETS_DATA=$(cat {{pkg.svc_config_path}}/veil-secrets.json)

# export HOME={{pkg.svc_var_path}}
export RUNNER_LOG_DIR="{{pkg.svc_var_path}}/logs"
export RELX_CONFIG_PATH="{{pkg.svc_config_path}}/sys.config"
export VMARGS_PATH="{{pkg.svc_config_path}}/vm.args"
export DBNAME="{{cfg.sql.db_name}}"
{{#if cfg.fips_enabled ~}}
export OPENSSL_FIPS=1
{{/if ~}}

mkdir -p "{{pkg.svc_var_path}}/etc"
render-template sqerl.config "{{pkg.svc_var_path}}/etc/sqerl.config"

pg-helper rename-if-exists ocid "$DBNAME"
pg-helper ensure-service-database "$DBNAME"
pg-helper create-extension "$DBNAME" "uuid-ossp"
pg-helper fix-permissions "$DBNAME"

secrets-helper generate oc_id.superuser_id 32 --if-not-exists

echo "exec run called ************"
# exec secrets-helper exec --secret oc_id.superuser_id -- oc_id foreground

echo "skipped run priting ***********HOME"
echo $HOME

echo "*********CD to custom path"
cd /hab/pkgs/chef/oc_id/15.4.0/20230105061030/oc_id
pwd


echo "(((((((Check what it prints"
echo $(hab pkg path "core/bundler")
# Habitat Todo

echo "*********Running rails bootstrap"
# move assets compile into the build phase
# $(hab pkg path "core/bundler")/bin/bundle exec bin/rake assets:precompile
# $(hab pkg path "core/bundler")/bin/bundle exec bin/rake db:migrate
# $(hab pkg path "core/bundler")/bin/bundle exec bin/rails server -p {{cfg.port}} -b 0.0.0.0
# bin/bundle exec bin/rake assets:precompile
# bin/bundle exec bin/rake db:migrate
# bin/bundle exec bin/rails server -p {{cfg.port}} -b 0.0.0.0

#!/bin/bash -e
#
# Copyright 2012-2015 Chef Software, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
export SVWAIT=30

pkg_prefix=/hab/pkgs/chef/oc_id/15.4.0/20230105061030
cd "$pkg_prefix/oc_id"

RUBY_BIN_DIR=/hab/pkgs/core/ruby27/2.7.5/20220312100031/bin

echo "@@@@@@@@@@"
echo pkg_prefix
echo pwd

export PATH=$PATH:$RUBY_BIN_DIR
export GEM_PATH="$pkg_prefix/oc_id/vendor/bundle"
# CHEF_SECRETS_DATA=$(cat /hab/svc/chef-server-ctl/config/hab-secrets-config.json)
# export CHEF_SECRETS_DATA
# export CSC_KNIFE_CONFIG_FILE=/hab/svc/chef-server-ctl/config/pivotal.rb
# export CSC_KNIFE_BIN="${RUBY_BIN_DIR}/bundle exec ${pkg_prefix}/chef/bin/knife"

# bundle exec binstubs/chef-server-ctl "$@"
bin/bundle exec bin/rake assets:precompile
