#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

chmod 0600 {{pkg.svc_config_path}}/service.crt
chmod 0600 {{pkg.svc_config_path}}/service.key
chmod 0600 {{pkg.svc_config_path}}/root_ca.crt

exec haproxy -f {{pkg.svc_config_path}}/haproxy.conf -db
