#!/bin/sh

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

while [ 1 ]
do
  PYTHONWARNINGS=ignore curator --config {{pkg.svc_path}}/config/curator.yml {{pkg.svc_path}}/config/actions.yml &
  sleep 3600
done
