# WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING 
#
# If you are modifying this file, you almost surely also want to
# modify pkg/es/config_request.go. The DefaultConfigRequest() function
# sets all of the real defaults.
#
# The duplication is necessary currently since our tests and studio
# require automate-elasticsearh be launchable without the deployment
# service.
#
# WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
[cluster]
  #
  # Use a descriptive name for your cluster:
  #
  name = "opensearch"
  max_shards_per_node= "2000"

  [cluster.routing.allocation]
    #
    # How many concurrent shard recoveries are allowed to happen on a node.
    # Defaults to 2.
    #
    node_concurrent_recoveries = "2"
    #
    # While the recovery of replicas happens over the network, the recovery of
    # an unassigned primary after node restart uses data from the local disk.
    # These should be fast so more initial primary recoveries can happen in
    # parallel on the same node. Defaults to 4.
    #
    node_initial_primaries_recoveries = "4"
    #
    # Allows to perform a check to prevent allocation of multiple instances of
    # the same shard on a single host, based on host name and host address.
    # Defaults to false, meaning that no check is performed by default. This
    # setting only applies if multiple nodes are started on the same machine.
    #
    same_shard_host = "false"
    #
    # https://www.elastic.co/guide/en/elasticsearch/reference/2.3/allocation-awareness.html
    #
    awareness_attributes = ""
#
# ------------------------------------ Node ------------------------------------
#
[node]
  # Use a descriptive name for the node:
  #
  name = ""
  #
  # Add custom attributes to the node:
  #
  # node.rack: r1
  #
  rack_id = ""
  zone    = ""
  #
  # Disable starting multiple nodes on a single system:
  #
  max_local_storage_nodes = 1
  #
  # Configure node as master-only, master-eligible, data-only, or client
  # (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-node.html#master-node)
  # Default is master-eligible (master and data are both "true")
  #
  master = true
  data   = true

#
# ----------------------------------- Paths ------------------------------------
#
[path]
  #
  # Path to directory where to store the data (separate multiple locations by comma):
  #
  data =    ""
  #
  # Path to log files:
  #
  logs =    "logs"
  #
  # Path to backup repository
  repo = ""

#
# ----------------------------------- Indices ----------------------------------
#
[indices]
  [indices.recovery]
    max_bytes_per_sec  =            "20mb"

  [indices.fielddata]
    #
    # The max size of the field data cache, eg 30% of node heap space, or an absolute
    # value, eg 12GB. Defaults to unbounded.
    #
    cache_size =                   ""

  [indices.breaker]
    #
    # Starting limit for overall parent breaker, defaults to 70% of JVM heap.
    #
    total_limit =                    "95%"
    #
    # Limit for fielddata breaker, defaults to 60% of JVM heap.
    #
    fielddata_limit =                "60%"
    #
    # A constant that all field data estimations are multiplied with to determine a
    # final estimation. Defaults to 1.03
    #
    fielddata_overhead =             "1.03"
    #
    # Limit for request breaker, defaults to 40% of JVM heap.
    #
    request_limit =                  "40%"
    #
    # A constant that all request estimations are multiplied with to determine a
    # final estimation. Defaults to 1.
    #
    request_overhead =               "1"

#
# ----------------------------------- Memory -----------------------------------
#
[bootstrap]
  # Lock the memory on startup:
  #
  memory_lock = false
  #
  # Make sure that the heap size is set to about half the memory available
  # on the system and that the owner of the process is allowed to use this
  # limit.
  #
  # Elasticsearch performs poorly when the system is swapping the memory.
  #

#
# ---------------------------------- Network -----------------------------------
#
[network]
  #
  # Set the bind address to a specific IP (IPv4 or IPv6):
  #
  host =  "0.0.0.0"
  #
  # Set a custom port for HTTP:
  #
  port = 9200
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>

[transport]
  port = 9300

#
# --------------------------------- Discovery ----------------------------------
#
[discovery]
  # Pass an initial list of hosts to perform discovery when new node is started:
  # The default list of hosts is ["127.0.0.1", "[::1]"]
  #
  ping_unicast_hosts = "[]"
  #
  # Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
  #
  minimum_master_nodes = 1
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
  #
  zen_fd_ping_timeout = "30s"

#
# ---------------------------------- Gateway -----------------------------------
#
[gateway]
  #
  # Block initial recovery after a full cluster restart until N nodes are started:
  #
  recover_after_nodes   = ""
  #
  # The number of (data or master) nodes that are expected to be in the cluster.
  # Recovery of local shards will start as soon as the expected number of nodes
  # have joined the cluster. Defaults to 0
  #
  expected_nodes        = "0"
  #
  # The number of master nodes that are expected to be in the cluster. Recovery
  # of local shards will start as soon as the expected number of master nodes
  # have joined the cluster. Defaults to 0
  #
  expected_master_nodes = "0"
  #
  # The number of data nodes that are expected to be in the cluster. Recovery of
  # local shards will start as soon as the expected number of data nodes have
  # joined the cluster. Defaults to 0
  #
  expected_data_nodes   = "0"
  #
  # If the expected number of nodes is not achieved, the recovery process waits
  # for the configured amount of time before trying to recover regardless.
  # Defaults to 5m if one of the expected_nodes settings is configured.
  #
  recover_after_time    = ""
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
  #

#
# ---------------------------------- Various -----------------------------------
#
[action]
  #
  # Require explicit names when deleting indices:
  #
  destructive_requires_name  = "true"

# ======================== Elasticsearch Logger Configuration =========================
[logger]
  level = "info"

# ======================== Elasticsearch Plugins Configuration =========================
[plugins]
  [plugins.security]
    allow_unsafe_democertificates = true
    allow_default_init_securityindex = true
    nodes_dn = "- CN=chefnode,O=Chef Software Inc,L=Seattle,ST=Washington,C=US"
    enable_snapshot_restore_privilege = true
    check_snapshot_restore_write_privileges = true

  [plugins.security.ssl.transport]
    pemcert_filepath = "certificates/node1.pem"
    pemkey_filepath = "certificates/node1-key.pem"
    pemtrustedcas_filepath = "certificates/root-ca.pem"
    enforce_hostname_verification = false
    resolve_hostname = false
  [plugins.security.ssl.http]
    enabled = true
    pemcert_filepath = "certificates/node1.pem"
    pemkey_filepath = "certificates/node1-key.pem"
    pemtrustedcas_filepath = "certificates/root-ca.pem"
  [plugins.security.authcz]
    admin_dn = "- CN=chefadmin,O=Chef Software Inc,L=Seattle,ST=Washington,C=US"
  [plugins.security.audit]
    type = "internal_opensearch"
  [plugins.security.restapi]
    roles_enabled = "[\"all_access\", \"security_rest_api_access\"]"
  [plugins.security.system_indices]
    enabled = true
    indices = "[\".opendistro-alerting-config\", \".opendistro-alerting-alert*\", \".opendistro-anomaly-results*\", \".opendistro-anomaly-detector*\", \".opendistro-anomaly-checkpoints\", \".opendistro-anomaly-detection-state\", \".opendistro-reports-*\", \".opendistro-notifications-*\", \".opendistro-notebooks\", \".opensearch-observability\", \".opendistro-asynchronous-search-response*\", \".replication-metadata-store\"]"
  cloud_aws_signer = ""
  #security.ssl.http.enabled = false

# ======================== S3 Client Configuration =========================
[s3]
  [s3.client.default]
    protocol = "https"
    read_timeout = "60s"
    max_retries = "3"
    use_throttle_retries = true
    endpoint = "s3.amazonaws.com"

# ======================== Runtime Configuration =========================
[runtime]
  max_open_files = ""
  max_locked_memory = "unlimited"
  es_startup_sleep_time = ""
  es_java_opts = ""
  minHeapsize = "2g"
  maxHeapsize = "2g"
  g1ReservePercent = "25"
  initiatingHeapOccupancyPercent = "15"

[deprecated]
external_os = false

[opensearch_auth]
  admin_username = "admin"
  admin_password = "admin"
  #Bcrypt hashed password
  hashed_password = "$2a$12$yObdBmd8JFy2ar7nRjv46OYs3P3q5uB9llsrLRppWyAO/YOQ2JW3m"

[tls]
# root pem cert that signed the two cert/key pairs below
rootCA = """-----BEGIN CERTIFICATE-----\nMIIDqzCCApOgAwIBAgIUMUG0kbGT5s8Vo415aNfii81CzRcwDQYJKoZIhvcNAQEL\nBQAwZTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcM\nB1NlYXR0bGUxGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMRMwEQYDVQQDDApj\naGVmcm9vdGNhMB4XDTIyMDYwMTA3MzMwMFoXDTI1MDUzMTA3MzMwMFowZTELMAkG\nA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUx\nGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMRMwEQYDVQQDDApjaGVmcm9vdGNh\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4aKz6j+Otgeg+oZSsHtq\nz5Phyb2cWr+CdbLb2qZA9ZDcCjEzkxvuvI6QBScF9feVk7YVXg59DXlHJRP7AHx5\nnG5iQmND0jUUQGjyZfKTWO8Z9F8D/w0HAFOk4LTvVR/AAC6f9PpxjaydfSzkh5cc\nNxeotjlkYUgh6D7fFma9gRtjX4a36miA5FqCv0Lkwrk9tXHdDk6skdjBvCS0URnq\nzDfyTcK7R/L/iaGYtY43c8tB8eHKwK+ZQ2fR4V90YI3xkbkwr6j0efZyU2Kp/03r\n2nDtFQXHwwuj6Sg465DJB9MQ01IbR30NUjJiFGOJaxdRlhsEeWWNL8BELQuGpJe9\nVQIDAQABo1MwUTAdBgNVHQ4EFgQU3XAfDSRK1wCTf0wiDjlR4m06FCQwHwYDVR0j\nBBgwFoAU3XAfDSRK1wCTf0wiDjlR4m06FCQwDwYDVR0TAQH/BAUwAwEB/zANBgkq\nhkiG9w0BAQsFAAOCAQEAVTiFfpOzYfXzQxTrl4VxctdQJI52jPjWP55PmK/IO7sb\nn/DKzRNnvn7mN3EDGmshh5i76/hoGA09pK4SdAwJl2QIRJSu3ChH4QCf7n/iIYww\nSxhpOp9QtJA5Cyu4MoemK49Lld/7xf3Qdt1pOgEMz4AGLt2uwS5SdmR4OkSPHqt0\nQq/lgSoiawVOd0UE+5Ocu5S472du/REcVS4KkQdkzZaw9Q7OGIN9G0X0wb0V3UZs\nR2XuApUUaGOl0s0a1uNMv3WkyOrCGS3JkIem6+R59pfliaz6FPcQD+0oXI2gjG3c\nH4VFwOis/oT/2FwYM89j7XZPDpRfUUGMHD53W7YPHA==\n-----END CERTIFICATE-----"""
# Certificate used for admin actions against https://9200
admin_cert = """-----BEGIN CERTIFICATE-----\nMIIDeDCCAmCgAwIBAgIUDsi0qPmptSvcCCXXJ2Fm1pFmvz8wDQYJKoZIhvcNAQEL\nBQAwZTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcM\nB1NlYXR0bGUxGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMRMwEQYDVQQDDApj\naGVmcm9vdGNhMB4XDTIyMDYwMTA3MzMwMFoXDTI1MDUzMTA3MzMwMFowZDELMAkG\nA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUx\nGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMRIwEAYDVQQDDAljaGVmYWRtaW4w\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmAPx686ekg1SaD1FRmkLW\nuIt4i7aoOFm/pAd7teD6AH4Xa3pa3w8ePNljz92xc4FciXakmNoBhiWl1gGff6xk\nzyEJkrj1+EYChIMo82Uu+/WBPVLevhNMQkWYL/tG2UGJNYKUtvKeUoNS9KFLc+6r\n0riD/fnP08+3SlK6o+ZzQAbqwQPAGjfLeGjduNPDJgvulbt98sPS5HPyme2PUk+z\nTg2YEoCI5U/op+OcC7S0HyjiG8IkfU300gpH70iwqDLdZ5KSnonKaxxhtEs5MR3W\nFP3wwh51Dbs43qF39nZMQfUCdOn6VCdH6ZlMv8CKvbpXm7w0TkARUky4FJlnUl2X\nAgMBAAGjITAfMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATANBgkqhkiG\n9w0BAQsFAAOCAQEAQ1GYvQvZHSLd0dVQq91T+yBP15HUuhd/sU4HXCDWNrlpp28f\nAWNwKW5L+p9Xt7DLVOFIl9WR1QowNa6h1E3sDZyAzM2m0wBq9qGzBosJzG+wQkhM\n8v0Rx6ODVw5yy3LxUEEyMQwYH++/aFz3dB+EbH74XFgPYGq4VcpZA5dkFYdzAELA\nT/34HKUpMV6KCI+DQRFKSBOZQnN1WsJs9zcxkl3FIGL7H4IifbmAwzSGS+zDRiHt\nQpc8KJQvH5IQPHam452H5RguC4EaFBJjOe1gg487/dj+kZRRGw+MnFo4Lpp+Ce32\nyx68zYBUuwdHlQEYkDjTQVceKl68CpOKhE2tQw==\n-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
admin_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmAPx686ekg1Sa\nD1FRmkLWuIt4i7aoOFm/pAd7teD6AH4Xa3pa3w8ePNljz92xc4FciXakmNoBhiWl\n1gGff6xkzyEJkrj1+EYChIMo82Uu+/WBPVLevhNMQkWYL/tG2UGJNYKUtvKeUoNS\n9KFLc+6r0riD/fnP08+3SlK6o+ZzQAbqwQPAGjfLeGjduNPDJgvulbt98sPS5HPy\nme2PUk+zTg2YEoCI5U/op+OcC7S0HyjiG8IkfU300gpH70iwqDLdZ5KSnonKaxxh\ntEs5MR3WFP3wwh51Dbs43qF39nZMQfUCdOn6VCdH6ZlMv8CKvbpXm7w0TkARUky4\nFJlnUl2XAgMBAAECggEATgAkonkeinSTKhiMczVytoXcMvYjC4P+18dxJLXfUlks\n5kBAK7an2eNpmjavypOlcx+8ObcAqLqpsfSOqq1JCc0xjtf8RMc1zjUJlBJZtuv4\n/ZMc/0B8vNZe8RWKkk2/N4OHKe2UrsPCpRYBO/zrZp0KyipqWTcDYPJxUPV2cSwg\nu8S+O6duDMteON4Ngo4mhsF2OsS2IRKe5dUptNZE9Zr/c7lJiapRkCu77YOSIud1\nQ9IhPOuhTOmZ5oGiCPiupFhHfbxIc9dTtQFy+q0ngBr3Wao3wH3A6yrSJkfNceF6\nEepFwo9S3ENr6e+dKyYEYRqLn5y5xp0tWxnd6ftAoQKBgQDVYDoa+WPzNc3eW21I\nuOnLWsGSYpYOMjR9yfQPAWcehEXQW138UV2KXJpPMyr1SIj1Uce3D5fcSfoi93yO\n7Bo9t1NI6bcrwCdTyTYwDE4uob3HJcDjYrndLkKq14fuAuiqzIfcbin7h3YyLtHn\nQKb5EM2nbdl/ZSHqt9uv4eXTuQKBgQDHKjaejTyQRGIsbwGErv3G7fp1yXOdDirZ\nX9TG4Mk1gfdSNsNnR1ftOxIVsBgIvVwbS3/Hc9O33ERNZplC+3Mb3RSr6AUxpWBV\n0cL9h28UI2kxInskVk0jcy0aUJuXwHzJwissMzhO7+abbfk6lP+hnDVPTLJK9i+m\nyGnJN4kDzwKBgELrfQ28rZY3h6t3LR0jsV9vxUnt1XX6VPAmiH60R+0QOv0Pyrg5\npIaiaFryh0SKTTnzPhmxsEUMhoC08cG5VrmIZ3x0oFf+WdczQeVr1pFVdLmio44t\nBnHR8mK2WhFRpDr9DpcZjd0vLOisOnS2mCeBF56tGwuTYkHFDAdrZ7MxAoGAdwGK\nUYMjRTEXWGWcCqRlj5BzsB4Hrzjf8bOJeKyojghyt/VxHS1MJLy/OaZXNiGv/79F\nQvC6+YnsZjOAML3/Mg8QYwfo0pl2ztDgKo3ambXvDSUFX9kRjrUrpiW0UyD5b7VO\nBsM0SjafHRDBc3fEp9SnJhM2FgS0xHvMeids/5ECgYEAoMz3QW4sslG3cgXEDhFw\nVu6UUMNuGW2b9ZedgSafkp6pXVVwMMf1eRN3Wz50MIDmMPnlYy0qjf5ooP3kG8F2\nKrhkYVqH3Iuchwz/JpT+fSfoRsheUVPSLJ44Kd5PldlUD5YEPlyWMrH+I49wLXdG\nfiRKmwfrHJg+yKmkdvA/ezY=\n-----END PRIVATE KEY-----"""
# Certificate used for intracluster ssl on port 9300
ssl_cert = """-----BEGIN CERTIFICATE-----\nMIIDdzCCAl+gAwIBAgIUDsi0qPmptSvcCCXXJ2Fm1pFmv0AwDQYJKoZIhvcNAQEL\nBQAwZTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcM\nB1NlYXR0bGUxGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMRMwEQYDVQQDDApj\naGVmcm9vdGNhMB4XDTIyMDYwMTA3MzMwMVoXDTI1MDUzMTA3MzMwMVowYzELMAkG\nA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUx\nGjAYBgNVBAoMEUNoZWYgU29mdHdhcmUgSW5jMREwDwYDVQQDDAhjaGVmbm9kZTCC\nASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM5iKA88y2M7T+OSD2vPTPFJ\nmSoKHEyZ3U8qW1ZL9ORY9c5yLpHazWIQ48S1Ad/OeggrrZG7JWOjBY1aYuXWgPe8\nZQ9nS3mUdEu3QjW52zJb5Tp8qO7MJGVXFNaBGoKDSvIuGpnlruNYLiwJbTj0mzkC\nRKvSXCg7iOszHt72VUkfRQM59iXh3LjNup6TPVMmW8Iamze7/NB9DMz4Ixjkknfc\nO9v1Fp2E+GJonpbIPBZGItBelMOH0g/EIBMASl3GX4+eBLndhcdjsdtzEV/fJE6H\nwgMtJGahb+17ztLK54dkZKQ7ES7WVlIq3Bfw+yepqaI6tnfIprqSaPclmeW+asUC\nAwEAAaMhMB8wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3\nDQEBCwUAA4IBAQBYhcyhj/PeVIcV7uWTK7lZxfEjEwG2Pydch+z8ElVuT8iYjuSE\nUMvJTjrX5topd+u9P1INUJAmjyXI8kJ42AoozCsH79iMwkX51O6Ri8GsAufDVeDf\nuTlNCxpnE2O1W1/l9UVUloTGW515KguPcC4xYdNwA6scN8rlhTtH8vvBteDUE+fq\nucRUikrbokEfgzHl3la0QlvQ8JnKprOAxK2eme815IK75ygpcLWKjveHFdC2VknY\nwbdG/4UzmsZbI2q5raa9nY3pSJ/kQ3IYg0lRyEAtIC1LsDw7aW1+Vlw5VR4arHRo\nLOEtF2OEtA1uREZpdtoViv7K36rTwDYwMDS+\n-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
ssl_key = """-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDOYigPPMtjO0/j\nkg9rz0zxSZkqChxMmd1PKltWS/TkWPXOci6R2s1iEOPEtQHfznoIK62RuyVjowWN\nWmLl1oD3vGUPZ0t5lHRLt0I1udsyW+U6fKjuzCRlVxTWgRqCg0ryLhqZ5a7jWC4s\nCW049Js5AkSr0lwoO4jrMx7e9lVJH0UDOfYl4dy4zbqekz1TJlvCGps3u/zQfQzM\n+CMY5JJ33Dvb9RadhPhiaJ6WyDwWRiLQXpTDh9IPxCATAEpdxl+PngS53YXHY7Hb\ncxFf3yROh8IDLSRmoW/te87SyueHZGSkOxEu1lZSKtwX8PsnqamiOrZ3yKa6kmj3\nJZnlvmrFAgMBAAECggEBAJMQRtN00smHPko/jlWYho95jnbydW/wRE9hM2yu+3as\nHZxaqOyuKaQzvNoy0X8VtseTuD8cSGxTgmVTfx2gWI4v5SOwy4t7SdOaZse6BIRC\nD3o50nc3aMf94Y9ot+dAf2tLhxEbJiBCecRPg1EOnH1nLF/zqk/Q/KP87YabqfJL\n2hV/+ZbUtRzyC88X7zgfHOIPjKF6qZYj2rBF9d6J/nyk4+RGTQXuYMRXRfMa/+Vg\nPQA8vHLOF1ZGbDfLkATcRFy8bVaCHbESRJuVxx377mK3fsZJwP3en3dsANkurJFU\npf0hdW2rL+XoKyBgkd5ZC1XMW6nLBJkhnyuDkWSLwIECgYEA77vdAyXOBIrykR0P\nTnG7d79h3iccYtMEJt3+yK+i/z4xvJ4kUyujXfld+DC2EpudGvAfcPqswMcEfASU\nz7/S7Fjs1DoNqhzVQ2AbLtiXv6gDDqtxRhiQsRebDrCMsy3ak9S+qwx1po/GbAI4\n+Jyd1Ej7nFbr1jaRDE5v/NCkpWkCgYEA3GMAglhMyiiZIp1SCTyZlw/JsgeounW8\nKpCeJW6sRGeKhjU63K6JAKRVH8ZN4BCZAslHgyBlqFavRP1iNGz8aVzijuE3LYv9\ndjClbTKDeL5BVQCMZmMeHRx26A6C2VR3bCeogKCLG2p2w2e6aNyC/5vRswPQ9fHN\n9oQTdP+3Iv0CgYBhsaoARWCuQz1UW4ZITlq6Eti8Ii4UK6/uctsIR2LiJyM3nS5q\nYkch3aQopxkbfiTIvH/jl5Pcv32ZWHiYLLC0tgxU9A9renKCEWEidwtoA/yy9rSj\nfxE/ycHbe6Dqx83iHnlQ1TQAm2idzU4QKiq7Pr6iWF2lHvl/DVvfp9rguQKBgHeX\nNZCFr+3HiAmziu++Na42gAGejF3aQ6hpX5f6bXqVISNgwTc9ctSpWBPs/RdIim9r\nn+W079UgbO2n/eFq/rGCGOLlrZaGr5yyGyKdVaBwxW0F5iotQQsVBiU4sqKSZleH\nUbWy6KmQ5S92Gz6J4oAoIuvcd0ju1RAfbZuAo/VVAoGBAOPXGcUiDIonDKVPTB9l\nW7AYWGXC2qaSCzM5B0A6+Nb4ZqKs1zjtjT1a2JC+EHY9alFo2ccBvkjux8gQmPyX\nuR4wX6ynzUxYIzs6aTPbvxe6d8U8lGK1LpsgLFPxBb9BKIHQ9d62/QUOrb75n2/H\nDEJQGW+rrJ+d9XyEozpuIv+I\n-----END PRIVATE KEY-----"""
