#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

if [[ -f {{pkg.svc_config_path}}/elasticsearch.keystore ]]; then
  elasticsearch-keystore upgrade
else
  elasticsearch-keystore create
fi

chown hab:hab {{pkg.svc_config_path}}/elasticsearch.keystore

secrets-helper show backup-gateway.access_key | elasticsearch-keystore add \
  --stdin \
  --force \
  s3.client.{{cfg.s3.client.name}}.access_key

secrets-helper show backup-gateway.secret_key | elasticsearch-keystore add \
  --stdin \
  --force \
  s3.client.{{cfg.s3.client.name}}.secret_key
