[mlsa]
accept = false

[service]
host = "localhost"
port = 1234

[tls]
key_contents = ""
cert_contents = ""
root_cert_contents = ""

[storage]
database = "chef_config_mgmt_service"
user = "config_mgmt"
max_open_conns = 10
max_idle_conns = 10

# If needed be, we can add more backends
# [mock]
# data = "awesome"
