// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/interservice/teams/teams.proto

package teams

import (
	context "context"
	fmt "fmt"
	version "github.com/chef/automate/api/external/common/version"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Team struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Projects             []string `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{0}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetTeamReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamReq) Reset()         { *m = GetTeamReq{} }
func (m *GetTeamReq) String() string { return proto.CompactTextString(m) }
func (*GetTeamReq) ProtoMessage()    {}
func (*GetTeamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{1}
}

func (m *GetTeamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamReq.Unmarshal(m, b)
}
func (m *GetTeamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamReq.Marshal(b, m, deterministic)
}
func (m *GetTeamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamReq.Merge(m, src)
}
func (m *GetTeamReq) XXX_Size() int {
	return xxx_messageInfo_GetTeamReq.Size(m)
}
func (m *GetTeamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamReq proto.InternalMessageInfo

func (m *GetTeamReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTeamResp struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty" toml:"team,omitempty" mapstructure:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamResp) Reset()         { *m = GetTeamResp{} }
func (m *GetTeamResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamResp) ProtoMessage()    {}
func (*GetTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{2}
}

func (m *GetTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamResp.Unmarshal(m, b)
}
func (m *GetTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamResp.Marshal(b, m, deterministic)
}
func (m *GetTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamResp.Merge(m, src)
}
func (m *GetTeamResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamResp.Size(m)
}
func (m *GetTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamResp proto.InternalMessageInfo

func (m *GetTeamResp) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type ListTeamsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ListTeamsReq) Reset()         { *m = ListTeamsReq{} }
func (m *ListTeamsReq) String() string { return proto.CompactTextString(m) }
func (*ListTeamsReq) ProtoMessage()    {}
func (*ListTeamsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{3}
}

func (m *ListTeamsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTeamsReq.Unmarshal(m, b)
}
func (m *ListTeamsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTeamsReq.Marshal(b, m, deterministic)
}
func (m *ListTeamsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTeamsReq.Merge(m, src)
}
func (m *ListTeamsReq) XXX_Size() int {
	return xxx_messageInfo_ListTeamsReq.Size(m)
}
func (m *ListTeamsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTeamsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListTeamsReq proto.InternalMessageInfo

type ListTeamsResp struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty" toml:"teams,omitempty" mapstructure:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ListTeamsResp) Reset()         { *m = ListTeamsResp{} }
func (m *ListTeamsResp) String() string { return proto.CompactTextString(m) }
func (*ListTeamsResp) ProtoMessage()    {}
func (*ListTeamsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{4}
}

func (m *ListTeamsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTeamsResp.Unmarshal(m, b)
}
func (m *ListTeamsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTeamsResp.Marshal(b, m, deterministic)
}
func (m *ListTeamsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTeamsResp.Merge(m, src)
}
func (m *ListTeamsResp) XXX_Size() int {
	return xxx_messageInfo_ListTeamsResp.Size(m)
}
func (m *ListTeamsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTeamsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListTeamsResp proto.InternalMessageInfo

func (m *ListTeamsResp) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type UpdateTeamReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Projects             []string `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpdateTeamReq) Reset()         { *m = UpdateTeamReq{} }
func (m *UpdateTeamReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamReq) ProtoMessage()    {}
func (*UpdateTeamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{5}
}

func (m *UpdateTeamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamReq.Unmarshal(m, b)
}
func (m *UpdateTeamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamReq.Marshal(b, m, deterministic)
}
func (m *UpdateTeamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamReq.Merge(m, src)
}
func (m *UpdateTeamReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamReq.Size(m)
}
func (m *UpdateTeamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamReq proto.InternalMessageInfo

func (m *UpdateTeamReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTeamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTeamReq) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

type UpdateTeamResp struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty" toml:"team,omitempty" mapstructure:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpdateTeamResp) Reset()         { *m = UpdateTeamResp{} }
func (m *UpdateTeamResp) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamResp) ProtoMessage()    {}
func (*UpdateTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{6}
}

func (m *UpdateTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamResp.Unmarshal(m, b)
}
func (m *UpdateTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamResp.Marshal(b, m, deterministic)
}
func (m *UpdateTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamResp.Merge(m, src)
}
func (m *UpdateTeamResp) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamResp.Size(m)
}
func (m *UpdateTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamResp proto.InternalMessageInfo

func (m *UpdateTeamResp) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type DeleteTeamReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *DeleteTeamReq) Reset()         { *m = DeleteTeamReq{} }
func (m *DeleteTeamReq) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamReq) ProtoMessage()    {}
func (*DeleteTeamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{7}
}

func (m *DeleteTeamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamReq.Unmarshal(m, b)
}
func (m *DeleteTeamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamReq.Marshal(b, m, deterministic)
}
func (m *DeleteTeamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamReq.Merge(m, src)
}
func (m *DeleteTeamReq) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamReq.Size(m)
}
func (m *DeleteTeamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamReq proto.InternalMessageInfo

func (m *DeleteTeamReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTeamResp struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty" toml:"team,omitempty" mapstructure:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *DeleteTeamResp) Reset()         { *m = DeleteTeamResp{} }
func (m *DeleteTeamResp) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamResp) ProtoMessage()    {}
func (*DeleteTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{8}
}

func (m *DeleteTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamResp.Unmarshal(m, b)
}
func (m *DeleteTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamResp.Marshal(b, m, deterministic)
}
func (m *DeleteTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamResp.Merge(m, src)
}
func (m *DeleteTeamResp) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamResp.Size(m)
}
func (m *DeleteTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamResp proto.InternalMessageInfo

func (m *DeleteTeamResp) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type CreateTeamReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" mapstructure:"name,omitempty"`
	Projects             []string `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty" toml:"projects,omitempty" mapstructure:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *CreateTeamReq) Reset()         { *m = CreateTeamReq{} }
func (m *CreateTeamReq) String() string { return proto.CompactTextString(m) }
func (*CreateTeamReq) ProtoMessage()    {}
func (*CreateTeamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{9}
}

func (m *CreateTeamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamReq.Unmarshal(m, b)
}
func (m *CreateTeamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamReq.Marshal(b, m, deterministic)
}
func (m *CreateTeamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamReq.Merge(m, src)
}
func (m *CreateTeamReq) XXX_Size() int {
	return xxx_messageInfo_CreateTeamReq.Size(m)
}
func (m *CreateTeamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamReq proto.InternalMessageInfo

func (m *CreateTeamReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateTeamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTeamReq) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

type CreateTeamResp struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty" toml:"team,omitempty" mapstructure:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *CreateTeamResp) Reset()         { *m = CreateTeamResp{} }
func (m *CreateTeamResp) String() string { return proto.CompactTextString(m) }
func (*CreateTeamResp) ProtoMessage()    {}
func (*CreateTeamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{10}
}

func (m *CreateTeamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamResp.Unmarshal(m, b)
}
func (m *CreateTeamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamResp.Marshal(b, m, deterministic)
}
func (m *CreateTeamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamResp.Merge(m, src)
}
func (m *CreateTeamResp) XXX_Size() int {
	return xxx_messageInfo_CreateTeamResp.Size(m)
}
func (m *CreateTeamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamResp proto.InternalMessageInfo

func (m *CreateTeamResp) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type AddTeamMembersReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	// However, this regex works for V1 and V2 User IDs.
	UserIds              []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" toml:"user_ids,omitempty" mapstructure:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *AddTeamMembersReq) Reset()         { *m = AddTeamMembersReq{} }
func (m *AddTeamMembersReq) String() string { return proto.CompactTextString(m) }
func (*AddTeamMembersReq) ProtoMessage()    {}
func (*AddTeamMembersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{11}
}

func (m *AddTeamMembersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeamMembersReq.Unmarshal(m, b)
}
func (m *AddTeamMembersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeamMembersReq.Marshal(b, m, deterministic)
}
func (m *AddTeamMembersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeamMembersReq.Merge(m, src)
}
func (m *AddTeamMembersReq) XXX_Size() int {
	return xxx_messageInfo_AddTeamMembersReq.Size(m)
}
func (m *AddTeamMembersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeamMembersReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeamMembersReq proto.InternalMessageInfo

func (m *AddTeamMembersReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddTeamMembersReq) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type AddTeamMembersResp struct {
	UserIds              []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" toml:"user_ids,omitempty" mapstructure:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *AddTeamMembersResp) Reset()         { *m = AddTeamMembersResp{} }
func (m *AddTeamMembersResp) String() string { return proto.CompactTextString(m) }
func (*AddTeamMembersResp) ProtoMessage()    {}
func (*AddTeamMembersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{12}
}

func (m *AddTeamMembersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeamMembersResp.Unmarshal(m, b)
}
func (m *AddTeamMembersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeamMembersResp.Marshal(b, m, deterministic)
}
func (m *AddTeamMembersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeamMembersResp.Merge(m, src)
}
func (m *AddTeamMembersResp) XXX_Size() int {
	return xxx_messageInfo_AddTeamMembersResp.Size(m)
}
func (m *AddTeamMembersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeamMembersResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeamMembersResp proto.InternalMessageInfo

func (m *AddTeamMembersResp) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type RemoveTeamMembersReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	// However, this regex works for V1 and V2 User IDs.
	UserIds              []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" toml:"user_ids,omitempty" mapstructure:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *RemoveTeamMembersReq) Reset()         { *m = RemoveTeamMembersReq{} }
func (m *RemoveTeamMembersReq) String() string { return proto.CompactTextString(m) }
func (*RemoveTeamMembersReq) ProtoMessage()    {}
func (*RemoveTeamMembersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{13}
}

func (m *RemoveTeamMembersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTeamMembersReq.Unmarshal(m, b)
}
func (m *RemoveTeamMembersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTeamMembersReq.Marshal(b, m, deterministic)
}
func (m *RemoveTeamMembersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTeamMembersReq.Merge(m, src)
}
func (m *RemoveTeamMembersReq) XXX_Size() int {
	return xxx_messageInfo_RemoveTeamMembersReq.Size(m)
}
func (m *RemoveTeamMembersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTeamMembersReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTeamMembersReq proto.InternalMessageInfo

func (m *RemoveTeamMembersReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveTeamMembersReq) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type RemoveTeamMembersResp struct {
	UserIds              []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" toml:"user_ids,omitempty" mapstructure:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *RemoveTeamMembersResp) Reset()         { *m = RemoveTeamMembersResp{} }
func (m *RemoveTeamMembersResp) String() string { return proto.CompactTextString(m) }
func (*RemoveTeamMembersResp) ProtoMessage()    {}
func (*RemoveTeamMembersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{14}
}

func (m *RemoveTeamMembersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTeamMembersResp.Unmarshal(m, b)
}
func (m *RemoveTeamMembersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTeamMembersResp.Marshal(b, m, deterministic)
}
func (m *RemoveTeamMembersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTeamMembersResp.Merge(m, src)
}
func (m *RemoveTeamMembersResp) XXX_Size() int {
	return xxx_messageInfo_RemoveTeamMembersResp.Size(m)
}
func (m *RemoveTeamMembersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTeamMembersResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTeamMembersResp proto.InternalMessageInfo

func (m *RemoveTeamMembersResp) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetTeamsForMemberReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" toml:"user_id,omitempty" mapstructure:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamsForMemberReq) Reset()         { *m = GetTeamsForMemberReq{} }
func (m *GetTeamsForMemberReq) String() string { return proto.CompactTextString(m) }
func (*GetTeamsForMemberReq) ProtoMessage()    {}
func (*GetTeamsForMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{15}
}

func (m *GetTeamsForMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsForMemberReq.Unmarshal(m, b)
}
func (m *GetTeamsForMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsForMemberReq.Marshal(b, m, deterministic)
}
func (m *GetTeamsForMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsForMemberReq.Merge(m, src)
}
func (m *GetTeamsForMemberReq) XXX_Size() int {
	return xxx_messageInfo_GetTeamsForMemberReq.Size(m)
}
func (m *GetTeamsForMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsForMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsForMemberReq proto.InternalMessageInfo

func (m *GetTeamsForMemberReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetTeamsForMemberResp struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty" toml:"teams,omitempty" mapstructure:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamsForMemberResp) Reset()         { *m = GetTeamsForMemberResp{} }
func (m *GetTeamsForMemberResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamsForMemberResp) ProtoMessage()    {}
func (*GetTeamsForMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{16}
}

func (m *GetTeamsForMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsForMemberResp.Unmarshal(m, b)
}
func (m *GetTeamsForMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsForMemberResp.Marshal(b, m, deterministic)
}
func (m *GetTeamsForMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsForMemberResp.Merge(m, src)
}
func (m *GetTeamsForMemberResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamsForMemberResp.Size(m)
}
func (m *GetTeamsForMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsForMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsForMemberResp proto.InternalMessageInfo

func (m *GetTeamsForMemberResp) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type GetTeamMembershipReq struct {
	// TODO (tc): We can't make this more restrictive until we migrate
	// existing IDs post-GA.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" mapstructure:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamMembershipReq) Reset()         { *m = GetTeamMembershipReq{} }
func (m *GetTeamMembershipReq) String() string { return proto.CompactTextString(m) }
func (*GetTeamMembershipReq) ProtoMessage()    {}
func (*GetTeamMembershipReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{17}
}

func (m *GetTeamMembershipReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamMembershipReq.Unmarshal(m, b)
}
func (m *GetTeamMembershipReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamMembershipReq.Marshal(b, m, deterministic)
}
func (m *GetTeamMembershipReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamMembershipReq.Merge(m, src)
}
func (m *GetTeamMembershipReq) XXX_Size() int {
	return xxx_messageInfo_GetTeamMembershipReq.Size(m)
}
func (m *GetTeamMembershipReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamMembershipReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamMembershipReq proto.InternalMessageInfo

func (m *GetTeamMembershipReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTeamMembershipResp struct {
	UserIds              []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" toml:"user_ids,omitempty" mapstructure:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *GetTeamMembershipResp) Reset()         { *m = GetTeamMembershipResp{} }
func (m *GetTeamMembershipResp) String() string { return proto.CompactTextString(m) }
func (*GetTeamMembershipResp) ProtoMessage()    {}
func (*GetTeamMembershipResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{18}
}

func (m *GetTeamMembershipResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamMembershipResp.Unmarshal(m, b)
}
func (m *GetTeamMembershipResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamMembershipResp.Marshal(b, m, deterministic)
}
func (m *GetTeamMembershipResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamMembershipResp.Merge(m, src)
}
func (m *GetTeamMembershipResp) XXX_Size() int {
	return xxx_messageInfo_GetTeamMembershipResp.Size(m)
}
func (m *GetTeamMembershipResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamMembershipResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamMembershipResp proto.InternalMessageInfo

func (m *GetTeamMembershipResp) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type UpgradeToV2Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpgradeToV2Req) Reset()         { *m = UpgradeToV2Req{} }
func (m *UpgradeToV2Req) String() string { return proto.CompactTextString(m) }
func (*UpgradeToV2Req) ProtoMessage()    {}
func (*UpgradeToV2Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{19}
}

func (m *UpgradeToV2Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeToV2Req.Unmarshal(m, b)
}
func (m *UpgradeToV2Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeToV2Req.Marshal(b, m, deterministic)
}
func (m *UpgradeToV2Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeToV2Req.Merge(m, src)
}
func (m *UpgradeToV2Req) XXX_Size() int {
	return xxx_messageInfo_UpgradeToV2Req.Size(m)
}
func (m *UpgradeToV2Req) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeToV2Req.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeToV2Req proto.InternalMessageInfo

type UpgradeToV2Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *UpgradeToV2Resp) Reset()         { *m = UpgradeToV2Resp{} }
func (m *UpgradeToV2Resp) String() string { return proto.CompactTextString(m) }
func (*UpgradeToV2Resp) ProtoMessage()    {}
func (*UpgradeToV2Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{20}
}

func (m *UpgradeToV2Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeToV2Resp.Unmarshal(m, b)
}
func (m *UpgradeToV2Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeToV2Resp.Marshal(b, m, deterministic)
}
func (m *UpgradeToV2Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeToV2Resp.Merge(m, src)
}
func (m *UpgradeToV2Resp) XXX_Size() int {
	return xxx_messageInfo_UpgradeToV2Resp.Size(m)
}
func (m *UpgradeToV2Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeToV2Resp.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeToV2Resp proto.InternalMessageInfo

type ResetToV1Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ResetToV1Req) Reset()         { *m = ResetToV1Req{} }
func (m *ResetToV1Req) String() string { return proto.CompactTextString(m) }
func (*ResetToV1Req) ProtoMessage()    {}
func (*ResetToV1Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{21}
}

func (m *ResetToV1Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetToV1Req.Unmarshal(m, b)
}
func (m *ResetToV1Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetToV1Req.Marshal(b, m, deterministic)
}
func (m *ResetToV1Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetToV1Req.Merge(m, src)
}
func (m *ResetToV1Req) XXX_Size() int {
	return xxx_messageInfo_ResetToV1Req.Size(m)
}
func (m *ResetToV1Req) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetToV1Req.DiscardUnknown(m)
}

var xxx_messageInfo_ResetToV1Req proto.InternalMessageInfo

type ResetToV1Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ResetToV1Resp) Reset()         { *m = ResetToV1Resp{} }
func (m *ResetToV1Resp) String() string { return proto.CompactTextString(m) }
func (*ResetToV1Resp) ProtoMessage()    {}
func (*ResetToV1Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{22}
}

func (m *ResetToV1Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetToV1Resp.Unmarshal(m, b)
}
func (m *ResetToV1Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetToV1Resp.Marshal(b, m, deterministic)
}
func (m *ResetToV1Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetToV1Resp.Merge(m, src)
}
func (m *ResetToV1Resp) XXX_Size() int {
	return xxx_messageInfo_ResetToV1Resp.Size(m)
}
func (m *ResetToV1Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetToV1Resp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetToV1Resp proto.InternalMessageInfo

type PurgeUserMembershipReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" toml:"user_id,omitempty" mapstructure:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *PurgeUserMembershipReq) Reset()         { *m = PurgeUserMembershipReq{} }
func (m *PurgeUserMembershipReq) String() string { return proto.CompactTextString(m) }
func (*PurgeUserMembershipReq) ProtoMessage()    {}
func (*PurgeUserMembershipReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{23}
}

func (m *PurgeUserMembershipReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeUserMembershipReq.Unmarshal(m, b)
}
func (m *PurgeUserMembershipReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeUserMembershipReq.Marshal(b, m, deterministic)
}
func (m *PurgeUserMembershipReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeUserMembershipReq.Merge(m, src)
}
func (m *PurgeUserMembershipReq) XXX_Size() int {
	return xxx_messageInfo_PurgeUserMembershipReq.Size(m)
}
func (m *PurgeUserMembershipReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeUserMembershipReq.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeUserMembershipReq proto.InternalMessageInfo

func (m *PurgeUserMembershipReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PurgeUserMembershipResp struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" toml:"ids,omitempty" mapstructure:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *PurgeUserMembershipResp) Reset()         { *m = PurgeUserMembershipResp{} }
func (m *PurgeUserMembershipResp) String() string { return proto.CompactTextString(m) }
func (*PurgeUserMembershipResp) ProtoMessage()    {}
func (*PurgeUserMembershipResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a364f54b7032c2c2, []int{24}
}

func (m *PurgeUserMembershipResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeUserMembershipResp.Unmarshal(m, b)
}
func (m *PurgeUserMembershipResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeUserMembershipResp.Marshal(b, m, deterministic)
}
func (m *PurgeUserMembershipResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeUserMembershipResp.Merge(m, src)
}
func (m *PurgeUserMembershipResp) XXX_Size() int {
	return xxx_messageInfo_PurgeUserMembershipResp.Size(m)
}
func (m *PurgeUserMembershipResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeUserMembershipResp.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeUserMembershipResp proto.InternalMessageInfo

func (m *PurgeUserMembershipResp) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*Team)(nil), "chef.automate.domain.teams.Team")
	proto.RegisterType((*GetTeamReq)(nil), "chef.automate.domain.teams.GetTeamReq")
	proto.RegisterType((*GetTeamResp)(nil), "chef.automate.domain.teams.GetTeamResp")
	proto.RegisterType((*ListTeamsReq)(nil), "chef.automate.domain.teams.ListTeamsReq")
	proto.RegisterType((*ListTeamsResp)(nil), "chef.automate.domain.teams.ListTeamsResp")
	proto.RegisterType((*UpdateTeamReq)(nil), "chef.automate.domain.teams.UpdateTeamReq")
	proto.RegisterType((*UpdateTeamResp)(nil), "chef.automate.domain.teams.UpdateTeamResp")
	proto.RegisterType((*DeleteTeamReq)(nil), "chef.automate.domain.teams.DeleteTeamReq")
	proto.RegisterType((*DeleteTeamResp)(nil), "chef.automate.domain.teams.DeleteTeamResp")
	proto.RegisterType((*CreateTeamReq)(nil), "chef.automate.domain.teams.CreateTeamReq")
	proto.RegisterType((*CreateTeamResp)(nil), "chef.automate.domain.teams.CreateTeamResp")
	proto.RegisterType((*AddTeamMembersReq)(nil), "chef.automate.domain.teams.AddTeamMembersReq")
	proto.RegisterType((*AddTeamMembersResp)(nil), "chef.automate.domain.teams.AddTeamMembersResp")
	proto.RegisterType((*RemoveTeamMembersReq)(nil), "chef.automate.domain.teams.RemoveTeamMembersReq")
	proto.RegisterType((*RemoveTeamMembersResp)(nil), "chef.automate.domain.teams.RemoveTeamMembersResp")
	proto.RegisterType((*GetTeamsForMemberReq)(nil), "chef.automate.domain.teams.GetTeamsForMemberReq")
	proto.RegisterType((*GetTeamsForMemberResp)(nil), "chef.automate.domain.teams.GetTeamsForMemberResp")
	proto.RegisterType((*GetTeamMembershipReq)(nil), "chef.automate.domain.teams.GetTeamMembershipReq")
	proto.RegisterType((*GetTeamMembershipResp)(nil), "chef.automate.domain.teams.GetTeamMembershipResp")
	proto.RegisterType((*UpgradeToV2Req)(nil), "chef.automate.domain.teams.UpgradeToV2Req")
	proto.RegisterType((*UpgradeToV2Resp)(nil), "chef.automate.domain.teams.UpgradeToV2Resp")
	proto.RegisterType((*ResetToV1Req)(nil), "chef.automate.domain.teams.ResetToV1Req")
	proto.RegisterType((*ResetToV1Resp)(nil), "chef.automate.domain.teams.ResetToV1Resp")
	proto.RegisterType((*PurgeUserMembershipReq)(nil), "chef.automate.domain.teams.PurgeUserMembershipReq")
	proto.RegisterType((*PurgeUserMembershipResp)(nil), "chef.automate.domain.teams.PurgeUserMembershipResp")
}

func init() {
	proto.RegisterFile("api/interservice/teams/teams.proto", fileDescriptor_a364f54b7032c2c2)
}

var fileDescriptor_a364f54b7032c2c2 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xef, 0x4e, 0xdb, 0x56,
	0x1c, 0xc5, 0x09, 0xe5, 0xcf, 0x8f, 0x85, 0x96, 0x5b, 0x28, 0x99, 0xdb, 0x4a, 0xd1, 0x55, 0xb7,
	0xc1, 0x68, 0xec, 0xc6, 0xb0, 0x4a, 0xeb, 0x87, 0xa9, 0xa3, 0x13, 0x55, 0xa5, 0x55, 0x9b, 0x3c,
	0xca, 0x87, 0x51, 0x8a, 0x2e, 0xf1, 0xaf, 0xc1, 0x53, 0xec, 0xeb, 0xdc, 0xeb, 0x44, 0x53, 0xa7,
	0x49, 0x7d, 0x84, 0xa9, 0x8f, 0xb3, 0x4f, 0x7b, 0x91, 0x3d, 0xc0, 0xde, 0x62, 0xba, 0xb6, 0x13,
	0xdb, 0xc1, 0x18, 0x87, 0x69, 0xfd, 0x02, 0xb6, 0x39, 0xe7, 0x77, 0xce, 0x3d, 0xc4, 0xe7, 0x17,
	0xa0, 0x2c, 0x70, 0x4d, 0xd7, 0x0f, 0x51, 0x48, 0x14, 0x23, 0xb7, 0x8b, 0x66, 0x88, 0xcc, 0x93,
	0xf1, 0x4f, 0x23, 0x10, 0x3c, 0xe4, 0x44, 0xef, 0x9e, 0xe3, 0x5b, 0x83, 0x0d, 0x43, 0xee, 0xb1,
	0x10, 0x0d, 0x87, 0x7b, 0xcc, 0xf5, 0x8d, 0x08, 0xa1, 0xdf, 0xeb, 0x71, 0xde, 0xeb, 0xa3, 0xa9,
	0xc6, 0x30, 0xdf, 0xe7, 0x21, 0x0b, 0x5d, 0xee, 0x27, 0x4c, 0x7d, 0x73, 0xc4, 0xfa, 0xae, 0xc3,
	0x42, 0x34, 0xc7, 0x17, 0xc9, 0x1f, 0xb6, 0x15, 0x1e, 0x7f, 0x0d, 0x51, 0xf8, 0xac, 0x6f, 0x76,
	0xb9, 0xe7, 0x71, 0xdf, 0x1c, 0xa1, 0x90, 0x6e, 0xfa, 0x3b, 0x86, 0xd2, 0x03, 0x98, 0x3f, 0x44,
	0xe6, 0x91, 0x55, 0xa8, 0xb9, 0x4e, 0x53, 0x6b, 0x69, 0x5b, 0xcb, 0x76, 0xcd, 0x75, 0x08, 0x81,
	0x79, 0x9f, 0x79, 0xd8, 0xac, 0x45, 0x4f, 0xa2, 0x6b, 0xa2, 0xc3, 0x52, 0x20, 0xf8, 0x2f, 0xd8,
	0x0d, 0x65, 0xb3, 0xde, 0xaa, 0x6f, 0x2d, 0xdb, 0x93, 0x7b, 0xba, 0x0d, 0xf0, 0x1c, 0x43, 0x35,
	0xca, 0xc6, 0x01, 0xb9, 0x9b, 0x4e, 0xdb, 0x5f, 0xf9, 0xf3, 0x9f, 0xbf, 0xea, 0x0b, 0x62, 0xde,
	0xaa, 0xbd, 0xfe, 0x49, 0x8d, 0xa6, 0xcf, 0x60, 0x65, 0x02, 0x95, 0x01, 0xd9, 0x83, 0x79, 0x75,
	0xd8, 0x08, 0xbd, 0x62, 0xb5, 0x8c, 0xcb, 0xe3, 0x30, 0x22, 0x4e, 0x84, 0xa6, 0xab, 0xf0, 0xc9,
	0xf7, 0xae, 0x8c, 0xa6, 0x48, 0x1b, 0x07, 0xf4, 0x39, 0x34, 0x32, 0xf7, 0x32, 0x20, 0x8f, 0xe1,
	0x46, 0x44, 0x6a, 0x6a, 0xad, 0x7a, 0xa5, 0xb9, 0x31, 0x9c, 0xbe, 0xd7, 0xa0, 0xf1, 0x2a, 0x50,
	0x61, 0x56, 0x39, 0x4c, 0x61, 0x4e, 0xdf, 0x4c, 0xe7, 0xb4, 0x4f, 0x15, 0xed, 0xfe, 0x07, 0x4d,
	0x6f, 0x6a, 0xf4, 0x8e, 0x58, 0xb7, 0xc8, 0x9b, 0x63, 0xd6, 0x7e, 0xf7, 0xa8, 0xfd, 0x75, 0xfb,
	0xf4, 0xe4, 0xb7, 0xce, 0xc3, 0xc7, 0x7b, 0xbf, 0x3f, 0xc8, 0x64, 0x79, 0x00, 0xab, 0x59, 0x07,
	0xd7, 0xce, 0xe8, 0x21, 0x34, 0xbe, 0xc3, 0x3e, 0x56, 0x3b, 0x89, 0x52, 0xcd, 0xa2, 0xaf, 0xad,
	0xfa, 0x87, 0x06, 0x8d, 0x67, 0x02, 0x33, 0x01, 0xee, 0x64, 0x64, 0xef, 0x2a, 0xd9, 0xcb, 0x22,
	0xf8, 0x1f, 0x03, 0xcd, 0x3a, 0xba, 0xf6, 0xd1, 0x04, 0xac, 0x7d, 0xeb, 0x38, 0xea, 0xc1, 0x4b,
	0xf4, 0xce, 0x50, 0xc8, 0x2b, 0x3f, 0x1e, 0x4f, 0x61, 0x69, 0x28, 0x51, 0x9c, 0xba, 0x8e, 0x6c,
	0xd6, 0x22, 0xe7, 0x9f, 0x29, 0x48, 0xeb, 0x83, 0x76, 0x7f, 0x49, 0x6b, 0x6a, 0x74, 0x53, 0x6c,
	0x58, 0xb7, 0xdf, 0x1c, 0x1f, 0x3f, 0x61, 0x7d, 0x7f, 0xe8, 0x3d, 0x39, 0x39, 0x35, 0x76, 0x9e,
	0xb6, 0x4f, 0x76, 0x1e, 0xd8, 0x8b, 0x8a, 0xf6, 0xc2, 0x91, 0xd4, 0x04, 0x32, 0xad, 0x29, 0x03,
	0xf2, 0x69, 0x66, 0xae, 0x16, 0xbd, 0x8a, 0x13, 0xc2, 0x10, 0xd6, 0x6d, 0xf4, 0xf8, 0x08, 0x3f,
	0xae, 0x4f, 0x0b, 0x36, 0x0a, 0x64, 0xcb, 0xad, 0xbe, 0x84, 0xf5, 0xa4, 0x09, 0xe4, 0x01, 0x17,
	0x31, 0x49, 0x59, 0xfd, 0x0a, 0x16, 0x13, 0x4a, 0xe2, 0xf7, 0x9e, 0x32, 0x73, 0xa9, 0x87, 0x85,
	0x78, 0x1e, 0xfd, 0x01, 0x36, 0x0a, 0xc6, 0xfd, 0x87, 0x2e, 0xd8, 0x9d, 0xf8, 0x4b, 0x0e, 0x74,
	0xee, 0x06, 0x57, 0xbe, 0x47, 0xd6, 0xc4, 0x45, 0x96, 0x54, 0x1e, 0xc4, 0x2d, 0xf5, 0xc6, 0xf7,
	0x04, 0x73, 0xf0, 0x90, 0x1f, 0x59, 0xaa, 0xcf, 0xd6, 0xe0, 0x66, 0xee, 0x89, 0x0c, 0x54, 0xe5,
	0xd9, 0x28, 0x31, 0x3c, 0xe4, 0x47, 0x1d, 0x05, 0xb9, 0x09, 0x8d, 0xcc, 0xbd, 0x0c, 0x68, 0x07,
	0xee, 0xfc, 0x38, 0x14, 0x3d, 0x7c, 0x25, 0x51, 0xe4, 0x0d, 0x6f, 0x4e, 0x05, 0x3a, 0x89, 0x6c,
	0x07, 0x36, 0x0b, 0x29, 0x32, 0x20, 0xb7, 0xa0, 0x9e, 0x3a, 0x55, 0x97, 0xd6, 0xdf, 0xcb, 0x70,
	0x23, 0x4a, 0x97, 0xc8, 0xa8, 0xed, 0x8f, 0xe2, 0x4d, 0x42, 0xf6, 0xa6, 0xf2, 0x64, 0x81, 0x6b,
	0xc4, 0x4b, 0xc7, 0x18, 0x2f, 0x9b, 0x04, 0xfa, 0xc2, 0x7f, 0xcb, 0x6d, 0x1c, 0x0c, 0x51, 0x86,
	0x7a, 0x7b, 0x26, 0x16, 0x9d, 0x23, 0xaf, 0x61, 0x31, 0x09, 0x96, 0x7c, 0x5e, 0xf6, 0x1f, 0x4c,
	0xf7, 0x90, 0xfe, 0x45, 0x25, 0x9c, 0x0c, 0xe8, 0x1c, 0x39, 0x83, 0xe5, 0xc9, 0x02, 0x21, 0x5b,
	0x65, 0xbc, 0xec, 0xde, 0xd1, 0xb7, 0x2b, 0x22, 0x23, 0x0d, 0x04, 0x48, 0x7b, 0x88, 0x94, 0x52,
	0x73, 0x0d, 0xaa, 0x7f, 0x59, 0x15, 0x3a, 0x96, 0x49, 0xf7, 0x47, 0xb9, 0x4c, 0x6e, 0xd3, 0x95,
	0xcb, 0xe4, 0x57, 0x52, 0x2c, 0x93, 0x2e, 0x8c, 0x72, 0x99, 0xdc, 0x1a, 0x2a, 0x97, 0xc9, 0xef,
	0x20, 0x3a, 0x47, 0x06, 0xb0, 0x9a, 0x2f, 0x40, 0xd2, 0x2e, 0xe3, 0x5f, 0x28, 0x68, 0xdd, 0x98,
	0x05, 0x1e, 0x49, 0xbe, 0x83, 0xb5, 0x0b, 0x5d, 0x46, 0x1e, 0x95, 0x8d, 0x29, 0x6a, 0x5c, 0xbd,
	0x33, 0x23, 0x63, 0xac, 0x7d, 0xa1, 0xc4, 0xca, 0xb5, 0x8b, 0x2a, 0xb4, 0x5c, 0xbb, 0xb0, 0x25,
	0x73, 0xda, 0x69, 0x17, 0x54, 0xd2, 0xce, 0xb5, 0x4d, 0x25, 0xed, 0x7c, 0xd9, 0xd0, 0x39, 0xf2,
	0x5e, 0x83, 0xdb, 0x05, 0x55, 0x44, 0xac, 0xb2, 0x61, 0xc5, 0x75, 0xa7, 0xef, 0xce, 0xcc, 0x51,
	0x16, 0xf6, 0x3b, 0x3f, 0x9b, 0x3d, 0x37, 0x3c, 0x1f, 0x9e, 0xa9, 0x1e, 0x32, 0xd5, 0x08, 0x73,
	0x3c, 0xc2, 0x2c, 0xfe, 0x22, 0x7f, 0xb6, 0x10, 0x7d, 0x8b, 0xde, 0xfd, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xe5, 0xca, 0x5b, 0x73, 0xe9, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TeamsClient is the client API for Teams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamsClient interface {
	GetVersion(ctx context.Context, in *version.VersionInfoRequest, opts ...grpc.CallOption) (*version.VersionInfo, error)
	GetTeam(ctx context.Context, in *GetTeamReq, opts ...grpc.CallOption) (*GetTeamResp, error)
	ListTeams(ctx context.Context, in *ListTeamsReq, opts ...grpc.CallOption) (*ListTeamsResp, error)
	CreateTeam(ctx context.Context, in *CreateTeamReq, opts ...grpc.CallOption) (*CreateTeamResp, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamReq, opts ...grpc.CallOption) (*UpdateTeamResp, error)
	DeleteTeam(ctx context.Context, in *DeleteTeamReq, opts ...grpc.CallOption) (*DeleteTeamResp, error)
	AddTeamMembers(ctx context.Context, in *AddTeamMembersReq, opts ...grpc.CallOption) (*AddTeamMembersResp, error)
	RemoveTeamMembers(ctx context.Context, in *RemoveTeamMembersReq, opts ...grpc.CallOption) (*RemoveTeamMembersResp, error)
	GetTeamsForMember(ctx context.Context, in *GetTeamsForMemberReq, opts ...grpc.CallOption) (*GetTeamsForMemberResp, error)
	GetTeamMembership(ctx context.Context, in *GetTeamMembershipReq, opts ...grpc.CallOption) (*GetTeamMembershipResp, error)
	PurgeUserMembership(ctx context.Context, in *PurgeUserMembershipReq, opts ...grpc.CallOption) (*PurgeUserMembershipResp, error)
}

type teamsClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamsClient(cc grpc.ClientConnInterface) TeamsClient {
	return &teamsClient{cc}
}

func (c *teamsClient) GetVersion(ctx context.Context, in *version.VersionInfoRequest, opts ...grpc.CallOption) (*version.VersionInfo, error) {
	out := new(version.VersionInfo)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeam(ctx context.Context, in *GetTeamReq, opts ...grpc.CallOption) (*GetTeamResp, error) {
	out := new(GetTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/GetTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) ListTeams(ctx context.Context, in *ListTeamsReq, opts ...grpc.CallOption) (*ListTeamsResp, error) {
	out := new(ListTeamsResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/ListTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) CreateTeam(ctx context.Context, in *CreateTeamReq, opts ...grpc.CallOption) (*CreateTeamResp, error) {
	out := new(CreateTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) UpdateTeam(ctx context.Context, in *UpdateTeamReq, opts ...grpc.CallOption) (*UpdateTeamResp, error) {
	out := new(UpdateTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/UpdateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) DeleteTeam(ctx context.Context, in *DeleteTeamReq, opts ...grpc.CallOption) (*DeleteTeamResp, error) {
	out := new(DeleteTeamResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) AddTeamMembers(ctx context.Context, in *AddTeamMembersReq, opts ...grpc.CallOption) (*AddTeamMembersResp, error) {
	out := new(AddTeamMembersResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/AddTeamMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) RemoveTeamMembers(ctx context.Context, in *RemoveTeamMembersReq, opts ...grpc.CallOption) (*RemoveTeamMembersResp, error) {
	out := new(RemoveTeamMembersResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/RemoveTeamMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeamsForMember(ctx context.Context, in *GetTeamsForMemberReq, opts ...grpc.CallOption) (*GetTeamsForMemberResp, error) {
	out := new(GetTeamsForMemberResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/GetTeamsForMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) GetTeamMembership(ctx context.Context, in *GetTeamMembershipReq, opts ...grpc.CallOption) (*GetTeamMembershipResp, error) {
	out := new(GetTeamMembershipResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/GetTeamMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsClient) PurgeUserMembership(ctx context.Context, in *PurgeUserMembershipReq, opts ...grpc.CallOption) (*PurgeUserMembershipResp, error) {
	out := new(PurgeUserMembershipResp)
	err := c.cc.Invoke(ctx, "/chef.automate.domain.teams.Teams/PurgeUserMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamsServer is the server API for Teams service.
type TeamsServer interface {
	GetVersion(context.Context, *version.VersionInfoRequest) (*version.VersionInfo, error)
	GetTeam(context.Context, *GetTeamReq) (*GetTeamResp, error)
	ListTeams(context.Context, *ListTeamsReq) (*ListTeamsResp, error)
	CreateTeam(context.Context, *CreateTeamReq) (*CreateTeamResp, error)
	UpdateTeam(context.Context, *UpdateTeamReq) (*UpdateTeamResp, error)
	DeleteTeam(context.Context, *DeleteTeamReq) (*DeleteTeamResp, error)
	AddTeamMembers(context.Context, *AddTeamMembersReq) (*AddTeamMembersResp, error)
	RemoveTeamMembers(context.Context, *RemoveTeamMembersReq) (*RemoveTeamMembersResp, error)
	GetTeamsForMember(context.Context, *GetTeamsForMemberReq) (*GetTeamsForMemberResp, error)
	GetTeamMembership(context.Context, *GetTeamMembershipReq) (*GetTeamMembershipResp, error)
	PurgeUserMembership(context.Context, *PurgeUserMembershipReq) (*PurgeUserMembershipResp, error)
}

// UnimplementedTeamsServer can be embedded to have forward compatible implementations.
type UnimplementedTeamsServer struct {
}

func (*UnimplementedTeamsServer) GetVersion(ctx context.Context, req *version.VersionInfoRequest) (*version.VersionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (*UnimplementedTeamsServer) GetTeam(ctx context.Context, req *GetTeamReq) (*GetTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeam not implemented")
}
func (*UnimplementedTeamsServer) ListTeams(ctx context.Context, req *ListTeamsReq) (*ListTeamsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeams not implemented")
}
func (*UnimplementedTeamsServer) CreateTeam(ctx context.Context, req *CreateTeamReq) (*CreateTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedTeamsServer) UpdateTeam(ctx context.Context, req *UpdateTeamReq) (*UpdateTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (*UnimplementedTeamsServer) DeleteTeam(ctx context.Context, req *DeleteTeamReq) (*DeleteTeamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedTeamsServer) AddTeamMembers(ctx context.Context, req *AddTeamMembersReq) (*AddTeamMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeamMembers not implemented")
}
func (*UnimplementedTeamsServer) RemoveTeamMembers(ctx context.Context, req *RemoveTeamMembersReq) (*RemoveTeamMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTeamMembers not implemented")
}
func (*UnimplementedTeamsServer) GetTeamsForMember(ctx context.Context, req *GetTeamsForMemberReq) (*GetTeamsForMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsForMember not implemented")
}
func (*UnimplementedTeamsServer) GetTeamMembership(ctx context.Context, req *GetTeamMembershipReq) (*GetTeamMembershipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamMembership not implemented")
}
func (*UnimplementedTeamsServer) PurgeUserMembership(ctx context.Context, req *PurgeUserMembershipReq) (*PurgeUserMembershipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeUserMembership not implemented")
}

func RegisterTeamsServer(s *grpc.Server, srv TeamsServer) {
	s.RegisterService(&_Teams_serviceDesc, srv)
}

func _Teams_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(version.VersionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetVersion(ctx, req.(*version.VersionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/GetTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeam(ctx, req.(*GetTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/ListTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).ListTeams(ctx, req.(*ListTeamsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).CreateTeam(ctx, req.(*CreateTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/UpdateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).UpdateTeam(ctx, req.(*UpdateTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).DeleteTeam(ctx, req.(*DeleteTeamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_AddTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).AddTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/AddTeamMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).AddTeamMembers(ctx, req.(*AddTeamMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_RemoveTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTeamMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).RemoveTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/RemoveTeamMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).RemoveTeamMembers(ctx, req.(*RemoveTeamMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeamsForMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsForMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeamsForMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/GetTeamsForMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeamsForMember(ctx, req.(*GetTeamsForMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_GetTeamMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).GetTeamMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/GetTeamMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).GetTeamMembership(ctx, req.(*GetTeamMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Teams_PurgeUserMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeUserMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServer).PurgeUserMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chef.automate.domain.teams.Teams/PurgeUserMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServer).PurgeUserMembership(ctx, req.(*PurgeUserMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Teams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chef.automate.domain.teams.Teams",
	HandlerType: (*TeamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Teams_GetVersion_Handler,
		},
		{
			MethodName: "GetTeam",
			Handler:    _Teams_GetTeam_Handler,
		},
		{
			MethodName: "ListTeams",
			Handler:    _Teams_ListTeams_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _Teams_CreateTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _Teams_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _Teams_DeleteTeam_Handler,
		},
		{
			MethodName: "AddTeamMembers",
			Handler:    _Teams_AddTeamMembers_Handler,
		},
		{
			MethodName: "RemoveTeamMembers",
			Handler:    _Teams_RemoveTeamMembers_Handler,
		},
		{
			MethodName: "GetTeamsForMember",
			Handler:    _Teams_GetTeamsForMember_Handler,
		},
		{
			MethodName: "GetTeamMembership",
			Handler:    _Teams_GetTeamMembership_Handler,
		},
		{
			MethodName: "PurgeUserMembership",
			Handler:    _Teams_PurgeUserMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/interservice/teams/teams.proto",
}
