#!{{pkgPathFor "core/bash"}}/bin/bash
set -e

exec 2>&1

# Required to allow common name feild in certificate. Feature soon to deprecated by 1.17
export GODEBUG=x509ignoreCN=0

export DBNAME="{{cfg.storage.database}}"

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

pg-helper ensure-service-database "$DBNAME" || exit 1

exec data-feed-service serve --config {{pkg.svc_config_path}}/config.toml
