#!{{pkgPathFor "core/bash"}}/bin/bash
set -e

exec 2>&1

export DBNAME="{{cfg.storage.database}}"

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

if [ ! -f /hab/.skip_migration ]; then
  pg-helper ensure-service-database "$DBNAME" || exit 1
fi


exec data-feed-service serve --config {{pkg.svc_config_path}}/config.toml
