#!{{pkgPathFor "core/bash"}}/bin/bash
set -e
exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

export COMPLIANCE_DBNAME="{{cfg.storage.compliance_database}}"
export A1_DBNAME="{{cfg.storage.a1_database}}"
export DBNAME="{{cfg.storage.database}}"

source {{pkg.svc_path}}/hooks/reconfigure
source {{pkg.svc_config_path}}/migration.sh

trigger_migrations

pg-helper ensure-service-database "$DBNAME" || exit 1

# Copy the migrations files
cp -r {{pkg.path}}/migrations/* {{pkg.svc_static_path}}/

# Setting coming from our default.toml
CONFIG="--log-level {{cfg.log.level}}"
CONFIG="$CONFIG --port {{cfg.service.port}}"

# Interval in minutes to poll for node status.
CONFIG="$CONFIG --manager-awsec2-poll {{cfg.nodemanager.awsec2_polling_interval}}"
CONFIG="$CONFIG --manager-azurevm-poll {{cfg.nodemanager.azurevm_polling_interval}}"
CONFIG="$CONFIG --manager-manual-poll {{cfg.nodemanager.manual_polling_interval}}"

# Mutual TLS Configuration
CONFIG="$CONFIG --cert {{pkg.svc_config_path}}/service.crt"
CONFIG="$CONFIG --key {{pkg.svc_config_path}}/service.key"
CONFIG="$CONFIG --root-cert {{pkg.svc_config_path}}/root_ca.crt"

# If we have a config pointing to an specific host,
# lets use it, otherwise use the ipaddress of the server
{{~#if cfg.service.host}}
CONFIG="$CONFIG --host {{cfg.service.host}}"
{{else}}
CONFIG="$CONFIG --host {{sys.ip}}"
{{~/if}}

# get secrets service binding, used for storing secrets
{{~#eachAlive bind.secrets-service.members as |secrets|}}
{{~#if @last}}
addNoProxy {{secrets.sys.ip}}
CONFIG="$CONFIG --secrets-host {{secrets.sys.ip}} --secrets-port {{secrets.cfg.port}}"
{{~/if}}
{{~/eachAlive}}

# get event service binding, used for publishing event
{{~#eachAlive bind.event-service.members as |event|}}
{{~#if @last}}
addNoProxy {{event.sys.ip}}
CONFIG="$CONFIG --event-endpoint {{event.sys.ip}}:{{event.cfg.port}}"
{{~/if}}
{{~/eachAlive}}

# Postgres
PG_BACKEND="--postgres-database {{cfg.storage.database}} --migrations-path {{pkg.svc_static_path}}"

export HOME="{{pkg.svc_data_path}}"

# Start our service
exec nodemanager-service run ${CONFIG} ${PG_BACKEND}
