#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

pg-helper ensure-service-database "{{cfg.storage.database}}"

pg-helper create-extension "{{cfg.storage.database}}" "pgcrypto"

exec session-service {{pkg.svc_config_path}}/config.yml
